aMule: CIPFilterTask Class Reference
CIPFilterTask Class Reference
This task loads the two ipfilter.dat files, a task that can take quite a while on a slow system with a large dat- file.
Classes
struct rangeObject
This structure is used to contain the range-data in the rangemap.
Public Member Functions
CIPFilterTask (wxEvtHandler *owner)
Private Types
typedef CRangeMap< rangeObject,
uint32 > IPMap
Private Member Functions
void Entry ()
bool AddIPRange (uint32 IPStart, uint32 IPEnd, uint16 AccessLevel, const char *DEBUG_ONLY(Description))
int LoadFromFile (const wxString &file)
Private Attributes
bool m_storeDescriptions
CIPFilter::RangeIPs m_rangeIPs
CIPFilter::RangeLengths m_rangeLengths
CIPFilter::RangeNames m_rangeNames
wxEvtHandler * m_owner
IPMap m_result
Detailed Description
This task loads the two ipfilter.dat files, a task that can take quite a while on a slow system with a large dat- file.
Member Function Documentation
bool CIPFilterTask::AddIPRange (uint32 IPStart, uint32 IPEnd, uint16 AccessLevel, const char * DEBUG_ONLYDescription) [inline, private]
Helper function.
Parameters:
IPstart The start of the IP-range.
IPend The end of the IP-range, must be less than or equal to IPstart.
AccessLevel The AccessLevel of this range.
Description The assosiated description of this range.
Returns:
true if the range was added, false if it was discarded.
This function inserts the specified range into the IPMap. Invalid ranges where the AccessLevel is not within the range 0..255, or where IPEnd < IPstart not inserted.
References CIPFilterTask::rangeObject::AccessLevel, and CRangeMap< VALUE, KEYTYPE >::insert().
Referenced by LoadFromFile().
void CIPFilterTask::Entry () [inline, private, virtual]
See also:
wxThread::Entry
Implements CThreadTask.
References CRangeMap< VALUE, KEYTYPE >::begin(), CRangeMap< VALUE, KEYTYPE >::end(), LoadFromFile(), m_owner, and CRangeMap< VALUE, KEYTYPE >::size().
int CIPFilterTask::LoadFromFile (const wxString & file) [inline, private]
Loads a IP-list from the specified file, can be text or zip.
Returns:
True if the file was loaded, false otherwise.
References AddIPRange(), CPath::FileExists(), CPath::GetRaw(), CLogger::IsEnabled(), and CThreadTask::TestDestroy().
Referenced by Entry().
The documentation for this class was generated from the following file:
src/IPFilter.cpp