aMule: Kademlia::CUInt128 Class Reference
Kademlia::CUInt128 Class Reference
Public Member Functions
CUInt128 (const CUInt128 &value) throw ()
CUInt128 (bool fill=false) throw ()
CUInt128 (uint32_t value) throw ()
CUInt128 (const uint8_t *valueBE) throw ()
CUInt128 (const CUInt128 &value, uint32_t numBits)
unsigned GetBitNumber (unsigned bit) const throw ()
int CompareTo (const CUInt128 &other) const throw ()
int CompareTo (uint32_t value) const throw ()
wxString ToHexString () const
wxString ToBinaryString (bool trim=false) const
void ToByteArray (uint8_t *b) const
uint32_t Get32BitChunk (unsigned val) const throw ()
void Set32BitChunk (unsigned chunk, uint32_t value)
CUInt128 & SetValue (const CUInt128 &value) throw ()
CUInt128 & SetValue (uint32_t value) throw ()
CUInt128 & SetValueBE (const uint8_t *valueBE) throw ()
void StoreCryptValue (uint8_t *buf) const
CUInt128 & SetBitNumber (unsigned bit, unsigned value)
CUInt128 & ShiftLeft (unsigned bits) throw ()
CUInt128 & Add (const CUInt128 &value) throw ()
CUInt128 & Add (uint32_t value) throw ()
CUInt128 & Subtract (const CUInt128 &value) throw ()
CUInt128 & Subtract (uint32_t value) throw ()
CUInt128 & XOR (const CUInt128 &value) throw ()
CUInt128 & XORBE (const uint8_t *valueBE) throw ()
bool operator< (const CUInt128 &value) const throw ()
bool operator> (const CUInt128 &value) const throw ()
bool operator<= (const CUInt128 &value) const throw ()
bool operator>= (const CUInt128 &value) const throw ()
bool operator== (const CUInt128 &value) const throw ()
bool operator!= (const CUInt128 &value) const throw ()
CUInt128 & operator= (const CUInt128 &value) throw ()
CUInt128 & operator+= (const CUInt128 &value) throw ()
CUInt128 & operator-= (const CUInt128 &value) throw ()
CUInt128 & operator^= (const CUInt128 &value) throw ()
CUInt128 operator+ (const CUInt128 &value) const throw ()
CUInt128 operator- (const CUInt128 &value) const throw ()
CUInt128 operator^ (const CUInt128 &value) const throw ()
bool operator< (uint32_t value) const throw ()
bool operator> (uint32_t value) const throw ()
bool operator<= (uint32_t value) const throw ()
bool operator>= (uint32_t value) const throw ()
bool operator== (uint32_t value) const throw ()
bool operator!= (uint32_t value) const throw ()
CUInt128 & operator= (uint32_t value) throw ()
CUInt128 & operator+= (uint32_t value) throw ()
CUInt128 & operator-= (uint32_t value) throw ()
CUInt128 & operator^= (uint32_t value) throw ()
CUInt128 operator+ (uint32_t value) const throw ()
CUInt128 operator- (uint32_t value) const throw ()
CUInt128 operator^ (uint32_t value) const throw ()
CUInt128 operator<< (uint32_t bits) const throw ()
CUInt128 & operator<<= (uint32_t bits) throw ()
Private Member Functions
bool IsZero () const throw ()
Private Attributes
uint32_t m_data [4]
Constructor & Destructor Documentation
CUInt128::CUInt128 (const CUInt128 & value, uint32_t numBits)
Generates a new number, copying the most significant 'numBits' bits from 'value'.
The remaining bits are randomly generated.
References GetBitNumber(), and SetBitNumber().
Member Function Documentation
unsigned Kademlia::CUInt128::GetBitNumber (unsigned bit) const throw () [inline]
Bit at level 0 being most significant.
Referenced by CUInt128().
CUInt128& Kademlia::CUInt128::SetBitNumber (unsigned bit, unsigned value) [inline]
Bit at level 0 being most significant.
Referenced by CUInt128().
void CUInt128::StoreCryptValue (uint8_t * buf) const
Stores value used by the crypt functions.
Since eMule started to use the value as-is (four little-endian 32-bit integers in big-endian order), we have to reproduce that same representation on every platform.
Parameters:
buf Buffer to hold the value. Must be large enough to hold the data (16 bytes at least), and must not be NULL.
The documentation for this class was generated from the following files:
src/kademlia/utils/UInt128.h
src/kademlia/utils/UInt128.cpp