aMule: CHashingTask Class Reference
CHashingTask Class Reference
This task performs MD4 and/or AICH hashings of a file, depending on the type.
#include <ThreadTasks.h>
Public Member Functions
CHashingTask (const CPath &path, const CPath &filename, const CPartFile *part=NULL)
CHashingTask (const CKnownFile *toAICHHash)
Protected Types
enum EHashes { EH_AICH = 1, EH_MD4 = 2 }
Protected Member Functions
virtual void OnLastTask ()
virtual void Entry ()
bool CreateNextPartHash (CFileAutoClose &file, uint16 part, CKnownFile *owner, EHashes toHash)
Protected Attributes
CPath m_path
CPath m_filename
EHashes m_toHash
const CKnownFile * m_owner
Detailed Description
This task performs MD4 and/or AICH hashings of a file, depending on the type.
For new shared files (using the first constructor, with part == NULL), both MD4 and AICH hashes are created. For incomplete partfiles (rehashed due to changed timestamps), only MD4 hashing is done. For complete partfiles, both MD4 and AICH hashing is done.
For existing shared files (using the second constructor), only an AICH hash is created.
See also:
CHashingEvent
CAICHSyncTask
Constructor & Destructor Documentation
CHashingTask::CHashingTask (const CPath & path, const CPath & filename, const CPartFile * part = NULL)
Schedules a partfile or new shared file for hashing.
Parameters:
path The full path, without filename.
filename The actual filename.
part Used to identify the owner in the event-handler (PartFiles only).
CHashingEvents sent by this type of tasks have the id MULE_EVT_HASHING.
See also:
EVT_MULE_HASHING
References m_toHash.
CHashingTask::CHashingTask (const CKnownFile * toAICHHash)
Schedules a KnownFile to have a AICH hashset created, used by CAICHSyncTask.
CHashingEvents sent by this type of tasks have the id MULE_EVT_AICH_HASHING.
See also:
EVT_MULE_AICH_HASHING
Member Function Documentation
bool CHashingTask::CreateNextPartHash (CFileAutoClose & file, uint16 part, CKnownFile * owner, EHashes toHash) [protected]
Helper function for hashing a PARTSIZE chunk of a file.
Parameters:
file The file to read from.
part The number of the part to hash.
owner The known- (or part) file representing that file. createAICH Specifies if AICH hash-sets should be created as well.
Returns:
Returns false on read-errors, true otherwise.
This function will create a MD4 hash and, if specified, a AICH hashset for the next part of the file. This function makes the assumption that it wont be called for closed or EOF files.
References CFileAutoClose::Eof().
Referenced by Entry().
void CHashingTask::Entry () [protected, virtual]
See also:
CThreadTask::Entry
Implements CThreadTask.
References CreateNextPartHash(), CScopedPtr< TYPE >::get(), CFileAutoClose::GetLength(), CPath::GetModificationTime(), CPath::JoinPaths(), m_filename, m_owner, m_path, m_toHash, CFileAutoClose::Open(), CScopedPtr< TYPE >::release(), and CThreadTask::TestDestroy().
void CHashingTask::OnLastTask () [protected, virtual]
See also:
CThreadTask::OnLastTask
Reimplemented from CThreadTask.
References CThreadScheduler::AddTask(), and CThreadTask::GetType().
The documentation for this class was generated from the following files:
src/ThreadTasks.h
src/ThreadTasks.cpp