aMule: CStatTreeItemSimple Class Reference
CStatTreeItemSimple Class Reference
Simple tree item.
#include <StatTree.h>
Public Member Functions
CStatTreeItemSimple (const wxString &label, unsigned flags=stNone, enum EDisplayMode displaymode=dmDefault)
void SetDisplayMode (enum EDisplayMode mode)
void SetValue (uint64_t value)
void SetValue (double value)
void SetValue (const wxString &value)
virtual wxString GetDisplayString () const
virtual bool IsVisible () const
Protected Member Functions
virtual void AddECValues (CECTag *tag) const
Protected Attributes
enum EValueType m_valuetype
enum EDisplayMode m_displaymode
union {
uint64_t m_intvalue
double m_floatvalue
};
wxString m_stringvalue
Detailed Description
Simple tree item.
This tree item has one value and nothing speciality. :) The value might be an arbitrary integer or floating point type, or a wxString string.
The item is able to display value in different formats, see SetDisplayMode().
Note:
that you have to specify the right format code on 'label', i.e.: s for string and integers with displayMode dmTime or dmBytes, u or similar for integers, and f or similar for floating point types.
You have to call SetValue() after creation for non-integer values, otherwise you'll get undesired results.
Constructor & Destructor Documentation
CStatTreeItemSimple::CStatTreeItemSimple (const wxString & label, unsigned flags = stNone, enum EDisplayMode displaymode = dmDefault) [inline]
Constructor.
See also:
CStatTreeItemBase::CStatTreeItemBase
References SetValue().
Member Function Documentation
void CStatTreeItemSimple::AddECValues (CECTag * tag) const [protected, virtual]
Add values to EC tag being generated.
Parameters:
tag The tag to which values should be added.
See also:
CStatTreeItemBase::AddECValues
Reimplemented from CStatTreeItemBase.
References CECTag::AddTag(), dmBytes, dmTime, m_displaymode, m_floatvalue, m_intvalue, m_stringvalue, and m_valuetype.
wxString CStatTreeItemSimple::GetDisplayString () const [virtual]
See also:
CStatTreeItemBase::GetDisplayString()
Reimplemented from CStatTreeItemBase.
References dmBytes, dmTime, m_displaymode, m_floatvalue, m_intvalue, CStatTreeItemBase::m_label, m_stringvalue, and m_valuetype.
bool CStatTreeItemSimple::IsVisible () const [virtual]
See also:
CStatTreeItemBase::IsVisible()
Reimplemented from CStatTreeItemBase.
References CStatTreeItemBase::m_flags, m_floatvalue, m_intvalue, m_stringvalue, m_valuetype, and stHideIfZero.
void CStatTreeItemSimple::SetValue (const wxString & value) [inline]
Sets a string type value.
Parameters:
value the value to be set.
References m_stringvalue, and m_valuetype.
void CStatTreeItemSimple::SetValue (double value) [inline]
Sets a floating point type value.
Parameters:
value the value to be set.
References m_floatvalue, and m_valuetype.
void CStatTreeItemSimple::SetValue (uint64_t value) [inline]
Sets an integer type value.
Parameters:
value the value to be set.
References m_intvalue, and m_valuetype.
Referenced by CStatTreeItemSimple().
The documentation for this class was generated from the following files:
src/StatTree.h
src/StatTree.cpp