aMule: CECSocket Class Reference
CECSocket Class Reference
Socket handler for External Communications (EC).
#include <ECSocket.h>
Public Member Functions
CECSocket (bool use_events)
bool ConnectSocket (uint32_t ip, uint16_t port)
void CloseSocket ()
bool HaveNotificationSupport () const
void SendPacket (const CECPacket *packet)
const CECPacket * SendRecvPacket (const CECPacket *request)
virtual const CECPacket * OnPacketReceived (const CECPacket *packet, uint32 trueSize)
virtual std::string GetLastErrorMsg ()
virtual void OnError ()
virtual void OnLost ()
virtual void OnConnect ()
void OnInput ()
void OnOutput ()
bool WouldBlock ()
bool GotError ()
void SocketRead (void *ptr, size_t len)
void SocketWrite (const void *ptr, size_t len)
bool SocketError ()
bool SocketRealError ()
size_t GetLastCount ()
bool WaitSocketConnect (long secs=-1, long msecs=0)
bool WaitSocketWrite (long secs=-1, long msecs=0)
bool WaitSocketRead (long secs=-1, long msecs=0)
bool IsSocketConnected ()
void DestroySocket ()
bool DataPending ()
Protected Attributes
uint32_t m_my_flags
bool m_haveNotificationSupport
Private Member Functions
const CECPacket * ReadPacket ()
uint32 WritePacket (const CECPacket *packet)
bool ReadNumber (void *buffer, size_t len)
bool ReadBuffer (void *buffer, size_t len)
bool ReadHeader ()
bool WriteNumber (const void *buffer, size_t len)
bool WriteBuffer (const void *buffer, size_t len)
bool FlushBuffers ()
size_t ReadBufferFromSocket (void *buffer, size_t len)
void WriteBufferToSocket (const void *buffer, size_t len)
virtual void WriteDoneAndQueueEmpty ()=0
virtual bool InternalConnect (uint32_t ip, uint16_t port, bool wait)=0
virtual size_t InternalLastCount ()=0
virtual bool InternalWaitOnConnect (long secs=-1, long msecs=0)=0
virtual bool InternalWaitForWrite (long secs=-1, long msecs=0)=0
virtual bool InternalWaitForRead (long secs=-1, long msecs=0)=0
virtual int InternalGetLastError ()=0
virtual void InternalClose ()=0
virtual bool InternalError ()=0
virtual void InternalRead (void *ptr, size_t len)=0
virtual void InternalWrite (const void *ptr, size_t len)=0
virtual bool InternalIsConnected ()=0
virtual void InternalDestroy ()=0
virtual bool IsAuthorized ()
Private Attributes
const bool m_use_events
std::list< CQueuedData * > m_output_queue
std::vector< unsigned char > m_in_ptr
std::vector< unsigned char > m_out_ptr
std::auto_ptr< CQueuedData > m_curr_rx_data
std::auto_ptr< CQueuedData > m_curr_tx_data
uint32_t m_rx_flags
uint32_t m_tx_flags
size_t m_bytes_needed
bool m_in_header
uint32_t m_curr_packet_len
z_stream m_z
Static Private Attributes
static const unsigned int EC_SOCKET_BUFFER_SIZE = 2048
static const unsigned int EC_HEADER_SIZE = 8
Friends
class CECPacket
class CECTag
Detailed Description
Socket handler for External Communications (EC).
CECSocket takes care of the transmission of EC packets
Member Function Documentation
std::string CECSocket::GetLastErrorMsg () [virtual]
Get a message describing the error.
Parameters:
error The code of the error for which a message should be returned.
Returns:
The text descibing the error.
Referenced by OnError().
void CECSocket::OnConnect () [virtual]
Event handler for connection events.
This function is called when a connection attempt succeeds.
Reimplemented in CRemoteConnect.
void CECSocket::OnError () [virtual]
Error handler.
This function is called when an error occurs. Use GetLastError() and GetErrorMsg() to find out the nature of the error.
The default error handler prints out an error message in debug builds, and destroys the socket.
References GetLastErrorMsg().
Referenced by SendRecvPacket().
void CECSocket::OnLost () [virtual]
Socket lost event handler.
This function is called when the socket is lost (either because of a network failure or because the remote end closed the socket gracefully).
The default handler destroys the socket.
Reimplemented in CECServerSocket, and CRemoteConnect.
const CECPacket * CECSocket::OnPacketReceived (const CECPacket * packet, uint32 trueSize) [virtual]
Event handler function called when a new packet is received.
Parameters:
packet The packet that has been received.
Returns:
The reply packet or NULL if no reply needed.
In this function the application should process the received packet, and create a reply if necessary. The reply must be allocated on the heap with new. If no reply is necessary, the return value of the function should be NULL. The library will delete both packets.
Note:
This function won't be called for packets received via the SendRecvPacket() function.
Reimplemented in CECServerSocket, and CRemoteConnect.
void CECSocket::SendPacket (const CECPacket * packet)
Sends an EC packet and returns immediately.
Parameters:
packet The CECPacket packet to be sent.
This is an asynchronous call, the function returns immediately and the packet is sent on idle time.
Note:
It's the caller's responsibilty to delete the packet.
Reimplemented in CRemoteConnect.
Referenced by SendRecvPacket().
const CECPacket * CECSocket::SendRecvPacket (const CECPacket * request)
Sends an EC packet and waits for a reply.
Parameters:
request The CECPacket packet to be sent.
Returns:
The reply packet for the request.
Unlike SendPacket(), this call is synchronous and blocking. The packet is sent immediately (or at least as soon as possible), and the function does not return until a reply is received, or a timeout encountered.
The returned packet will be allocated on the heap with new, or NULL is returned in case of an error (timeout).
Note:
It's the caller's responsibilty to delete both request and reply.
OnPacketReceived() won't be called for packets received via this function.
References OnError(), and SendPacket().
The documentation for this class was generated from the following files:
src/libs/ec/cpp/ECSocket.h
src/libs/ec/cpp/ECSocket.cpp