aMule: CFileDataIO Class Reference
CFileDataIO Class Reference
This class provides a interface for safe file IO.
#include <SafeFile.h>
Public Member Functions
virtual ~CFileDataIO ()
virtual uint64 GetPosition () const =0
virtual uint64 GetLength () const =0
virtual bool Eof () const
virtual uint64 Seek (sint64 offset, wxSeekMode from=wxFromStart) const
virtual void Read (void *buffer, size_t count) const
virtual void Write (const void *buffer, size_t count)
virtual wxString ReadString (bool bOptUTF8, uint8 lenBytes=2, bool SafeRead=false) const
virtual wxString ReadOnlyString (bool bOptUTF8, uint16 length) const
virtual void WriteString (const wxString &str, EUtf8Str encoding=utf8strNone, uint8 lenBytes=2)
CTag * ReadTag (bool bOptACP=false) const
void ReadTagPtrList (TagPtrList *taglist, bool bOptACP=false) const
void WriteTag (const CTag &tag)
void WriteTagPtrList (const TagPtrList &tagList)
uint64 GetIntTagValue () const
bool IsEmpty ()
void Append (const uint8 *buffer, int n)
Protected Member Functions
virtual sint64 doSeek (sint64 offset) const =0
Private Member Functions
void WriteStringCore (const char *str, EUtf8Str encoding, uint8 lenBytes)
virtual uint8 ReadUInt8 () const
virtual uint16 ReadUInt16 () const
virtual uint32 ReadUInt32 () const
virtual uint64 ReadUInt64 () const
virtual CUInt128 ReadUInt128 () const
virtual CMD4Hash ReadHash () const
virtual float ReadFloat () const
virtual unsigned char * ReadBsob (uint8 *size) const
virtual void WriteUInt8 (uint8 value)
virtual void WriteUInt16 (uint16 value)
virtual void WriteUInt32 (uint32 value)
virtual void WriteUInt64 (uint64 value)
virtual void WriteUInt128 (const CUInt128 &value)
virtual void WriteHash (const CMD4Hash &value)
virtual void WriteFloat (float value)
virtual void WriteBsob (const unsigned char *val, uint8 size)
virtual sint64 doRead (void *buffer, size_t count) const =0
virtual sint64 doWrite (const void *buffer, size_t count)=0
Detailed Description
This class provides a interface for safe file IO.
Basic IO operations will either succeed or throw an exception, so that failure cannot be ignored. There are currently 3 types of failures: Read past EOF, errors while reading, and errors while writing.
Beyond basic IO, the interface provides functions for reading and writing a number of simple data-types. These are all written and read as little-endian in order to allow for communication across platforms.
Note that when empty areas are created, for instance by seeking past the end, then writing, the value of bytes where no data was explicitly written is not specified.
Member Function Documentation
virtual sint64 CFileDataIO::doRead (void * buffer, size_t count) const [protected, pure virtual]
The actual read / write function, as implemented by subclasses.
Parameters:
buffer The buffer to read data into / write data from.
count The number of bytes to read / written.
Returns:
The number of bytes read / written or -1 in case of errors.
Note that the return value must be the actual number of bytes read or written, with the exception that in case of errors, -1 may be returned. This is because the return value is used to detect if the operation succeded.
This function should not throw Either of the CSafeIOExceptions, this is done by the CSafeFileIO::Read and the CSafeFileIO::Write functions.
Implemented in CFile, and CMemFile.
Referenced by Read().
virtual sint64 CFileDataIO::doSeek (sint64 offset) const [protected, pure virtual]
The actual seek function, as implemented by subclasses.
Parameters:
offset The absolute offset to seek to.
Returns:
The resulting offset.
This function should not throw of the CSafeIOExceptions, this is handled by the CSafeFileIO::Seek. At the moment, seeks that fail are considered a fatal error.
Implemented in CFile, and CMemFile.
Referenced by Seek().
void CFileDataIO::Read (void * buffer, size_t count) const [virtual]
Reads 'count' bytes into 'buffer'.
Parameters:
buffer The target buffer.
count The number of bytes to read.
Note that Read will read the specified number of bytes unless this would read past the end of the file. In that case, a CEOFException is thrown and the position and target buffer is left unchanged.
However, it is also possible that the read will fail due to IO errors (bad hardware, ect), in which case an CIOFailureException will be thrown.
References doRead(), and Eof().
Referenced by CAICHSyncTask::ConvertToKnown2ToKnown264(), CFileAutoClose::ReadAt(), ReadOnlyString(), and ReadUInt8().
wxString CFileDataIO::ReadOnlyString (bool bOptUTF8, uint16 length) const [virtual]
Reads a string from the file, where the length is specified directly.
Parameters:
bOptUTF8 Specifies if the string is UTF8 encoded.
length The length of the string.
Returns:
The resulting text-string.
This function is typically used when the text-fields length is not stored as an integer-field in front of the text-field.
References Read().
Referenced by ReadString().
wxString CFileDataIO::ReadString (bool bOptUTF8, uint8 lenBytes = 2, bool SafeRead = false) const [virtual]
Reads a string from the file.
Parameters:
bOptUTF8 Specifies if the string is UTF8 encoded.
lenBytes The number of bytes used to store the string length.
SafeRead Avoids throwing CEOFException, see below.
Returns:
The resulting text-string.
Note that when SafeRead is set to true, CSafeFileIO will crop the length read from the lenght-field (see lenBytes), so that at most GetLength() - GetPosition() bytes are read.
See also:
CSafeFileIO::Read
References GetLength(), GetPosition(), and ReadOnlyString().
uint8 CFileDataIO::ReadUInt8 () const [virtual]
Reads the given type from the file, stored as little-endian.
See also:
CSafeFileIO::Read
References Read().
Referenced by CPreferences::CPreferences(), CAICHSyncTask::Entry(), and CSearchList::ProcessSharedFileList().
uint64 CFileDataIO::Seek (sint64 offset, wxSeekMode from = wxFromStart) const [virtual]
Changes the file position.
Note that seeking to an negative position is an illegal operation.
See also:
wxFile::Seek
References doSeek(), GetLength(), and GetPosition().
Referenced by CAllocateFileTask::Entry(), CAICHSyncTask::Entry(), CSearchList::KademliaSearchKeyword(), CDownloadQueue::OnHostnameResolved(), CFileAutoClose::ReadAt(), and CFileAutoClose::WriteAt().
void CFileDataIO::Write (const void * buffer, size_t count) [virtual]
Write 'count' bytes from 'buffer' into the file.
Parameters:
buffer The source-data buffer.
count The number of bytes to write.
Note that Write will throw a CIOFailureException if it fails to write the specified number of bytes, which can be caused by hardware failures, lack of free space, etc.
Referenced by CAICHSyncTask::ConvertToKnown2ToKnown264(), CAllocateFileTask::Entry(), CFileAutoClose::WriteAt(), WriteStringCore(), and WriteUInt8().
void CFileDataIO::WriteString (const wxString & str, EUtf8Str encoding = utf8strNone, uint8 lenBytes = 2) [virtual]
Writes a text-string to the file.
Parameters:
str The string to be written.
encoding The text-ecoding, see EUtf8Str.
lenBytes The number of bytes used to store the string length.
Valid values for the 'lenBytes' parameters is 0 bytes (no length field), 2 bytes and 4 bytes.
See also:
CSafeFileIO::Write
References WriteStringCore().
Referenced by CUpDownClient::SendChatMessage().
void CFileDataIO::WriteStringCore (const char * str, EUtf8Str encoding, uint8 lenBytes) [private]
Helper-function that does the actual writing of the string.
Parameters:
str The string to be written.
encoding The encoding of the string.
lenBytes The number of bytes used to store the string length.
References Write().
Referenced by WriteString().
void CFileDataIO::WriteUInt8 (uint8 value) [virtual]
Writes a value of the given type to the file, storing it as little-endian.
See also:
CSafeFileIO::Write
References Write().
Referenced by CDownloadQueue::AddSearchToDownload(), CAICHSyncTask::ConvertToKnown2ToKnown264(), CAllocateFileTask::Entry(), CAICHSyncTask::Entry(), and CDownloadQueue::OnHostnameResolved().
The documentation for this class was generated from the following files:
src/SafeFile.h
src/SafeFile.cpp