aMule: CSharedFileList Class Reference
CSharedFileList Class Reference
Public Member Functions
CSharedFileList (CKnownFileList *in_filelist)
void Reload ()
void SafeAddKFile (CKnownFile *toadd, bool bOnlyAdd=false)
void RemoveFile (CKnownFile *toremove)
CKnownFile * GetFileByID (const CMD4Hash &filehash)
short GetFilePriorityByID (const CMD4Hash &filehash)
const CKnownFile * GetFileByIndex (unsigned int index) const
size_t GetCount ()
size_t GetFileCount ()
void CopyFileList (std::vector< CKnownFile * > &out_list) const
void UpdateItem (CKnownFile *toupdate)
void GetSharedFilesByDirectory (const wxString &directory, CKnownFilePtrList &list)
void ClearED2KPublishInfo ()
void RepublishFile (CKnownFile *pFile)
void Process ()
void PublishNextTurn ()
bool RenameFile (CKnownFile *pFile, const CPath &newName)
wxString GetPublicSharedDirName (const CPath &dir)
const CPath * GetDirForPublicSharedDirName (const wxString &strSharedDir) const
bool IsShared (const CPath &path) const
void Publish ()
void AddKeywords (CKnownFile *pFile)
void RemoveKeywords (CKnownFile *pFile)
void ClearKadSourcePublishInfo ()
void CheckAICHHashes (const std::list< CAICHHash > &hashes)
Private Types
typedef std::list< CThreadTask * > TaskList
Private Member Functions
bool AddFile (CKnownFile *pFile)
unsigned AddFilesFromDirectory (const CPath &directory, TaskList &hashTasks)
void FindSharedFiles ()
void SendListToServer ()
Private Attributes
bool reloading
uint32 m_lastPublishED2K
bool m_lastPublishED2KFlag
CKnownFileList * filelist
CKnownFileMap m_Files_map
wxMutex list_mut
StringPathMap m_PublicSharedDirNames
CPublishKeywordList * m_keywords
unsigned int m_currFileSrc
unsigned int m_currFileNotes
unsigned int m_currFileKey
uint32 m_lastPublishKadSrc
uint32 m_lastPublishKadNotes
Member Function Documentation
void CSharedFileList::CheckAICHHashes (const std::list< CAICHHash > & hashes)
Checks for files which missing or wrong AICH hashes.
Those that are found are scheduled for ACIH hashing.
References CThreadScheduler::AddTask().
wxString CSharedFileList::GetPublicSharedDirName (const CPath & dir)
Returns the name of a folder visible to the public.
Parameters:
dir The full path to a shared directory.
Returns:
The name of the shared directory that will be visible to the public.
This function is used to hide sensitive data considering the directory structure of the client. The returned public name consists of only subdirectories that are shared. Example: /ed2k/shared/games/tetris -> "games/tetris" if /ed2k/shared are not marked as shared
References CPath::GetPrintable(), CPath::GetRaw(), and IsShared().
The documentation for this class was generated from the following files:
src/SharedFileList.h
src/SharedFileList.cpp