aMule: PrefsUnifiedDlg Class Reference
PrefsUnifiedDlg Class Reference
This class represents a dialog used to display preferences.
#include <PrefsUnifiedDlg.h>
Public Member Functions
PrefsUnifiedDlg (wxWindow *parent)
bool TransferFromWindow ()
bool TransferToWindow ()
Protected Member Functions
bool CfgChanged (int id)
Cfg_Base * GetCfg (int id)
void EnableServerTab (bool enable)
void OnOk (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnClose (wxCloseEvent &event)
void OnButtonBrowseApplication (wxCommandEvent &event)
void OnButtonDir (wxCommandEvent &event)
void OnButtonEditAddr (wxCommandEvent &event)
void OnButtonColorChange (wxCommandEvent &event)
void OnButtonIPFilterReload (wxCommandEvent &event)
void OnButtonIPFilterUpdate (wxCommandEvent &event)
void OnColorCategorySelected (wxCommandEvent &event)
void OnCheckBoxChange (wxCommandEvent &event)
void OnPrefsPageChange (wxListEvent &event)
void OnToolTipDelayChange (wxSpinEvent &event)
void OnScrollBarChange (wxScrollEvent &event)
void OnRateLimitChanged (wxSpinEvent &event)
void OnTCPClientPortChange (wxSpinEvent &event)
void OnUserEventSelected (wxListEvent &event)
void OnLanguageChoice (wxCommandEvent &event)
void CreateEventPanels (const int idx, const wxString &vars, wxWindow *parent)
void OnInitDialog (wxInitDialogEvent &evt)
Protected Attributes
CDirectoryTreeCtrl * m_ShareSelector
wxChoice * m_choiceColor
wxButton * m_buttonColor
wxPanel * m_CurrentPanel
int m_IndexServerTab
bool m_ServerTabVisible
wxPanel * m_ServerWidget
wxListCtrl * m_PrefsIcons
Detailed Description
This class represents a dialog used to display preferences.
Constructor & Destructor Documentation
PrefsUnifiedDlg::PrefsUnifiedDlg (wxWindow * parent)
Constructor.
Parameters:
parent The parent window.
This constructor is a much more simple version of the wxDialog one, which only needs to know the parent of the dialog. Please note that it is private so that we can ensure that only one dialog has been created at one time.
References CUserEvents::GetCount(), CLogger::GetDebugCategory(), CLogger::GetDebugCategoryCount(), CUserEvents::GetDisplayName(), CDebugCategory::GetName(), m_buttonColor, m_choiceColor, m_CurrentPanel, PrefsPage::m_function, m_IndexServerTab, and m_ShareSelector.
The documentation for this class was generated from the following files:
src/PrefsUnifiedDlg.h
src/PrefsUnifiedDlg.cpp