aMule: CamuleRemoteGuiApp Class Reference
CamuleRemoteGuiApp Class Reference
Public Member Functions
void Startup ()
bool ShowConnectionDialog ()
bool CopyTextToClipboard (wxString strText)
virtual int ShowAlert (wxString msg, wxString title, int flags)
void ShutDown (wxCloseEvent &evt)
bool AddServer (CServer *srv, bool fromUser=false)
uint32 GetPublicIP ()
wxString GetLog (bool reset=false)
wxString GetServerLog (bool reset=false)
void AddServerMessageLine (wxString &msg)
void AddRemoteLogLine (const wxString &line)
void SetOSFiles (wxString)
bool IsConnected () const
bool IsFirewalled () const
bool IsConnectedED2K () const
bool IsConnectedKad () const
bool IsFirewalledKad () const
bool IsKadRunning () const
bool IsFirewalledKadUDP () const
bool IsKadRunningInLanMode () const
uint32 GetKadUsers () const
uint32 GetKadFiles () const
uint32 GetKadIndexedSources () const
uint32 GetKadIndexedKeywords () const
uint32 GetKadIndexedNotes () const
uint32 GetKadIndexedLoad () const
uint32 GetKadIPAdress () const
uint8 GetBuddyStatus () const
uint32 GetBuddyIP () const
uint32 GetBuddyPort () const
void StartKad ()
void StopKad ()
void BootstrapKad (uint32 ip, uint16 port)
void UpdateNotesDat (const wxString &str)
void DisconnectED2K ()
bool CryptoAvailable () const
uint32 GetED2KID () const
uint32 GetID () const
void ShowUserCount ()
Public Attributes
class CRemoteConnect * m_connect
CEConnectDlg * dialog
CPreferencesRem * glob_prefs
CServerConnectRem * serverconnect
CServerListRem * serverlist
CDownQueueRem * downloadqueue
CSharedFilesRem * sharedfiles
CKnownFilesRem * knownfiles
CUpDownClientListRem * clientlist
CIPFilterRem * ipfilter
CSearchListRem * searchlist
CFriendListRem * friendlist
CListenSocketRem * listensocket
CStatTreeRem * stattree
CStatistics * m_statistics
uint8 m_ConnState
uint32 m_clientID
wxLocale m_locale
CKnownFile * m_allUploadingKnownFile
Private Member Functions
virtual int InitGui (bool geometry_enable, wxString &geometry_string)
bool OnInit ()
int OnExit ()
void OnPollTimer (wxTimerEvent &evt)
void OnECConnection (wxEvent &event)
void OnECInitDone (wxEvent &event)
void OnNotifyEvent (CMuleGUIEvent &evt)
void OnFinishedHTTPDownload (CMuleInternalEvent &event)
Private Attributes
wxTimer * poll_timer
CStatsUpdaterRem m_stats_updater
Member Function Documentation
void CamuleRemoteGuiApp::BootstrapKad (uint32 ip, uint16 port)
Bootstraps kad from the specified IP (must be in hostorder).
References CECTag::AddTag(), and CRemoteConnect::SendPacket().
void CamuleRemoteGuiApp::UpdateNotesDat (const wxString & str)
Updates the nodes.dat file from the specified url.
References CECTag::AddTag(), and CRemoteConnect::SendPacket().
The documentation for this class was generated from the following files:
src/amule-remote-gui.h
src/amule-remote-gui.cpp