aMule: CSearchList Class Reference
CSearchList Class Reference
Classes
struct CSearchParams
Structure used to pass search-parameters.
Public Member Functions
CSearchList ()
~CSearchList ()
wxString StartNewSearch (uint32 *searchID, SearchType type, const CSearchParams &params)
void StopSearch (bool globalOnly=false)
uint32 GetSearchProgress () const
void LocalSearchEnd ()
const CSearchResultList & GetSearchResults (long searchID) const
void RemoveResults (long searchID)
void AddFileToDownloadByHash (const CMD4Hash &hash, uint8 category=0)
void ProcessSharedFileList (const byte *packet, uint32 size, CUpDownClient *sender, bool *moreResultsAvailable, const wxString &directory)
void ProcessSearchAnswer (const uint8_t *packet, uint32_t size, bool optUTF8, uint32_t serverIP, uint16_t serverPort)
void ProcessUDPSearchAnswer (const CMemFile &packet, bool optUTF8, uint32 serverIP, uint16 serverPort)
void KademliaSearchKeyword (uint32_t searchID, const Kademlia::CUInt128 *fileID, const wxString &name, uint64_t size, const wxString &type, uint32_t kadPublishInfo, const TagPtrList &taglist)
void UpdateSearchFileByHash (const CMD4Hash &hash)
void SetKadSearchFinished ()
Private Types
typedef std::auto_ptr< CMemFile > CMemFilePtr
typedef std::map< long,
CSearchResultList > ResultMap
Private Member Functions
void OnGlobalSearchTimer (CTimerEvent &evt)
bool AddToList (CSearchFile *toadd, bool clientResponse=false)
CMemFilePtr CreateSearchData (const CSearchParams &params, SearchType type, bool supports64bit, bool &packetUsing64bit)
Private Attributes
CTimer m_searchTimer
SearchType m_searchType
bool m_searchInProgress
long m_currentSearch
CPacket * m_searchPacket
bool m_64bitSearchPacket
bool m_KadSearchFinished
CQueueObserver< CServer * > m_serverQueue
ResultMap m_results
wxString m_resultType
Constructor & Destructor Documentation
CSearchList::CSearchList ()
Constructor.
CSearchList::~CSearchList ()
Frees any remaining search-results.
References m_results, RemoveResults(), and StopSearch().
Member Function Documentation
void CSearchList::AddFileToDownloadByHash (const CMD4Hash & hash, uint8 category = 0)
Finds the search-result (by hash) and downloads it in the given category.
References m_results.
bool CSearchList::AddToList (CSearchFile * toadd, bool clientResponse = false) [private]
Adds the specified file to the current search's results.
Parameters:
toadd The result to add.
clientResponse Is the result sent by a client (shared-files list).
Returns:
True if the results were added, false otherwise.
Note that this function takes ownership of the CSearchFile object, regardless of whenever or not it was actually added to the results list.
References CSearchFile::AddChild(), CSearchFile::GetSearchID(), m_results, and m_resultType.
Referenced by KademliaSearchKeyword(), ProcessSearchAnswer(), ProcessSharedFileList(), and ProcessUDPSearchAnswer().
CSearchList::CMemFilePtr CSearchList::CreateSearchData (const CSearchParams & params, SearchType type, bool supports64bit, bool & packetUsing64bit) [private]
Create a basic search-packet for the given search-type.
References CSearchList::CSearchParams::availability, CSearchList::CSearchParams::extension, CSearchList::CSearchParams::maxSize, CSearchList::CSearchParams::minSize, CSearchList::CSearchParams::searchString, and CSearchList::CSearchParams::typeText.
Referenced by StartNewSearch().
uint32 CSearchList::GetSearchProgress () const
Returns the completion percentage of the current search.
References CQueueObserver< ValueType >::GetRemaining(), m_KadSearchFinished, m_searchInProgress, m_searchType, and m_serverQueue.
Referenced by OnGlobalSearchTimer().
const CSearchResultList & CSearchList::GetSearchResults (long searchID) const
Returns the list of results for the specified search.
If the search is not valid, an empty list is returned.
References m_results.
void CSearchList::KademliaSearchKeyword (uint32_t searchID, const Kademlia::CUInt128 * fileID, const wxString & name, uint64_t size, const wxString & type, uint32_t kadPublishInfo, const TagPtrList & taglist)
Adds a result in the form of a kad search-keyword to the specified result-list.
Parameters:
searchID The search to which this result belongs.
fileID The hash of the result-file.
name The filename of the result.
size The filesize of the result.
type The filetype of the result (TODO: Not used?)
kadPublishInfo The kademlia publish information of the result.
taglist List of additional tags associated with the search-result.
References AddToList(), CMemFile::GetPosition(), and CFileDataIO::Seek().
void CSearchList::LocalSearchEnd ()
This function is called once the local (ed2k) search has ended.
References m_searchInProgress, m_searchPacket, m_searchTimer, m_searchType, m_serverQueue, and CTimer::Start().
void CSearchList::OnGlobalSearchTimer (CTimerEvent & evt) [private]
Event-handler for global searches.
References CMemFile::GetLength(), CQueueObserver< ValueType >::GetNext(), CQueueObserver< ValueType >::GetRemaining(), GetSearchProgress(), CQueueObserver< ValueType >::IsActive(), m_64bitSearchPacket, m_searchPacket, m_serverQueue, and StopSearch().
void CSearchList::ProcessSearchAnswer (const uint8_t * packet, uint32_t size, bool optUTF8, uint32_t serverIP, uint16_t serverPort)
Processes a search-result sent via TCP from the local server.
All results are added.
Parameters:
packet The packet containing one or more search-results.
size the length of the packet.
optUTF8 Specifies if the server supports UTF8.
serverIP The IP of the server sending the results.
serverPort The Port of the server sending the results.
References AddToList(), and m_currentSearch.
void CSearchList::ProcessSharedFileList (const byte * packet, uint32 size, CUpDownClient * sender, bool * moreResultsAvailable, const wxString & directory)
Processes a list of shared files from a client.
Parameters:
packet The raw packet received from the client.
size the length of the packet.
sender The sender of the packet.
moreResultsAvailable Set to a value specifying if more results are available.
directory The directory containing the shared files.
References AddToList(), CMemFile::GetLength(), CMemFile::GetPosition(), and CFileDataIO::ReadUInt8().
void CSearchList::ProcessUDPSearchAnswer (const CMemFile & packet, bool optUTF8, uint32 serverIP, uint16 serverPort)
Processes a search-result sent via UDP.
Only one result is read from the packet.
Parameters:
packet The packet containing one or more search-results.
optUTF8 Specifies if the server supports UTF8.
serverIP The IP of the server sending the results.
serverPort The Port of the server sending the results.
References AddToList(), and m_currentSearch.
void CSearchList::RemoveResults (long searchID)
Removes all results for the specified search.
References m_results, and StopSearch().
Referenced by ~CSearchList().
wxString CSearchList::StartNewSearch (uint32 * searchID, SearchType type, const CSearchParams & params)
Starts a new search.
Parameters:
searchID The ID of the search, which may be modified.
type The type of search, see SearchType.
params The search parameters, see CSearchParams.
Returns:
An empty string on success, otherwise an error-message.
References CreateSearchData(), m_64bitSearchPacket, m_currentSearch, m_KadSearchFinished, m_resultType, m_searchInProgress, m_searchPacket, m_searchType, CSearchList::CSearchParams::searchString, StopSearch(), and CSearchList::CSearchParams::typeText.
void CSearchList::StopSearch (bool globalOnly = false)
Stops the current search (global or Kad), if any is in progress.
References m_currentSearch, m_searchInProgress, m_searchPacket, m_searchTimer, m_searchType, and CTimer::Stop().
Referenced by OnGlobalSearchTimer(), RemoveResults(), StartNewSearch(), and ~CSearchList().
Member Data Documentation
wxString CSearchList::m_resultType [private]
Contains the results type desired in the current search.
If not empty, results of different types are filtered.
Referenced by AddToList(), and StartNewSearch().
CQueueObserver<CServer*> CSearchList::m_serverQueue [private]
Queue of servers to ask when doing global searches.
TODO: Replace with 'cookie' system.
Referenced by GetSearchProgress(), LocalSearchEnd(), and OnGlobalSearchTimer().
The documentation for this class was generated from the following files:
src/SearchList.h
src/SearchList.cpp