aMule: Cfg_Path Class Reference
Cfg_Path Class Reference
Cfg class for CPath.
Public Member Functions
Cfg_Path (const wxString &keyname, CPath &value, const wxString &defaultVal=EmptyString)
virtual void LoadFromFile (wxConfigBase *cfg)
virtual void SaveToFile (wxConfigBase *cfg)
virtual bool TransferToWindow ()
virtual bool TransferFromWindow ()
Private Attributes
wxString m_temp_path
CPath & m_real_path
Detailed Description
Cfg class for CPath.
Constructor & Destructor Documentation
Cfg_Path::Cfg_Path (const wxString & keyname, CPath & value, const wxString & defaultVal = EmptyString) [inline]
Constructor.
Member Function Documentation
virtual void Cfg_Path::LoadFromFile (wxConfigBase * cfg) [inline, virtual]
See also:
Cfg_Str::LoadFromFile.
Reimplemented from Cfg_Str.
References CPath::FromUniv().
virtual void Cfg_Path::SaveToFile (wxConfigBase * cfg) [inline, virtual]
See also:
Cfg_Str::SaveToFile.
Reimplemented from Cfg_Str.
References CPath::ToUniv().
virtual bool Cfg_Path::TransferFromWindow () [inline, virtual]
See also:
Cfg_Tmpl::TransferFromWindow.
Reimplemented from Cfg_Tmpl< wxString >.
References Cfg_Tmpl< wxString >::TransferFromWindow().
virtual bool Cfg_Path::TransferToWindow () [inline, virtual]
See also:
Cfg_Tmpl::TransferToWindow.
Reimplemented from Cfg_Tmpl< wxString >.
References CPath::GetRaw().
The documentation for this class was generated from the following file:
src/Preferences.cpp