aMule: CClientList Class Reference
CClientList Class Reference
This class takes care of managing existing clients.
#include <ClientList.h>
Classes
struct IpAndTicks
Public Types
typedef std::map< uint32, uint32 > ClientMap
typedef std::deque< CClientRef > SourceList
typedef std::multimap< uint32,
CClientRef > IDMap
typedef std::pair< uint32,
CClientRef > IDMapPair
Public Member Functions
CClientList ()
~CClientList ()
void AddClient (CUpDownClient *toadd)
void RemoveClient (CUpDownClient *client)
void UpdateClientIP (CUpDownClient *client, uint32 newIP)
void UpdateClientID (CUpDownClient *client, uint32 newID)
void UpdateClientHash (CUpDownClient *client, const CMD4Hash &newHash)
uint32 GetClientCount () const
void DeleteAll ()
bool AttachToAlreadyKnown (CUpDownClient **client, CClientTCPSocket *sender)
CUpDownClient * FindClientByIP (uint32 clientip, uint16 port)
CUpDownClient * FindClientByIP (uint32 clientip)
CUpDownClient * FindClientByECID (uint32 ecid) const
void AddTrackClient (CUpDownClient *toadd)
uint16 GetClientsFromIP (uint32 dwIP)
bool ComparePriorUserhash (uint32 dwIP, uint16 nPort, void *pNewHash)
void AddBannedClient (uint32 dwIP)
bool IsBannedClient (uint32 dwIP)
void RemoveBannedClient (uint32 dwIP)
void Process ()
void FilterQueues ()
SourceList GetClientsByHash (const CMD4Hash &hash)
SourceList GetClientsByIP (unsigned long ip)
const IDMap & GetClientList ()
void AddDeadSource (const CUpDownClient *client)
bool IsDeadSource (const CUpDownClient *client)
bool SendChatMessage (uint64 client_id, const wxString &message)
void SetChatState (uint64 client_id, uint8 state)
uint8 GetBuddyStatus () const
CUpDownClient * GetBuddy ()
uint32 GetBuddyIP ()
uint16 GetBuddyPort ()
bool RequestTCP (Kademlia::CContact *contact, uint8_t connectOptions)
void RequestBuddy (Kademlia::CContact *contact, uint8_t connectOptions)
bool IncomingBuddy (Kademlia::CContact *contact, Kademlia::CUInt128 *buddyID)
void RemoveFromKadList (CUpDownClient *torem)
void AddToKadList (CUpDownClient *toadd)
bool DoRequestFirewallCheckUDP (const Kademlia::CContact &contact)
void AddKadFirewallRequest (uint32 ip)
bool IsKadFirewallCheckIP (uint32 ip) const
void AddDirectCallbackClient (CUpDownClient *toAdd)
void RemoveDirectCallback (CUpDownClient *toRemove)
void AddTrackCallbackRequests (uint32_t ip)
bool AllowCallbackRequest (uint32_t ip) const
Protected Member Functions
void CleanUpClientList ()
void ProcessDirectCallbackList ()
Private Types
typedef std::multimap
< CMD4Hash, CClientRef > HashMap
typedef std::pair< CMD4Hash,
CClientRef > HashMapPair
typedef std::list< IpAndTicks > IpAndTicksList
typedef CClientRefList DirectCallbackList
Private Member Functions
CUpDownClient * FindMatchingClient (CUpDownClient *client)
bool IsIPAlreadyKnown (uint32_t ip)
void RemoveIPFromList (CUpDownClient *client)
bool RemoveIDFromList (CUpDownClient *client)
void RemoveHashFromList (CUpDownClient *client)
Private Attributes
HashMap m_hashList
IDMap m_ipList
IDMap m_clientList
ClientMap m_bannedList
uint32 m_dwLastBannCleanUp
std::map< uint32,
CDeletedClient * > m_trackedClientsList
uint32 m_dwLastTrackedCleanUp
uint32 m_dwLastClientCleanUp
CDeadSourceList m_deadSources
CClientRefSet m_KadSources
CClientRef m_pBuddy
uint8 m_nBuddyStatus
IpAndTicksList m_firewallCheckRequests
DirectCallbackList m_currentDirectCallbacks
IpAndTicksList m_directCallbackRequests
Detailed Description
This class takes care of managing existing clients.
This class tracks a number of attributes related to existing and deleted clients. Among other things, it keeps track of existing, banned, dead and dying clients, as well as offers support for matching new client-instances against already exist clients to avoid duplicates.
Member Function Documentation
void CClientList::AddBannedClient (uint32 dwIP)
Bans an IP address for 2 hours.
Parameters:
dwIP The IP from which all clients will be banned.
References m_bannedList.
void CClientList::AddClient (CUpDownClient * toadd)
Adds a client to the global list of clients.
Parameters:
toadd The new client.
References m_clientList, m_hashList, and m_ipList.
Referenced by SendChatMessage().
void CClientList::AddDeadSource (const CUpDownClient * client)
Adds a source to the list of dead sources.
Parameters:
client The source to be recorded as dead.
References CDeadSourceList::AddDeadSource(), and m_deadSources.
void CClientList::AddTrackClient (CUpDownClient * toadd)
Adds a client to the list of tracked clients.
Parameters:
toadd The client to track.
This function is used to keep track of clients after they have been deleted and makes it possible to spot port or hash changes.
References m_trackedClientsList.
bool CClientList::AttachToAlreadyKnown (CUpDownClient ** client, CClientTCPSocket * sender)
Replaces a new client-instance with the an already existing client, if one such exist.
Parameters:
client A pointer to the pointer of the new instance.
sender The socket assosiated with the new instance.
Call this function when a new client-instance has been created. This function will then compare it against all existing clients and see if we already have an instance matching the new one. If that is the case, it will delete the new instance and set the pointer to the existing one.
References FindMatchingClient(), CUpDownClient::GetSocket(), CUpDownClient::IsConnected(), CUpDownClient::Safe_Delete(), and CUpDownClient::SetSocket().
bool CClientList::ComparePriorUserhash (uint32 dwIP, uint16 nPort, void * pNewHash)
Checks if a client has changed its user-hash.
Parameters:
dwIP The IP of the client.
nPort The port of the client.
pNewHash The userhash assosiated with the client.
References m_trackedClientsList.
void CClientList::FilterQueues ()
This function removes all clients filtered by the current IPFilter.
Call this function after changing the current IPFiler list, to ensure that no client-connections to illegal IPs exist. These would otherwise be allowed to exist, bypassing the IPFilter.
References m_ipList, and CUpDownClient::Safe_Delete().
CUpDownClient * CClientList::FindClientByECID (uint32 ecid) const
Finds a client with the specified ECID.
Parameters:
clientip The IP of the client to find.
References m_clientList.
CUpDownClient * CClientList::FindClientByIP (uint32 clientip)
Finds a client with the specified ip.
Parameters:
clientip The IP of the client to find.
Returns the first client found if there are several with same ip.
References m_ipList.
CUpDownClient * CClientList::FindClientByIP (uint32 clientip, uint16 port)
Finds a client with the specified ip and port.
Parameters:
clientip The IP of the client to find.
port The port used by the client.
References m_ipList.
Referenced by SendChatMessage(), and SetChatState().
CUpDownClient * CClientList::FindMatchingClient (CUpDownClient * client) [private]
Helperfunction which finds a client matching the specified client.
Parameters:
client The client to search for.
Returns:
The matching client or NULL.
This functions searches through the list of clients and finds the first match using the same checks as CUpDownClient::Compare, but without the overhead.
References m_clientList, m_hashList, and m_ipList.
Referenced by AttachToAlreadyKnown().
const CClientList::IDMap & CClientList::GetClientList ()
Returns a list of all clients.
Returns:
The complete list of clients.
References m_clientList.
CClientList::SourceList CClientList::GetClientsByHash (const CMD4Hash & hash)
Returns a list of clients with the specified user-hash.
Parameters:
hash The userhash to search for.
This function will return a list of clients with the specified userhash, provided that the hash is a valid non-empty userhash. Empty hashes will simply result in nothing being found.
References m_hashList.
CClientList::SourceList CClientList::GetClientsByIP (unsigned long ip)
Returns a list of clients with the specified IP.
Parameters:
ip The IP-address to search for.
This function will return a list of clients with the specified IP, provided that the IP is a non-zero value. A value of zero will not result in any results.
References m_ipList.
uint16 CClientList::GetClientsFromIP (uint32 dwIP)
Returns the number of tracked client.
Parameters:
dwIP The IP-adress which of the clients.
Returns:
The number of clients tracked at the specifed IP.
References m_trackedClientsList.
bool CClientList::IsBannedClient (uint32 dwIP)
Checks if a client has been banned.
Parameters:
dwIP The IP to check.
Returns:
True if the IP is banned, false otherwise.
References m_bannedList, and RemoveBannedClient().
bool CClientList::IsDeadSource (const CUpDownClient * client)
Checks if a source is recorded as being dead.
Parameters:
client The client to evaluate.
Returns:
True if dead, false otherwise.
Sources that are dead are not to be considered valid sources and should not be added to partfiles.
References CDeadSourceList::IsDeadSource(), and m_deadSources.
bool CClientList::IsIPAlreadyKnown (uint32_t ip) [private]
Check if we already know this IP.
This function is used to determine if the given IP address is already known.
Parameters:
ip The IP address to check.
References m_ipList.
void CClientList::Process ()
Main loop.
This function takes care of cleaning the various lists and deleting pending clients on the deletion-queue.
References CUpDownClient::IsConnected(), m_bannedList, m_dwLastBannCleanUp, m_dwLastTrackedCleanUp, m_trackedClientsList, and RemoveBannedClient().
void CClientList::RemoveBannedClient (uint32 dwIP)
Unbans an IP address, if it has been banned.
Parameters:
dwIP The IP address to unban.
References m_bannedList.
Referenced by IsBannedClient(), and Process().
void CClientList::RemoveClient (CUpDownClient * client)
Removes a client from the client lists.
Parameters:
client The client to be removed.
To be called from CUpDownClient::Safe_Delete only.
References RemoveHashFromList(), RemoveIDFromList(), and RemoveIPFromList().
bool CClientList::SendChatMessage (uint64 client_id, const wxString & message)
Sends a message to a client, identified by a GUI_ID.
Returns:
Success
References AddClient(), FindClientByIP(), and CUpDownClient::SendChatMessage().
void CClientList::UpdateClientHash (CUpDownClient * client, const CMD4Hash & newHash)
Updates the recorded hash of the specified client.
Parameters:
client The client to have its entry updated.
newHash The new user-hash.
This function is to be called before the client actually changes its user-hash, and will update the old entry with the new value. There will only be added an entry if the new hash is valid.
References CMD4Hash::IsEmpty(), m_hashList, and RemoveHashFromList().
void CClientList::UpdateClientID (CUpDownClient * client, uint32 newID)
Updates the recorded ID of the specified client.
Parameters:
client The client to have its entry updated.
newID The new ID of the client.
This function is to be called before the client actually changes its ID, and will update the old entry with the new value. Unlike the other two functions, this function will always ensure that there is an entry for the client, regardless of the value of newID.
References m_clientList, and RemoveIDFromList().
void CClientList::UpdateClientIP (CUpDownClient * client, uint32 newIP)
Updates the recorded IP of the specified client.
Parameters:
client The client to have its entry updated.
newIP The new IP adress of the client.
This function is to be called before the client actually changes its IP-address, and will update the old entry with the new value. There will only be added an entry if the new IP isn't zero.
References m_ipList, and RemoveIPFromList().
The documentation for this class was generated from the following files:
src/ClientList.h
src/ClientList.cpp