aMule: CDownloadQueue Class Reference
CDownloadQueue Class Reference
The download queue houses all active downloads.
#include <DownloadQueue.h>
Classes
struct Hostname_Entry
Structure used to store sources with dynamic hostnames.
Public Member Functions
CDownloadQueue ()
~CDownloadQueue ()
void LoadMetFiles (const CPath &path)
void Process ()
CPartFile * GetFileByID (const CMD4Hash &filehash) const
CPartFile * GetFileByIndex (unsigned int idx) const
bool IsFileExisting (const CMD4Hash &fileid) const
bool IsPartFile (const CKnownFile *file) const
void OnConnectionState (bool bConnected)
void AddSearchToDownload (CSearchFile *toadd, uint8 category)
void AddDownload (CPartFile *newfile, bool paused, uint8 category)
void RemoveFile (CPartFile *toremove, bool keepAsCompleted=false)
void SaveSourceSeeds ()
void LoadSourceSeeds ()
void CheckAndAddSource (CPartFile *sender, CUpDownClient *source)
void CheckAndAddKnownSource (CPartFile *sender, CUpDownClient *source)
bool RemoveSource (CUpDownClient *toremove, bool updatewindow=true, bool bDoStatsUpdate=true)
CUpDownClient * GetDownloadClientByIP_UDP (uint32 dwIP, uint16 nUDPPort) const
void SendLocalSrcRequest (CPartFile *sender)
void RemoveLocalServerRequest (CPartFile *pFile)
void ResetLocalServerRequests ()
void StartNextFile (CPartFile *oldfile)
void ResetCatParts (uint8 cat)
void SetCatPrio (uint8 cat, uint8 newprio)
void SetCatStatus (uint8 cat, int newstatus)
uint16 GetFileCount () const
void CopyFileList (std::vector< CPartFile * > &out_list, bool includeCompleted=false) const
uint16 GetDownloadingFileCount () const
uint16 GetPausedFileCount () const
void OnHostnameResolved (uint32 ip)
bool AddLink (const wxString &link, uint8 category=0)
bool AddED2KLink (const wxString &link, uint8 category=0)
bool AddED2KLink (const CED2KLink *link, uint8 category=0)
bool AddED2KLink (const CED2KFileLink *link, uint8 category=0)
bool AddED2KLink (const CED2KServerLink *link)
bool AddED2KLink (const CED2KServerListLink *link)
CServer * GetUDPServer () const
void SetUDPServer (CServer *server)
void StopUDPRequests ()
void KademliaSearchFile (uint32_t searchID, const Kademlia::CUInt128 *pcontactID, const Kademlia::CUInt128 *pkadID, uint8_t type, uint32_t ip, uint16_t tcp, uint16_t udp, uint32_t buddyip, uint16_t buddyport, uint8_t byCryptOptions)
CPartFile * GetFileByKadFileSearchID (uint32 id) const
bool DoKademliaFileRequest ()
void SetLastKademliaFileRequest ()
uint32 GetRareFileThreshold () const
uint32 GetCommonFileThreshold () const
void ClearCompleted (const ListOfUInts32 &ecids)
Private Types
typedef std::deque< CPartFile * > FileQueue
typedef std::list< CPartFile * > FileList
Private Member Functions
virtual void ObserverAdded (ObserverType *o)
void DoSortByPriority ()
void CheckDiskspace (const CPath &path)
void DoStopUDPRequests ()
void ProcessLocalRequests ()
bool SendNextUDPPacket ()
int GetMaxFilesPerUDPServerPacket () const
bool SendGlobGetSourcesUDPPacket (CMemFile &data)
void AddToResolve (const CMD4Hash &fileid, const wxString &pszHostname, uint16 port, const wxString &hash, uint8 cryptoptions)
Private Attributes
wxMutex m_mutex
uint32 m_datarate
uint32 m_lastDiskCheck
uint32 m_lastudpsearchtime
uint32 m_lastsorttime
uint32 m_lastudpstattime
uint32 m_nLastED2KLinkCheck
uint8 m_cRequestsSentToServer
uint32 m_dwNextTCPSrcReq
uint8 m_udcounter
CServer * m_udpserver
std::deque< Hostname_Entry > m_toresolve
FileQueue m_filelist
FileList m_localServerReqQueue
FileList m_completedDownloads
CQueueObserver< CServer * > m_queueServers
CQueueObserver< CPartFile * > m_queueFiles
uint32 lastkademliafilerequest
uint32 m_rareFileThreshold
uint32 m_commonFileThreshold
Detailed Description
The download queue houses all active downloads.
This class should be thread-safe.
Member Function Documentation
void CDownloadQueue::AddDownload (CPartFile * newfile, bool paused, uint8 category)
Adds an existing partfile to the queue.
Parameters:
newfile The file to add.
paused If the file should be stopped when added.
category The category to assign to the file.
References DoSortByPriority(), GetFileCount(), CQueueEvent< ValueType >::INSERTED, IsFileExisting(), m_mutex, and CObservable< CQueueEvent< CPartFile * > >::NotifyObservers().
Referenced by AddSearchToDownload().
void CDownloadQueue::AddSearchToDownload (CSearchFile * toadd, uint8 category)
Starts a new download based on the specified search-result.
Parameters:
toadd The search-result to add.
category The category to assign to the new download.
The download will only be started if no identical files are either being downloaded or shared currently.
References AddDownload(), IsFileExisting(), CMemFile::Reset(), and CFileDataIO::WriteUInt8().
void CDownloadQueue::CheckAndAddKnownSource (CPartFile * sender, CUpDownClient * source)
This function adds already known source to the specified file.
Parameters:
sender The owner fo the new source.
source The client in question.
This function acts like CheckAndAddSource, with the exception that no checks are made to see if the client is a duplicate. It is assumed that it is in fact a valid client.
References CPartFile::IsDeadSource().
void CDownloadQueue::CheckAndAddSource (CPartFile * sender, CUpDownClient * source)
Adds a potiential new client to the specified file.
Parameters:
sender The owner of the new source.
source The client in question, might be deleted!
This function will check the new client against the already existing clients. The source will then be queued as is appropriate, or deleted if it is duplicate of an existing client.
References CPartFile::IsDeadSource(), and CUpDownClient::Safe_Delete().
Referenced by KademliaSearchFile().
void CDownloadQueue::CheckDiskspace (const CPath & path) [private]
Checks that there is enough free spaces for temp-files at that specified path.
References CPath::GetFreeSpaceAt(), and CUserEvents::ProcessEvent().
Referenced by LoadMetFiles(), and Process().
CUpDownClient * CDownloadQueue::GetDownloadClientByIP_UDP (uint32 dwIP, uint16 nUDPPort) const
Finds the queued client by IP and UDP-port, by looking at file-sources.
Parameters:
dwIP The IP-address of the client.
nUDPPort The UDP-port of the client.
Returns:
The matching client or NULL if none was found.
References m_mutex.
CPartFile * CDownloadQueue::GetFileByID (const CMD4Hash & filehash) const
Returns a pointer to the file with the specified hash, or NULL.
Parameters:
filehash The hash to search for.
Returns:
The corresponding file or NULL.
References m_completedDownloads, and m_mutex.
Referenced by IsFileExisting(), and OnHostnameResolved().
CPartFile * CDownloadQueue::GetFileByIndex (unsigned int idx) const
Returns the file at the specified position in the file-list, or NULL if invalid.
Parameters:
A valid position in the file-list.
Returns:
A valid pointer or NULL if the index was invalid.
References m_mutex.
Referenced by LoadSourceSeeds(), RemoveSource(), SaveSourceSeeds(), and SetCatPrio().
void CDownloadQueue::LoadMetFiles (const CPath & path)
Loads met-files from the specified directory.
References CheckDiskspace(), DoSortByPriority(), GetFileCount(), CPath::GetFullName(), CPath::GetPrintable(), CQueueEvent< ValueType >::INSERTED, IsFileExisting(), CPath::IsOk(), CPath::JoinPaths(), m_mutex, and CObservable< CQueueEvent< CPartFile * > >::NotifyObservers().
void CDownloadQueue::RemoveFile (CPartFile * toremove, bool keepAsCompleted = false)
Removes the specified file from the queue.
Parameters:
toremove A pointer to the file object to be removed.
keepAsCompleted If true add the removed file to the list of completed files.
References m_completedDownloads, m_mutex, CObservable< CQueueEvent< CPartFile * > >::NotifyObservers(), CQueueEvent< ValueType >::REMOVED, and RemoveLocalServerRequest().
bool CDownloadQueue::RemoveSource (CUpDownClient * toremove, bool updatewindow = true, bool bDoStatsUpdate = true)
Removes the specified client completly.
Parameters:
toremove The client to be removed.
updatewindow NOT USED!
bDoStatsUdpate Specifies if the affected files should update their statistics.
Returns:
True if the sources was found and removed.
This function will remove the specified source from both normal source lists, A4AF lists and the downloadqueue-widget. The requestfile of the source is also reset.
References GetFileByIndex(), and GetFileCount().
void CDownloadQueue::StartNextFile (CPartFile * oldfile)
Starts the next paused file on the queue, going after priority.
Also checks for categories if enabled on preferences.
References SFindBestPF::m_category, m_mutex, and SFindBestPF::m_result.
The documentation for this class was generated from the following files:
src/DownloadQueue.h
src/DownloadQueue.cpp