aMule: CTextFile Class Reference
CTextFile Class Reference
Text file class.
#include <TextFile.h>
Public Types
enum EOpenMode { read, write }
Public Member Functions
~CTextFile ()
bool IsOpened () const
bool Eof () const
bool Close ()
wxString GetNextLine (EReadTextFile flags=txtReadAll, const wxMBConv &conv=wxConvLibc, bool *result=NULL)
bool WriteLine (const wxString &line, const wxMBConv &conv=wxConvLibc)
wxArrayString ReadLines (EReadTextFile flags=txtReadDefault, const wxMBConv &conv=wxConvLibc)
bool WriteLines (const wxArrayString &lines, const wxMBConv &conv=wxConvLibc)
bool Open (const wxString &path, EOpenMode mode)
bool Open (const CPath &path, EOpenMode mode)
Private Attributes
wxFFile m_file
EOpenMode m_mode
Detailed Description
Text file class.
This class is a wrapper around wxFFile, letting an text file be read or written line-by-line. The class provides transparent and automatic EOL-style handling.
Note that it is not possible to seek in a CTextFile, only sequential reading or writing is possible. Also note that the maximum length of a line is fixed (see CTextFile::GetNextLine), however this shouldn't be a problem, given the uses of this class.
Member Enumeration Documentation
enum CTextFile::EOpenMode
Enumerator:
read
Opens the file for reading, if it exists.
write
Opens the file for writing, overwriting old contents.
Constructor & Destructor Documentation
CTextFile::~CTextFile ()
Destructor.
Closes the file if still open.
Member Function Documentation
bool CTextFile::Close ()
Closes the file, returning true on success.
References m_file.
bool CTextFile::Eof () const
Returns true if GetNextLine has reached the end of the file.
References m_file.
Referenced by ReadLines().
wxString CTextFile::GetNextLine (EReadTextFile flags = txtReadAll, const wxMBConv & conv = wxConvLibc, bool * result = NULL)
Returns the next line of a readable file.
Parameters:
conv The converter used to convert from multibyte to widechar.
Note that GetNextLine will return an empty string if the file has reached EOF, or if the file is closed, or not readable. However, empty lines in the file will also be returned unless otherwise specified, so this cannot be used to test for EOF. Instead, use the function Eof().
References m_file, m_mode, and read.
Referenced by ReadLines().
bool CTextFile::IsOpened () const
Returns true if the file is opened.
References m_file.
bool CTextFile::Open (const wxString & path, EOpenMode mode)
Opens the specified file, returning true on success.
Referenced by CPreferences::CPreferences().
wxArrayString CTextFile::ReadLines (EReadTextFile flags = txtReadDefault, const wxMBConv & conv = wxConvLibc)
Reads and returns the contents of a text-file, using the specifed criteria and converter.
References Eof(), and GetNextLine().
Referenced by CPreferences::CPreferences().
bool CTextFile::WriteLine (const wxString & line, const wxMBConv & conv = wxConvLibc)
Writes the line to a writable file, returning true on success.
Parameters:
conv The converter used to convert from widechar to multibyte.
References m_file, m_mode, and write.
Referenced by WriteLines().
bool CTextFile::WriteLines (const wxArrayString & lines, const wxMBConv & conv = wxConvLibc)
Writes the lines to the file, using the given converter, returning true if no errors occured.
References WriteLine().
The documentation for this class was generated from the following files:
src/libs/common/TextFile.h
src/libs/common/TextFile.cpp