aMule: CFile Class Reference
CFile Class Reference
This class is a modified version of the wxFile class.
#include <CFile.h>
Public Types
enum { fd_invalid = -1, fd_stdin, fd_stdout, fd_stderr }
enum OpenMode {
read, write, read_write, write_append,
write_excl, write_safe
}
Public Member Functions
CFile ()
CFile (const CPath &path, OpenMode mode=read)
CFile (const wxString &path, OpenMode mode=read)
virtual ~CFile ()
bool Open (const CPath &path, OpenMode mode=read, int accessMode=wxS_DEFAULT)
bool Open (const wxString &path, OpenMode mode=read, int accessMode=wxS_DEFAULT)
void Reopen (OpenMode mode)
bool Create (const CPath &path, bool overwrite=false, int accessMode=wxS_DEFAULT)
bool Create (const wxString &path, bool overwrite=false, int accessMode=wxS_DEFAULT)
bool Close ()
int fd () const
bool Flush ()
virtual uint64 GetLength () const
bool SetLength (uint64 newLength)
virtual uint64 GetPosition () const
virtual uint64 GetAvailable () const
const CPath & GetFilePath () const
bool IsOpened () const
Protected Member Functions
virtual sint64 doRead (void *buffer, size_t count) const
virtual sint64 doWrite (const void *buffer, size_t count)
virtual sint64 doSeek (sint64 offset) const
Private Member Functions
CFile (const CFile &)
CFile & operator= (const CFile &)
Private Attributes
int m_fd
CPath m_filePath
bool m_safeWrite
Detailed Description
This class is a modified version of the wxFile class.
In addition to implementing the CFileDataIO interface, it offers improved support for UTF8 filenames and 64b file-IO on both windows and unix-like systems.
See also:
wxFile
Member Enumeration Documentation
enum CFile::OpenMode
See also:
wxFile::OpenMode
Constructor & Destructor Documentation
CFile::CFile (const CPath & path, OpenMode mode = read)
Constructor, calls Open on the specified file.
To check if the file was successfully opened, a call to IsOpened() is required.
References Open().
Member Function Documentation
bool CFile::Close ()
Closes the file.
Note that calling Close on an closed file is an illegal operation.
References IsOpened(), m_fd, m_filePath, m_safeWrite, CPath::RemoveExt(), and CPath::RenameFile().
Referenced by CFileAutoClose::Close(), CAllocateFileTask::Entry(), CAICHSyncTask::Entry(), Open(), CFileAutoClose::Release(), and ~CFile().
bool CFile::Create (const CPath & path, bool overwrite = false, int accessMode = wxS_DEFAULT)
Calling Create is equivilant of calling open with OpenMode 'write'.
Parameters:
overwrite Specifies if the target file should be overwritten, in case that it already exists.
See also:
CFile::Open
References CPath::FileExists(), and Open().
Referenced by CFileAutoClose::Create().
sint64 CFile::doRead (void * buffer, size_t count) const [protected, virtual]
See also:
CFileDataIO::doRead
Implements CFileDataIO.
References CFileDataIO::Eof(), IsOpened(), and m_fd.
sint64 CFile::doSeek (sint64 offset) const [protected, virtual]
See also:
CFileDataIO::doSeek
Implements CFileDataIO.
References IsOpened(), and m_fd.
sint64 CFile::doWrite (const void * buffer, size_t count) [protected, virtual]
See also:
CFileDataIO::doWrite
Implements CFileDataIO.
References IsOpened(), and m_fd.
int CFile::fd () const
Returns the file descriptior assosiated with the file.
Note that direct manipulation of the descriptor should be avoided! That's what this class is for.
References m_fd.
Referenced by CAllocateFileTask::Entry(), and CFileAutoClose::fd().
bool CFile::Flush ()
Flushes data not yet written.
Note that calling Flush on an closed file is an illegal operation.
References IsOpened(), m_fd, and m_filePath.
Referenced by CAICHSyncTask::ConvertToKnown2ToKnown264().
uint64 CFile::GetAvailable () const [virtual]
Returns the current available bytes to read on the file before EOF.
References GetLength(), and GetPosition().
uint64 CFile::GetLength () const [virtual]
See also:
CSafeFileIO::GetLength
Note that calling GetLength on a closed file is an illegal operation.
Implements CFileDataIO.
References IsOpened(), and m_fd.
Referenced by CAICHSyncTask::ConvertToKnown2ToKnown264(), CAICHSyncTask::Entry(), GetAvailable(), CFileAutoClose::GetLength(), and CFileAutoClose::Release().
uint64 CFile::GetPosition () const [virtual]
See also:
CSafeFileIO::GetPosition
Note that calling GetPosition on a closed file is an illegal operation.
Implements CFileDataIO.
References IsOpened(), and m_fd.
Referenced by CAICHSyncTask::ConvertToKnown2ToKnown264(), CAICHSyncTask::Entry(), and GetAvailable().
bool CFile::Open (const CPath & path, OpenMode mode = read, int accessMode = wxS_DEFAULT)
Opens a file.
Parameters:
path The full or relative path to the file.
mode The opening mode.
accessMode The permissions in case a new file is created.
Returns:
True if the file was opened, false otherwise.
Calling Open with the openmodes 'write' or 'write_append' will create the specified file if it does not already exist.
Calling Open with the openmode 'write_safe' will append ".new" to the file name and otherwise work like 'write'. On close it will be renamed to the original name. Close() has to be called manually - destruct won't rename the file!
If an accessMode is not explicitly specified, the accessmode specified via CPreferences::GetFilePermissions will be used.
References CPath::AppendExt(), Close(), CPath::FileExists(), CPath::GetRaw(), CPath::IsOk(), IsOpened(), m_fd, m_filePath, and m_safeWrite.
Referenced by CFile(), CAICHSyncTask::ConvertToKnown2ToKnown264(), CPreferences::CPreferences(), Create(), CAllocateFileTask::Entry(), CAICHSyncTask::Entry(), CFileAutoClose::Open(), and Reopen().
void CFile::Reopen (OpenMode mode)
Reopens a file which was opened and closed before.
Parameters:
mode The opening mode.
The filename used for last open is used again. No return value - function throws on failure.
References m_filePath, and Open().
Referenced by CAICHSyncTask::Entry(), and CFileAutoClose::Reopen().
The documentation for this class was generated from the following files:
src/CFile.h
src/CFile.cpp