aMule: Cfg_Base Class Reference
Cfg_Base Class Reference
Base-class for automatically loading and saving of preferences.
#include <Preferences.h>
Public Member Functions
Cfg_Base (const wxString &keyname)
virtual ~Cfg_Base ()
virtual void LoadFromFile (wxConfigBase *cfg)=0
virtual void SaveToFile (wxConfigBase *cfg)=0
virtual bool TransferFromWindow ()
virtual bool TransferToWindow ()
virtual bool ConnectToWidget (int id, wxWindow *parent=NULL)
virtual const wxString & GetKey ()
virtual bool HasChanged ()
Protected Member Functions
virtual void SetChanged (bool changed)
Private Attributes
wxString m_key
bool m_changed
Detailed Description
Base-class for automatically loading and saving of preferences.
The purpose of this class is to perform two tasks: 1) To load and save a variable using wxConfig 2) If nescecarry, to syncronize it with a widget
This pure-virtual class servers as the base of all the Cfg types defined below, and exposes the entire interface.
Please note that for reasons of simplicity these classes dont provide direct access to the variables they maintain, as there is no real need for this.
To create a sub-class you need only provide the Load/Save functionality, as it is given that not all variables have a widget assosiated.
Constructor & Destructor Documentation
Cfg_Base::Cfg_Base (const wxString & keyname) [inline]
Constructor.
Parameters:
keyname This is the keyname under which the variable is to be saved.
Member Function Documentation
virtual bool Cfg_Base::ConnectToWidget (int id, wxWindow * parent = NULL) [inline, virtual]
Connects a widget with the specified ID to the Cfg object.
Parameters:
id The ID of the widget.
parent A pointer to the widgets parent, to speed up searches.
Returns:
True on success, false otherwise.
This function only makes sense for Cfg-classes that have the capability to interact with a widget, see Cfg_Tmpl::ConnectToWidget().
Reimplemented in Cfg_Tmpl< TYPE >, Cfg_Tmpl< int >, Cfg_Tmpl< wxString >, and Cfg_Tmpl< bool >.
virtual const wxString& Cfg_Base::GetKey () [inline, virtual]
Gets the key assosiated with Cfg object.
Returns:
The config-key of this object.
References m_key.
Referenced by Cfg_Colour::LoadFromFile(), Cfg_Bool::LoadFromFile(), Cfg_Int< int >::LoadFromFile(), Cfg_Str::LoadFromFile(), Cfg_Colour::SaveToFile(), Cfg_Bool::SaveToFile(), Cfg_Int< int >::SaveToFile(), Cfg_Str::SaveToFile(), and Cfg_Skin::TransferToWindow().
virtual bool Cfg_Base::HasChanged () [inline, virtual]
Specifies if the variable has changed since the TransferFromWindow() call.
Returns:
True if the variable has changed, false otherwise.
References m_changed.
Referenced by PrefsUnifiedDlg::CfgChanged(), and Cfg_Str_Encrypted::TransferFromWindow().
virtual void Cfg_Base::SetChanged (bool changed) [inline, protected, virtual]
Sets the changed status.
Parameters:
changed The new status.
References m_changed.
Referenced by Cfg_Tmpl< bool >::TransferFromWindow().
virtual bool Cfg_Base::TransferFromWindow () [inline, virtual]
Syncs the variable with the contents of the widget.
Returns:
True of success, false otherwise.
Reimplemented in Cfg_Tmpl< TYPE >, Cfg_Str_Encrypted, Cfg_Path, Cfg_Int< TYPE >, Cfg_Lang, Cfg_Skin, Cfg_Tmpl< int >, Cfg_Tmpl< wxString >, Cfg_Tmpl< bool >, and Cfg_Int< int >.
virtual bool Cfg_Base::TransferToWindow () [inline, virtual]
Syncs the widget with the contents of the variable.
Returns:
True of success, false otherwise.
Reimplemented in Cfg_Tmpl< TYPE >, Cfg_Path, Cfg_Int< TYPE >, Cfg_Lang, Cfg_Skin, Cfg_Tmpl< int >, Cfg_Tmpl< wxString >, Cfg_Tmpl< bool >, and Cfg_Int< int >.
The documentation for this class was generated from the following file:
src/Preferences.h