aMule: CMuleThread Class Reference
CMuleThread Class Reference
Public Member Functions
CMuleThread (wxThreadKind kind=wxTHREAD_DETACHED)
void Stop ()
virtual bool TestDestroy ()
Private Attributes
bool m_stop
Constructor & Destructor Documentation
CMuleThread::CMuleThread (wxThreadKind kind = wxTHREAD_DETACHED) [inline]
See also:
wxThread::wxThread
Member Function Documentation
void CMuleThread::Stop () [inline]
Stops the thread.
For detached threads, this function is equivalent to Delete, but is also useable for joinable threads, where Delete should not be used, due to crashes experienced in that case. In the case of joinable threads, Wait is called rather than Delete.
See also:
wxThread::Delete
References m_stop.
Referenced by CThreadScheduler::CreateSchedulerThread(), CTimer::Start(), and CTimer::Stop().
The documentation for this class was generated from the following file:
src/MuleThread.h