aMule: CSearchListCtrl Class Reference
CSearchListCtrl Class Reference
This class is used to display search results.
#include <SearchListCtrl.h>
Public Member Functions
CSearchListCtrl (wxWindow *parent, wxWindowID winid=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxLC_ICON, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxT("mulelistctrl"))
virtual ~CSearchListCtrl ()
void AddResult (CSearchFile *toshow)
void RemoveResult (CSearchFile *toshow)
void UpdateResult (CSearchFile *toupdate)
void ShowResults (long ResultsId)
void UpdateItemColor (long index)
wxUIntPtr GetSearchId ()
void SetFilter (const wxString &regExp, bool invert, bool filterKnown)
void EnableFiltering (bool enabled)
size_t GetHiddenItemCount () const
void DownloadSelected (int category=-1)
Static Public Member Functions
static wxString DetermineStatusPrintable (CSearchFile *toshow)
Protected Types
typedef std::list< CSearchFile * > ResultList
Protected Member Functions
wxString GetOldColumnOrder () const
void SetSorting (unsigned column, unsigned order)
bool IsFiltered (const CSearchFile *file)
virtual bool AltSortAllowed (unsigned column) const
virtual wxString GetTTSText (unsigned item) const
void OnDrawItem (int item, wxDC *dc, const wxRect &rect, const wxRect &rectHL, bool highlighted)
void ShowChildren (CSearchFile *file, bool show)
void OnRightClick (wxListEvent &event)
void OnItemActivated (wxListEvent &event)
void OnColumnLClick (wxListEvent &event)
void OnColumnResize (wxListEvent &event)
void OnPopupGetUrl (wxCommandEvent &event)
void OnRazorStatsCheck (wxCommandEvent &event)
void OnRelatedSearch (wxCommandEvent &event)
void OnMarkAsKnown (wxCommandEvent &event)
void OnPopupDownload (wxCommandEvent &event)
Static Protected Member Functions
static int wxCALLBACK SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData)
static void SyncLists (CSearchListCtrl *src, CSearchListCtrl *dst)
static void SyncOtherLists (CSearchListCtrl *src)
Protected Attributes
ResultList m_filteredOut
wxRegEx m_filter
wxString m_filterText
bool m_filterKnown
bool m_invert
bool m_filterEnabled
wxUIntPtr m_nResultsID
Static Protected Attributes
static std::list
< CSearchListCtrl * > s_lists
Detailed Description
This class is used to display search results.
Results on added to the list will be colored according to the number of sources and other parameters (see UpdateColor).
To display results, first use the ShowResults function, which will display all current results with the specified id and afterwards you can use the AddResult function to add new results or the UpdateResult function to update already present results. Please note that it is not possible to add results with the AddResult function before calling ShowResults.
Constructor & Destructor Documentation
CSearchListCtrl::CSearchListCtrl (wxWindow * parent, wxWindowID winid = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxLC_ICON, const wxValidator & validator = wxDefaultValidator, const wxString & name = wxT("mulelistctrl"))
Constructor.
See also:
CMuleListCtrl::CMuleListCtrl for documentation of parameters.
References CMuleListCtrl::InsertColumn(), CMuleListCtrl::LoadSettings(), m_nResultsID, s_lists, CMuleListCtrl::SetSortFunc(), CMuleListCtrl::SetTableName(), SortProc(), and SyncLists().
Member Function Documentation
void CSearchListCtrl::AddResult (CSearchFile * toshow)
Adds ths specified file to the list.
Parameters:
The new result to be shown.
Please note that no duplicates checking is done, so the pointer should point to a new file in order to avoid problems. Also note that the result will be inserted sorted according to current sort-type, so there is no need to resort the list after adding new items.
References CSearchFile::GetChildren(), CSearchFile::GetCompleteSourceCount(), CMuleListCtrl::GetInsertPos(), CSearchFile::GetParent(), CPath::GetPrintable(), CSearchFile::GetSearchID(), CSearchFile::GetSourceCount(), CSearchFile::HasChildren(), IsFiltered(), m_filteredOut, m_nResultsID, CSearchFile::ShowChildren(), and UpdateItemColor().
Referenced by CSearchDlg::AddResult(), EnableFiltering(), SetFilter(), ShowChildren(), and ShowResults().
bool CSearchListCtrl::AltSortAllowed (unsigned column) const [protected, virtual]
See also:
CMuleListCtrl::AltSortAllowed
Reimplemented from CMuleListCtrl.
void CSearchListCtrl::DownloadSelected (int category = -1)
Attempts to download all selected items, updating color-scheme as needed.
Parameters:
category The target category, or -1 to use the drop-down selection.
Referenced by OnItemActivated(), and OnPopupDownload().
wxUIntPtr CSearchListCtrl::GetSearchId ()
Returns the current Search Id.
Returns:
The Search Id of the displayed results (set through ShowResults()).
References m_nResultsID.
Referenced by CSearchDlg::KadSearchEnd().
wxString CSearchListCtrl::GetTTSText (unsigned item) const [protected, virtual]
See also:
CMuleListCtrl::GetTTSText
Reimplemented from CMuleListCtrl.
void CSearchListCtrl::OnColumnLClick (wxListEvent & event) [protected]
Event handler for left-clicks on the column headers.
This eventhandler takes care of sync'ing all the other lists with this one.
Reimplemented from CMuleListCtrl.
References SyncOtherLists().
void CSearchListCtrl::OnColumnResize (wxListEvent & event) [protected]
Event handler for resizing of the columns.
This eventhandler takes care of sync'ing all the other lists with this one.
References SyncOtherLists().
void CSearchListCtrl::SetFilter (const wxString & regExp, bool invert, bool filterKnown)
Sets the filter which decides which results should be shown.
Parameters:
regExp A regular expression targeting the filenames.
invert If true, invert the results of the filter-test.
filterKnown Should files that are queued or known be filtered out.
An invalid regExp will result in all results being displayed.
References AddResult(), IsFiltered(), m_filter, m_filteredOut, m_filterEnabled, m_filterKnown, m_filterText, and m_invert.
Referenced by CSearchDlg::CreateNewTab(), and EnableFiltering().
void CSearchListCtrl::SetSorting (unsigned column, unsigned order) [protected, virtual]
Set the sort column.
Parameters:
column The column with which the list should be sorted.
order The order in which to sort the column.
Note that attempting to sort a column in an unsupported order is an illegal operation.
Reimplemented from CMuleListCtrl.
References ShowChildren(), and CSearchFile::ShowChildren().
Referenced by SyncLists().
void CSearchListCtrl::ShowResults (long ResultsId)
Clears the list and inserts all results with the specified Id instead.
Parameters:
nResult The ID of the results or Zero to simply reset the list.
References AddResult(), and m_nResultsID.
Referenced by CSearchDlg::CreateNewTab().
int CSearchListCtrl::SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData) [static, protected]
Sorter function used by wxListCtrl::SortItems function.
See also:
CMuleListCtrl::SetSortFunc
wxListCtrl::SortItems
Reimplemented from CMuleListCtrl.
References CMuleListCtrl::COLUMN_MASK, CSearchFile::GetCompleteSourceCount(), CPath::GetExt(), CSearchFile::GetParent(), CSearchFile::GetSourceCount(), CMuleListCtrl::SORT_ALT, and CMuleListCtrl::SORT_DES.
Referenced by CSearchListCtrl().
void CSearchListCtrl::SyncLists (CSearchListCtrl * src, CSearchListCtrl * dst) [static, protected]
Helper function which syncs two lists.
Parameters:
src The source list.
dst The list to be synced with the source list.
This function syncronises the following settings of two lists:
Sort column
Sort direction
Column widths
If either sort column or direction is changed, then the dst list will be resorted. This function is used to ensure that all results list act as one, while still allowing individual selection.
References CMuleListCtrl::GetSortColumn(), CMuleListCtrl::GetSortOrder(), and SetSorting().
Referenced by CSearchListCtrl(), and SyncOtherLists().
void CSearchListCtrl::SyncOtherLists (CSearchListCtrl * src) [static, protected]
Helper function which syncs all other lists against the specified one.
Parameters:
src The list which all other lists should be synced against.
This function just calls SyncLists() on all lists in s_lists, using the src argument as the src argument of the SyncLists function.
References s_lists, and SyncLists().
Referenced by OnColumnLClick(), and OnColumnResize().
void CSearchListCtrl::UpdateItemColor (long index)
Updates the colors of item at the specified index.
Parameters:
index The zero-based index of the item.
This function sets the color of the item based on the following:
Downloading files are marked in red.
Known (shared/completed) files are marked in green.
New files are marked in blue depending on the number of sources.
Canceled files are marked in magenta.
References CSearchFile::GetDownloadStatus(), and CSearchFile::GetSourceCount().
Referenced by AddResult(), and UpdateResult().
void CSearchListCtrl::UpdateResult (CSearchFile * toupdate)
Updates the specified source.
Parameters:
The search result to be updated.
References CSearchFile::GetCompleteSourceCount(), CPath::GetPrintable(), CSearchFile::GetSourceCount(), CMuleListCtrl::IsItemSorted(), CMuleListCtrl::SortList(), and UpdateItemColor().
Referenced by CSearchDlg::UpdateResult().
The documentation for this class was generated from the following files:
src/SearchListCtrl.h
src/SearchListCtrl.cpp