aMule: ServersInfo Class Reference
ServersInfo Class Reference
Public Member Functions
ServersInfo (CamulewebApp *webApp)
virtual bool ReQuery ()
Static Public Attributes
static ServersInfo * m_This = 0
Member Function Documentation
bool ServersInfo::ReQuery () [virtual]
Re-query server: refresh all dataset
Implements ItemsContainer< ServerEntry >.
References CECTag::GetInt(), CECTag::GetIPv4Data(), and CECTag::GetTagByNameSafe().
The documentation for this class was generated from the following files:
src/webserver/src/WebServer.h
src/webserver/src/WebServer.cpp