aMule: CDownloadListCtrl Class Reference
CDownloadListCtrl Class Reference
This class is responsible for representing the download queue.
#include <DownloadListCtrl.h>
Public Member Functions
CDownloadListCtrl (wxWindow *parent, wxWindowID winid=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxLC_ICON, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxT("downloadlistctrl"))
virtual ~CDownloadListCtrl ()
void AddFile (CPartFile *file)
void RemoveFile (CPartFile *file)
void ShowFile (CPartFile *file, bool show)
void UpdateItem (const void *toupdate)
uint8 GetCategory () const
void ChangeCategory (int newCategory)
void ClearCompleted ()
void DoItemSelectionChanged ()
Protected Member Functions
wxString GetOldColumnOrder () const
Private Types
typedef std::multimap< const
void *, FileCtrlItem_Struct * > ListItems
typedef ListItems::value_type ListItemsPair
typedef std::pair
< ListItems::iterator,
ListItems::iterator > ListIteratorPair
Private Member Functions
void ShowFilesCount (int diff)
virtual wxString GetTTSText (unsigned item) const
virtual void OnDrawItem (int item, wxDC *dc, const wxRect &rect, const wxRect &rectHL, bool highlighted)
void DrawFileItem (wxDC *dc, int nColumn, const wxRect &rect, FileCtrlItem_Struct *item) const
void DrawFileStatusBar (const CPartFile *file, wxDC *dc, const wxRect &rect, bool bFlat) const
void OnCancelFile (wxCommandEvent &event)
void OnSetPriority (wxCommandEvent &event)
void OnSwapSources (wxCommandEvent &event)
void OnSetCategory (wxCommandEvent &event)
void OnSetStatus (wxCommandEvent &event)
void OnClearCompleted (wxCommandEvent &event)
void OnGetLink (wxCommandEvent &event)
void OnGetFeedback (wxCommandEvent &event)
void OnViewFileInfo (wxCommandEvent &event)
void OnViewFileComments (wxCommandEvent &event)
void OnPreviewFile (wxCommandEvent &event)
void OnItemActivated (wxListEvent &event)
void OnMouseRightClick (wxListEvent &event)
void OnMouseMiddleClick (wxListEvent &event)
void OnKeyPressed (wxKeyEvent &event)
void OnItemSelectionChanged (wxListEvent &event)
void PreviewFile (CPartFile *file)
void ShowFileDetailDialog (long index)
Static Private Member Functions
static int wxCALLBACK SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData)
static int Compare (const CPartFile *file1, const CPartFile *file2, long lParamSort)
Private Attributes
ListItems m_ListItems
wxMenu * m_menu
wxBrush m_hilightBrush
wxBrush m_hilightUnfocusBrush
uint8 m_category
bool m_ItemSelectionChangePending
int m_filecount
Detailed Description
This class is responsible for representing the download queue.
The CDownlodListCtrl class is responsible for drawing files being downloaded. It is in many ways primary widget within the application, since it is here that users can inspect and manipulate their current downloads.
Constructor & Destructor Documentation
CDownloadListCtrl::CDownloadListCtrl (wxWindow * parent, wxWindowID winid = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxLC_ICON, const wxValidator & validator = wxDefaultValidator, const wxString & name = wxT("downloadlistctrl"))
Constructor.
See also:
CMuleListCtrl::CMuleListCtrl for documentation of parameters.
Member Function Documentation
void CDownloadListCtrl::AddFile (CPartFile * file)
Adds a file to the list, but it wont show unless it matches the current category.
Parameters:
A valid pointer to a new partfile.
Please note that duplicates wont be added.
References m_category, m_ListItems, ShowFile(), and CMuleListCtrl::SortList().
void CDownloadListCtrl::ChangeCategory (int newCategory)
Changes the displayed category and updates the list of shown files.
Parameters:
newCategory The new category to display.
References m_category, m_ListItems, and ShowFile().
Referenced by CTransferWnd::OnSetDefaultCat().
wxString CDownloadListCtrl::GetTTSText (unsigned item) const [private, virtual]
See also:
CMuleListCtrl::GetTTSText
Reimplemented from CMuleListCtrl.
void CDownloadListCtrl::RemoveFile (CPartFile * file)
Removes the specified file from the list.
Parameters:
file A valid pointer of the file to be removed.
This function also removes any sources assosiated with the file.
References m_ListItems, and ShowFile().
void CDownloadListCtrl::ShowFile (CPartFile * file, bool show)
Shows or hides the sources of a specific file.
Parameters:
file A valid pointer to the file to be shown/hidden.
show Whenever or not to show the file.
If the file is hidden, then its sources will also be hidden.
References m_ListItems, and ShowFilesCount().
Referenced by AddFile(), ChangeCategory(), RemoveFile(), and UpdateItem().
int CDownloadListCtrl::SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData) [static, private]
Wrapper around the user-provided sorter function.
This function ensures that items are sorted in the order specified by clicking on column-headers, and also enforces that different entries are never considered equal. This is required for lists that make use of child-items, since otherwise, parents may not end up properly located in relation to child-items.
Reimplemented from CMuleListCtrl.
References CMuleListCtrl::COLUMN_MASK, and CMuleListCtrl::SORT_DES.
void CDownloadListCtrl::UpdateItem (const void * toupdate)
Updates the state of the specified item, possibly causing a redrawing.
Parameters:
toupdate The source or file to be updated.
Calling this function with a file as the argument will ensure that the file is hidden/shown depending on its state and the currently selected category.
References m_category, m_ListItems, and ShowFile().
Member Data Documentation
ListItems CDownloadListCtrl::m_ListItems [private]
This list contains everything shown on the list.
Sources are only to be found on this list if they are being displayed, whereas files can always be found on this list, even if they are currently hidden.
Referenced by AddFile(), ChangeCategory(), ClearCompleted(), RemoveFile(), ShowFile(), UpdateItem(), and ~CDownloadListCtrl().
The documentation for this class was generated from the following files:
src/DownloadListCtrl.h
src/DownloadListCtrl.cpp