aMule: CMD4Hash Class Reference
CMD4Hash Class Reference
Container-class for the MD4 hashes used in aMule.
#include <MD4Hash.h>
Public Member Functions
CMD4Hash ()
CMD4Hash (const Kademlia::CUInt128 &hash)
CMD4Hash (const unsigned char hash[])
bool operator== (const CMD4Hash &other_hash) const
bool operator!= (const CMD4Hash &other_hash) const
bool operator< (const CMD4Hash &other_hash) const
bool IsEmpty () const
void Clear ()
bool Decode (const std::string &hash)
std::string EncodeSTL () const
void SetHash (const unsigned char hash[])
unsigned char * GetHash ()
const unsigned char * GetHash () const
unsigned char operator[] (size_t i) const
unsigned char & operator[] (size_t i)
Private Attributes
unsigned char m_hash [MD4HASH_LENGTH]
Detailed Description
Container-class for the MD4 hashes used in aMule.
This is a safe representation of the MD4 hashes used in aMule. By transparently wrapping the char array used to store the hash, we get the advantages of assigment, equality and non-equality operators, plus other nifty features.
Please remember that the hashes are arrays with length 16 WITHOUT a zero-terminator!
Constructor & Destructor Documentation
CMD4Hash::CMD4Hash () [inline]
Default constructor.
The default constructor creates an empty hash of length 16. Each field of the char array has an initial value of zero.
References Clear().
CMD4Hash::CMD4Hash (const Kademlia::CUInt128 & hash) [inline]
Create a CMD4Hash from a CUInt128.
Parameters:
hash The 128 bits integer to be used.
References SetHash().
CMD4Hash::CMD4Hash (const unsigned char hash[]) [inline, explicit]
Cast a unsigned char array to a CMD4Hash.
Parameters:
hash The array to be cast.
Please note that the array must either be a NULL pointer or be at least 16 chars long, not including any possible zero-terminator!
References SetHash().
Member Function Documentation
void CMD4Hash::Clear () [inline]
Resets the contents of the hash.
This functions sets the value of each field of the hash to zero. IsEmpty() will return true after a call to this function.
References m_hash.
Referenced by CMD4Hash(), CECFileConfig::ReadHash(), and SetHash().
bool CMD4Hash::Decode (const std::string & hash) [inline]
Decodes a 32 char long hexadecimal representation of a MD4 hash.
Parameters:
hash The hash representation to be converted. Length must be 32.
Returns:
Return value specifies if the hash was succesfully decoded.
This function converts a hexadecimal representation of a MD4 hash and stores it in the m_hash data-member.
References m_hash.
Referenced by CECFileConfig::ReadHash().
std::string CMD4Hash::EncodeSTL () const [inline]
Creates a 32 char long hexadecimal representation of a MD4 hash.
Returns:
Hexadecimal representation of the m_hash data-member.
This function creates a hexadecimal representation of the MD4 hash stored in the m_hash data-member and returns it.
References m_hash.
unsigned char* CMD4Hash::GetHash () [inline]
Explicit access to the hash-array.
Returns:
Pointer to the hash array.
References m_hash.
Referenced by CECTag::CECTag(), and CPreferences::CPreferences().
bool CMD4Hash::IsEmpty () const [inline]
Returns true if the hash is empty.
Returns:
True if all fields are zero, false otherwise.
This functions checks the contents of the hash and returns true only if each field of the array contains the value zero. To achive an empty hash, the function Clear() can be used.
References m_hash.
Referenced by CPreferences::CPreferences(), CClientDetailDialog::OnInitDialog(), CClientList::UpdateClientHash(), and CECFileConfig::WriteHash().
bool CMD4Hash::operator!= (const CMD4Hash & other_hash) const [inline]
Non-equality operator.
Returns true if there is any difference between the two hashes.
bool CMD4Hash::operator< (const CMD4Hash & other_hash) const [inline]
Less than operator.
Returns:
True if the hash is less than other_hash, false otherwise.
The purpose of this function is to enable the usage of CMD4Hashes in sorted STL containers like std::map.
References m_hash.
bool CMD4Hash::operator== (const CMD4Hash & other_hash) const [inline]
Equality operator.
Returns true if all fields of both hashes are the same.
References m_hash.
unsigned char CMD4Hash::operator[] (size_t i) const [inline]
Explic access to values in the hash-array.
Parameters:
i An index less than the length of an MD4 hash.
Returns:
The value (or its reference) at the given index.
References m_hash.
void CMD4Hash::SetHash (const unsigned char hash[]) [inline]
Explicitly set the hash-array to the contents of a unsigned char array.
Parameters:
hash The array to be assigned.
The hash must either be a NULL pointer or be of length 16.
References Clear(), and m_hash.
Referenced by CMD4Hash().
Member Data Documentation
unsigned char CMD4Hash::m_hash[MD4HASH_LENGTH] [private]
The raw MD4-hash.
The raw representation of the MD4-hash. In most cases, you should try to avoid direct access and instead use the member functions.
Referenced by Clear(), Decode(), EncodeSTL(), GetHash(), IsEmpty(), operator<(), operator==(), operator[](), and SetHash().
The documentation for this class was generated from the following file:
src/MD4Hash.h