aMule: CTransferWnd Class Reference
CTransferWnd Class Reference
This class takes care of managing the lists and other controls contained in the transfer-window.
#include <TransferWnd.h>
Public Member Functions
CTransferWnd (wxWindow *pParent=NULL)
~CTransferWnd ()
void AddCategory (Category_Struct *category)
void UpdateCategory (int index)
void RemoveCategory (int index)
void RemoveCategoryPage (int index)
void UpdateCatTabTitles ()
void Prepare ()
Public Attributes
CDownloadListCtrl * downloadlistctrl
CSourceListCtrl * clientlistctrl
Private Member Functions
void OnSetCatStatus (wxCommandEvent &event)
void OnSetCatPriority (wxCommandEvent &event)
void OnAddCategory (wxCommandEvent &event)
void OnDelCategory (wxCommandEvent &event)
void OnEditCategory (wxCommandEvent &event)
void OnSetDefaultCat (wxCommandEvent &event)
void OnBtnClearDownloads (wxCommandEvent &evt)
void OnCategoryChanged (wxBookCtrlEvent &evt)
void OnNMRclickDLtab (wxMouseEvent &evt)
void OnToggleClientList (wxCommandEvent &event)
void OnSashPositionChanging (wxSplitterEvent &evt)
Private Attributes
int m_splitter
wxMenu * m_menu
CMuleNotebook * m_dlTab
Static Private Attributes
static const int s_splitterMin = 90
Detailed Description
This class takes care of managing the lists and other controls contained in the transfer-window.
It's primary function is to manage the user-defined categories.
Member Function Documentation
void CTransferWnd::AddCategory (Category_Struct * category)
Adds the specified category to the end of the list.
Parameters:
category A pointer to the new category.
This function should be called after a category has been added to the lists of categories. The new category is assumed to be the last, and thus will be appended to the end of the tabs on the category-notebook.
References m_dlTab, and UpdateCategory().
void CTransferWnd::Prepare ()
Call this function before displaying the dialog.
This functions does a few tasks to ensure that the dialog is looking the right way.
References clientlistctrl, m_splitter, OnToggleClientList(), and s_splitterMin.
void CTransferWnd::UpdateCategory (int index)
Updates the title of the specified category.
Parameters:
index The index of the category on the notebook. -1 will update all categories.
References m_dlTab.
Referenced by AddCategory(), OnSetDefaultCat(), and UpdateCatTabTitles().
The documentation for this class was generated from the following files:
src/TransferWnd.h
src/TransferWnd.cpp