aMule: CAICHSyncTask Class Reference
CAICHSyncTask Class Reference
This task synchronizes the AICH hashlist.
#include <ThreadTasks.h>
Protected Member Functions
virtual void Entry ()
bool ConvertToKnown2ToKnown264 ()
Detailed Description
This task synchronizes the AICH hashlist.
Shared files that are lacking a AICH-hash are scheduled for hashing.
Member Function Documentation
bool CAICHSyncTask::ConvertToKnown2ToKnown264 () [protected]
Converts old known2.met files to known2_64.met files.
References CPath::FileExists(), CFile::Flush(), CScopedArray< TYPE >::get(), CFile::GetLength(), CFile::GetPosition(), CFile::Open(), CFileDataIO::Read(), CFileDataIO::Write(), and CFileDataIO::WriteUInt8().
Referenced by Entry().
The documentation for this class was generated from the following files:
src/ThreadTasks.h
src/ThreadTasks.cpp