aMule: UploadBandwidthThrottler Class Reference
UploadBandwidthThrottler Class Reference
Public Member Functions
UploadBandwidthThrottler ()
~UploadBandwidthThrottler ()
uint64 GetNumberOfSentBytesSinceLastCallAndReset ()
uint64 GetNumberOfSentBytesOverheadSinceLastCallAndReset ()
void AddToStandardList (uint32 index, ThrottledFileSocket *socket)
bool RemoveFromStandardList (ThrottledFileSocket *socket)
void QueueForSendingControlPacket (ThrottledControlSocket *socket, bool hasSent=false)
void RemoveFromAllQueues (ThrottledControlSocket *socket)
void RemoveFromAllQueues (ThrottledFileSocket *socket)
void EndThread ()
Private Types
typedef std::deque
< ThrottledControlSocket * > SocketQueue
typedef std::deque
< ThrottledFileSocket * > FileSocketQueue
Private Member Functions
void DoRemoveFromAllQueues (ThrottledControlSocket *socket)
bool RemoveFromStandardListNoLock (ThrottledFileSocket *socket)
void * Entry ()
Private Attributes
bool m_doRun
wxMutex m_sendLocker
wxMutex m_tempQueueLocker
SocketQueue m_ControlQueue_list
SocketQueue m_ControlQueueFirst_list
SocketQueue m_TempControlQueue_list
SocketQueue m_TempControlQueueFirst_list
FileSocketQueue m_StandardOrder_list
uint64 m_SentBytesSinceLastCall
uint64 m_SentBytesSinceLastCallOverhead
Constructor & Destructor Documentation
UploadBandwidthThrottler::~UploadBandwidthThrottler ()
The destructor stops the thread.
If the thread has already stoppped, destructor does nothing.
References EndThread().
Member Function Documentation
void UploadBandwidthThrottler::AddToStandardList (uint32 index, ThrottledFileSocket * socket)
Add a socket to the list of sockets that have upload slots.
The main thread will continously call send on these sockets, to give them chance to work off their queues. The sockets are called in the order they exist in the list, so the top socket (index 0) will be given a chance first to use bandwidth, and then the next socket (index 1) etc.
It is possible to add a socket several times to the list without removing it inbetween, but that should be avoided.
Parameters:
index insert the socket at this place in the list. An index that is higher than the current number of sockets in the list will mean that the socket should be inserted last in the list.
socket the address to the socket that should be added to the list. If the address is NULL, this method will do nothing.
References RemoveFromStandardListNoLock().
void UploadBandwidthThrottler::DoRemoveFromAllQueues (ThrottledControlSocket * socket) [private]
Remove the socket from all lists and queues.
This will make it safe to erase/delete the socket. It will also cause the main thread to stop calling send() for the socket.
Parameters:
socket address to the socket that should be removed
void UploadBandwidthThrottler::EndThread ()
Make the thread exit.
This method will not return until the thread has stopped looping. This guarantees that the thread will not access the CEMSockets after this call has exited.
Referenced by ~UploadBandwidthThrottler().
void * UploadBandwidthThrottler::Entry () [private]
The thread method that handles calling send for the individual sockets.
Control packets will always be tried to be sent first. If there is any bandwidth leftover after that, send() for the upload slot sockets will be called in priority order until we have run out of available bandwidth for this loop. Upload slots will not be allowed to go without having sent called for more than a defined amount of time (i.e. two seconds).
Returns:
always returns 0.
uint64 UploadBandwidthThrottler::GetNumberOfSentBytesOverheadSinceLastCallAndReset ()
Find out how many bytes that has been put on the sockets since the last call to this method.
Excludes overhead of control packets.
Returns:
the number of bytes that has been put on the sockets since the last call
uint64 UploadBandwidthThrottler::GetNumberOfSentBytesSinceLastCallAndReset ()
Find out how many bytes that has been put on the sockets since the last call to this method.
Includes overhead of control packets.
Returns:
the number of bytes that has been put on the sockets since the last call
void UploadBandwidthThrottler::QueueForSendingControlPacket (ThrottledControlSocket * socket, bool hasSent = false)
Notifies the send thread that it should try to call controlpacket send for the supplied socket.
It is allowed to call this method several times for the same socket, without having controlpacket send called for the socket first. The doublette entries are never filtered, since it is incurs less cpu overhead to simply call Send() in the socket for each double. Send() will already have done its work when the second Send() is called, and will just return with little cpu overhead.
Parameters:
socket address to the socket that requests to have controlpacket send to be called on it
bool UploadBandwidthThrottler::RemoveFromStandardList (ThrottledFileSocket * socket)
Remove a socket from the list of sockets that have upload slots.
If the socket has mistakenly been added several times to the list, this method will return all of the entries for the socket.
Parameters:
socket the address of the socket that should be removed from the list. If this socket does not exist in the list, this method will do nothing.
References RemoveFromStandardListNoLock().
bool UploadBandwidthThrottler::RemoveFromStandardListNoLock (ThrottledFileSocket * socket) [private]
Remove a socket from the list of sockets that have upload slots.
NOT THREADSAFE! This is an internal method that doesn't take the necessary lock before it removes the socket. This method should only be called when the current thread already owns the m_sendLocker lock!
Parameters:
socket address of the socket that should be removed from the list. If this socket does not exist in the list, this method will do nothing.
Referenced by AddToStandardList(), and RemoveFromStandardList().
The documentation for this class was generated from the following files:
src/UploadBandwidthThrottler.h
src/UploadBandwidthThrottler.cpp