aMule: CScopedPtr< TYPE > Class Template Reference
CScopedPtr< TYPE > Class Template Reference
CScopedPtr is a simple smart pointer.
#include <ScopedPtr.h>
Public Member Functions
CScopedPtr (TYPE *ptr)
~CScopedPtr ()
TYPE * get () const
void reset (TYPE *ptr=0)
TYPE * release ()
Private Attributes
TYPE * m_ptr
TYPE & operator* () const
TYPE * operator-> () const
CScopedPtr (const CScopedPtr< TYPE > &)
CScopedPtr< TYPE > & operator= (const CScopedPtr< TYPE > &)
Detailed Description
template<typename TYPE>
class CScopedPtr< TYPE >
CScopedPtr is a simple smart pointer.
This class is a replacement for std::auto_ptr, with simpler copying schematics, in that it doesn't allow copying or assignment, compared to auto_ptr, which allows only one instance to own a pointer (swapping at assignment).
Constructor & Destructor Documentation
template<typename TYPE> CScopedPtr< TYPE >::CScopedPtr (TYPE * ptr) [inline]
Constructor.
Note that CScopedPtr takes ownership of the pointer.
template<typename TYPE> CScopedPtr< TYPE >::~CScopedPtr () [inline]
Frees the pointer owned by the instance.
Member Function Documentation
template<typename TYPE> TYPE* CScopedPtr< TYPE >::get () const [inline]
Returns the actual pointer value.
Referenced by CHashingTask::Entry(), and CThreadScheduler::Entry().
template<typename TYPE> TYPE& CScopedPtr< TYPE >::operator* () const [inline]
Deference operators.
template<typename TYPE> TYPE* CScopedPtr< TYPE >::release () [inline]
Returns the actual pointer.
The scoped-ptr will thereafter contain NULL.
Referenced by CHashingTask::Entry().
template<typename TYPE> void CScopedPtr< TYPE >::reset (TYPE * ptr = 0) [inline]
Sets the actual pointer to a different value.
The old pointer is freed.
Referenced by CThreadScheduler::Entry().
The documentation for this class was generated from the following file:
src/ScopedPtr.h