aMule: CMuleUDPSocket Class Reference
CMuleUDPSocket Class Reference
Classes
struct UDPPack
Storage struct used for queueing packets.
Public Member Functions
CMuleUDPSocket (const wxString &name, int id, const amuleIPV4Address &address, const CProxyData *ProxyData=NULL)
virtual ~CMuleUDPSocket ()
void Open ()
void Close ()
virtual void OnSend (int errorCode)
virtual void OnReceive (int errorCode)
virtual void OnReceiveError (int errorCode, uint32 ip, uint16 port)
virtual void OnDisconnected (int errorCode)
void SendPacket (CPacket *packet, uint32 IP, uint16 port, bool bEncrypt, const uint8 *pachTargetClientHashORKadID, bool bKad, uint32 nReceiverVerifyKey)
bool Ok ()
Protected Member Functions
virtual void OnPacketReceived (uint32 ip, uint16 port, byte *buffer, size_t length)=0
SocketSentBytes SendControlData (uint32 maxNumberOfBytesToSend, uint32 minFragSize)
Private Member Functions
bool SendTo (uint8_t *buffer, uint32_t length, uint32_t ip, uint16_t port)
void CreateSocket ()
void DestroySocket ()
Private Attributes
bool m_busy
wxString m_name
int m_id
amuleIPV4Address m_addr
const CProxyData * m_proxy
wxMutex m_mutex
CEncryptedDatagramSocket * m_socket
std::list< UDPPack > m_queue
Constructor & Destructor Documentation
CMuleUDPSocket::CMuleUDPSocket (const wxString & name, int id, const amuleIPV4Address & address, const CProxyData * ProxyData = NULL)
Opens a UDP socket at the specified address.
Parameters:
name Name used when logging events.
id The ID used for events.
address The address where the socket will listen.
ProxyData ProxyData assosiated with the socket.
Member Function Documentation
void CMuleUDPSocket::Close ()
Closes the socket.
The socket can be reopened by calling Open. Closing a already closed socket is an illegal operation.
References DestroySocket(), and m_mutex.
Referenced by CClientUDPSocket::OnReceive().
void CMuleUDPSocket::CreateSocket () [private]
Creates a new socket.
Calling this function when a socket already exists is an illegal operation.
References DestroySocket(), m_addr, m_id, m_name, m_proxy, and m_socket.
Referenced by OnDisconnected(), OnReceive(), and Open().
bool CMuleUDPSocket::Ok ()
Returns true if the socket is Ok, false otherwise.
See also:
wxSocketBase::Ok
References m_mutex, and m_socket.
Referenced by OnReceive(), and SendPacket().
void CMuleUDPSocket::OnDisconnected (int errorCode) [virtual]
This function is called when the socket is lost (see comments in func.
)
References CreateSocket(), DestroySocket(), and m_name.
virtual void CMuleUDPSocket::OnPacketReceived (uint32 ip, uint16 port, byte * buffer, size_t length) [protected, pure virtual]
This function is called when a packet has been received.
Parameters:
addr The address from where data was received.
buffer The data that has been received.
length The length of the data buffer.
Implemented in CClientUDPSocket, and CServerUDPSocket.
Referenced by OnReceive().
void CMuleUDPSocket::OnReceive (int errorCode) [virtual]
This function is called by aMule when there are data to be received.
Reimplemented in CClientUDPSocket.
References CreateSocket(), DestroySocket(), m_mutex, m_name, m_socket, Ok(), OnPacketReceived(), and OnReceiveError().
virtual void CMuleUDPSocket::OnReceiveError (int errorCode, uint32 ip, uint16 port) [virtual]
This function is called by aMule when there is an error while receiving.
Reimplemented in CServerUDPSocket.
Referenced by OnReceive().
void CMuleUDPSocket::OnSend (int errorCode) [virtual]
This function is called by aMule when the socket may send.
References m_busy, m_mutex, and m_queue.
void CMuleUDPSocket::Open ()
Opens the socket.
The socket is bound to the address specified in the constructor.
References CreateSocket(), and m_mutex.
void CMuleUDPSocket::SendPacket (CPacket * packet, uint32 IP, uint16 port, bool bEncrypt, const uint8 * pachTargetClientHashORKadID, bool bKad, uint32 nReceiverVerifyKey)
Queues a packet for sending.
Parameters:
packet The packet to send.
IP The target IP address.
port The target port.
bEncrypt If the packet must be encrypted
port The target port.
pachTargetClientHashORKadID The client hash or Kad ID
bKad
nReceiverVerifyKey Note that CMuleUDPSocket takes ownership of the packet.
References m_mutex, m_name, m_queue, and Ok().
bool CMuleUDPSocket::SendTo (uint8_t * buffer, uint32_t length, uint32_t ip, uint16_t port) [private]
Sends a packet to the specified address.
Parameters:
buffer The data to be sent.
length the length of the data buffer.
ip The target ip address.
port The target port.
References m_busy, m_name, and m_socket.
Referenced by SendControlData().
The documentation for this class was generated from the following files:
src/MuleUDPSocket.h
src/MuleUDPSocket.cpp