aMule: CRemoteConnect Class Reference
CRemoteConnect Class Reference
Public Member Functions
CRemoteConnect (wxEvtHandler *evt_handler)
void SetCapabilities (bool canZLIB, bool canUTF8numbers, bool canNotify)
bool ConnectToCore (const wxString &host, int port, const wxString &login, const wxString &pass, const wxString &client, const wxString &version)
const wxString & GetServerReply () const
bool RequestFifoFull ()
virtual void OnConnect ()
virtual void OnLost ()
void SendRequest (CECPacketHandlerBase *handler, const CECPacket *request)
void SendPacket (const CECPacket *request)
void ShutDown ()
void Ed2kLink (wxString *link)
void StartKad ()
void StopKad ()
void ConnectED2K (uint32 ip, uint16 port)
void DisconnectED2K ()
void AddServer (uint32 ip, uint16 port)
void RemoveServer (uint32 ip, uint16 port)
void GetServerList ()
void UpdateServerList (wxString url)
void StartSearch ()
void StopSearch ()
void GetSearchProgress ()
void DownloadSearchResult (uint32 *file)
void GetStatistics ()
void GetConnectionState ()
void GetDlQueue (CMD4Hash *file)
void GetUpQueue (CMD4Hash *file)
void GetWtQueue (CMD4Hash *file)
void DropNoNeededSources (CMD4Hash *file)
void DropFullQueueSources (CMD4Hash *file)
void DropHighQueueSources (CMD4Hash *file)
void CleanUpSources (CMD4Hash *file)
void SwapA4AFThis (CMD4Hash *file)
void SwapA4AFThisAuto (CMD4Hash *file)
void SwapA4AFOthers (CMD4Hash *file)
void Pause (CMD4Hash *file)
void Resume (CMD4Hash *file)
void Stop (CMD4Hash *file)
void SetPriority (CMD4Hash *file, uint8 priority)
void Delete (CMD4Hash *file)
void SetCategory (CMD4Hash *file, wxString category)
void GetSharedFiles ()
void SetSharedPriority (CMD4Hash *file, uint8 priority)
void ReloadSharedFiles ()
void AddDirectoryToSharedFiles (wxString dir)
void RenameFile (CMD4Hash file, wxString name)
void AddLogline ()
void AddDebugLogLine ()
void GetLog ()
void GetLastLogLine ()
void GetDebugLog ()
void GetServerInfo ()
void ClearLog ()
void ClearDebugLog ()
void ClearServerInfo ()
void GetPreferences ()
void SetPreferencesCategories ()
void SetPreferencesGeneral (wxString userNick, CMD4Hash userHash)
void SetPreferencesConnections (uint32 LineDownloadCapacity, uint32 LineUploadCapacity, uint16 MaxDownloadSpeed, uint16 MaxUploadSpeed, uint16 UploadSlotAllocation, uint16 TCPPort, uint16 UDPPort, bool DisableUDP, uint16 MaxSourcesPerFile, uint16 MaxConnections, bool EnableAutoConnect, bool EnableReconnect, bool EnableNetworkED2K, bool EnableNetworkKademlia)
void SetPreferencesMessageFilter (bool Enabled, bool FilterAll, bool AllowFromFriends, bool FilterFromUnknownClients, bool FilterByKeyword, wxString Keywords)
void SetPreferencesRemoteCrtl (bool RunOnStartup, uint16 Port, bool Guest, CMD4Hash GuestPasswdHash, bool UseGzip, uint32 RefreshInterval, wxString Template)
void SetPreferencesOnlineSig (bool Enabled)
void SetPreferencesServers (bool RemoveDeadServers, uint16 RetriesDeadServers, bool AutoUpdate, bool AddFromServer, bool AddFromClient, bool UsePrioritySystem, bool SmartLowIDCheck, bool SafeServerConnection, bool AutoConnectStaticOnly, bool ManualHighPriority)
void SetPreferencesFiles (bool ICHEnabled, bool AIHCTrust, bool NewPaused, bool NewDownloadAutoPriority, bool PreviewPriority, bool NewAutoULPriotiry, bool UploadFullChunks, bool StartNextPaused, bool ResumeSameCategory, bool SaveSources, bool ExtractMetadata, bool AllocateFullChunks, bool AllocateFullSize, bool CheckFreeSpace, uint32 MinFreeSpace)
void SetPreferencesSrcDrop (uint8 NoNeeded, bool DropFQS, bool DropHQRS, uint16 HQRSValue, uint16 AutodropTimer)
void SetPreferencesDirectories ()
void SetPreferencesStatistics ()
void SetPreferencesSecurity (uint8 CanSeeShares, uint32 FilePermissions, uint32 DirPermissions, bool IPFilterEnabled, bool IPFilterAutoUpdate, wxString IPFilterUpdateURL, uint8 IPFilterLevel, bool IPFilterFilterLAN, bool UseSecIdent)
void SetPreferencesCoreTweaks (uint16 MaxConnectionsPerFive, bool Verbose, uint32 FileBuffer, uint32 ULQueue, uint32 SRVKeepAliveTimeout)
void CreateCategory (uint32 category, wxString title, wxString folder, wxString comment, uint32 color, uint8 priority)
void UpdateCategory (uint32 category, wxString title, wxString folder, wxString comment, uint32 color, uint8 priority)
void DeleteCategory (uint32 category)
void GetStatsGraphs ()
void GetStatsTree ()
bool IsConnectedToLocalHost ()
Private Types
enum {
EC_INIT, EC_CONNECT_SENT, EC_REQ_SENT, EC_SALT_RECEIVED,
EC_PASSWD_SENT, EC_OK, EC_FAIL
}
Private Member Functions
void WriteDoneAndQueueEmpty ()
virtual const CECPacket * OnPacketReceived (const CECPacket *packet, uint32 trueSize)
bool ProcessAuthPacket (const CECPacket *reply)
Private Attributes
enum CRemoteConnect:: { ... } m_ec_state
std::list< CECPacketHandlerBase * > m_req_fifo
int m_req_count
int m_req_fifo_thr
wxEvtHandler * m_notifier
wxString m_connectionPassword
wxString m_server_reply
wxString m_client
wxString m_version
bool m_canZLIB
bool m_canUTF8numbers
bool m_canNotify
Constructor & Destructor Documentation
CRemoteConnect::CRemoteConnect (wxEvtHandler * evt_handler)
Connection to remote core
Member Function Documentation
void CRemoteConnect::OnConnect () [virtual]
Event handler for connection events.
This function is called when a connection attempt succeeds.
Reimplemented from CECSocket.
References SendPacket().
void CRemoteConnect::OnLost () [virtual]
Socket lost event handler.
This function is called when the socket is lost (either because of a network failure or because the remote end closed the socket gracefully).
The default handler destroys the socket.
Reimplemented from CECSocket.
const CECPacket * CRemoteConnect::OnPacketReceived (const CECPacket * packet, uint32 trueSize) [private, virtual]
Event handler function called when a new packet is received.
Parameters:
packet The packet that has been received.
Returns:
The reply packet or NULL if no reply needed.
In this function the application should process the received packet, and create a reply if necessary. The reply must be allocated on the heap with new. If no reply is necessary, the return value of the function should be NULL. The library will delete both packets.
Note:
This function won't be called for packets received via the SendRecvPacket() function.
Reimplemented from CECSocket.
References SendPacket().
void CRemoteConnect::SendPacket (const CECPacket * packet)
Sends an EC packet and returns immediately.
Parameters:
packet The CECPacket packet to be sent.
This is an asynchronous call, the function returns immediately and the packet is sent on idle time.
Note:
It's the caller's responsibilty to delete the packet.
Reimplemented from CECSocket.
Referenced by CamuleRemoteGuiApp::BootstrapKad(), OnConnect(), OnPacketReceived(), and CamuleRemoteGuiApp::UpdateNotesDat().
The documentation for this class was generated from the following files:
src/libs/ec/cpp/RemoteConnect.h
src/libs/ec/cpp/RemoteConnect.cpp