aMule: CMemFile Class Reference
CMemFile Class Reference
CMemFile handles virtual files stored in memory.
#include <MemFile.h>
Public Member Functions
CMemFile (unsigned int growthRate=1024)
CMemFile (byte *buffer, size_t bufferSize)
CMemFile (const byte *buffer, size_t bufferSize)
virtual ~CMemFile ()
virtual uint64 GetPosition () const
virtual uint64 GetLength () const
virtual void SetLength (size_t newLen)
virtual void Reset () const
virtual sint64 GetAvailable () const
virtual void ResetData ()
byte * GetRawBuffer () const
Protected Member Functions
virtual sint64 doRead (void *buffer, size_t count) const
virtual sint64 doWrite (const void *buffer, size_t count)
virtual sint64 doSeek (sint64 offset) const
Private Member Functions
void enlargeBuffer (size_t size)
CMemFile (const CMemFile &)
CMemFile & operator= (const CMemFile &)
Private Attributes
unsigned int m_growthRate
size_t m_position
size_t m_BufferSize
size_t m_fileSize
bool m_delete
bool m_readonly
byte * m_buffer
Detailed Description
CMemFile handles virtual files stored in memory.
This class allows for manipulation of binary data in memory such as data sent over networks. Using this class rather than writing the stream onto a struct confers the following advantages:
Contents may be read dynamically in case of various versions of the same packet.
Endian correction is handled transparently. When reading and writing values, CMemFile converts to and from little-endian, so that no explicit endian convertions are nescesarry.
Strings of dynamic length can be read.
Most of these advantages also hold for writing packets.
See also:
CFileDataIO
Constructor & Destructor Documentation
CMemFile::CMemFile (unsigned int growthRate = 1024)
Creates a dynamic file object.
Parameters:
growthRate The growth-rate of the buffer.
The growth-rate specified by how much the buffer-size will be increased when the memfile runs out of space. Normally this means that the amount of re-allocations is cut down at the expence of slightly higher mem-usage.
If the size of the entire file to be written is known in advance, one can avoid needless re-allocations by specifying the exact length as the growth-rate.
If the growth-rate is set to zero, the memfile will allocate exactly the needed amount of memory and no more when resizing.
References m_buffer, m_BufferSize, m_delete, m_fileSize, m_growthRate, m_position, and m_readonly.
CMemFile::CMemFile (byte * buffer, size_t bufferSize)
Creates a mem-file attached to an already existing buffer.
Parameters:
buffer A pre-existing buffer.
bufferSize The size of the buffer.
A buffer attached to a memfile is assumed to already contain data and therefore the file-size is set to match the size of of the buffer.
Note that while it is valid to resize the buffer to a length between zero and 'bufferSize', it is not valid to resize it to a length greater than the length specified in the constructor. This also holds for writes that would increase the length.
The buffer is _not_ freed by CMemFile upon destruction.
If the buffer is a const byte*, the memfile is read-only.
References m_buffer, m_BufferSize, m_delete, m_fileSize, m_growthRate, m_position, and m_readonly.
CMemFile::~CMemFile () [virtual]
Destructor.
References m_buffer, and m_delete.
Member Function Documentation
sint64 CMemFile::doRead (void * buffer, size_t count) const [protected, virtual]
See also:
CFileDataIO::doRead
Implements CFileDataIO.
References m_buffer, m_fileSize, and m_position.
sint64 CMemFile::doSeek (sint64 offset) const [protected, virtual]
See also:
CFileDataIO::doSeek
Implements CFileDataIO.
References m_position.
Referenced by Reset().
sint64 CMemFile::doWrite (const void * buffer, size_t count) [protected, virtual]
See also:
CFileDataIO::doWrite
Implements CFileDataIO.
References enlargeBuffer(), m_buffer, m_BufferSize, m_fileSize, m_position, and m_readonly.
void CMemFile::enlargeBuffer (size_t size) [private]
Enlarges the buffer to at least 'size' length.
References m_buffer, m_BufferSize, m_delete, m_growthRate, and m_readonly.
Referenced by doWrite(), and SetLength().
uint64 CMemFile::GetLength () const [virtual]
See also:
CFileDataIO::GetLength
Implements CFileDataIO.
References m_fileSize.
Referenced by GetAvailable(), CSearchList::OnGlobalSearchTimer(), and CSearchList::ProcessSharedFileList().
uint64 CMemFile::GetPosition () const [virtual]
See also:
CFileDataIO::GetPosition
Implements CFileDataIO.
References m_position.
Referenced by GetAvailable(), CSearchList::KademliaSearchKeyword(), and CSearchList::ProcessSharedFileList().
void CMemFile::SetLength (size_t newLen) [virtual]
Changes the length of the file, possibly resizing the buffer.
Parameters:
newLen The new length of the file.
If the current position is greater than the new length, it will be set to the end of the file.
Note that changing the lenght of a file with an attached buffer to a value greater than the actual buffer size is an illegal operation.
References enlargeBuffer(), m_BufferSize, m_fileSize, m_position, and m_readonly.
The documentation for this class was generated from the following files:
src/MemFile.h
src/MemFile.cpp