aMule: CStatTreeItemRatio Class Reference
CStatTreeItemRatio Class Reference
Tree item for displaying ratio between two counters.
#include <StatTree.h>
Public Member Functions
CStatTreeItemRatio (const wxString &label, const CStatTreeItemCounter *cnt1, const CStatTreeItemCounter *cnt2, uint64_t(*totalfunc1)()=NULL, uint64_t(*totalfunc2)()=NULL)
virtual wxString GetDisplayString () const
Protected Member Functions
virtual void AddECValues (CECTag *tag) const
Protected Attributes
const CStatTreeItemCounter * m_counter1
const CStatTreeItemCounter * m_counter2
uint64_t(* m_totalfunc1)()
uint64_t(* m_totalfunc2)()
Private Member Functions
wxString GetString () const
Detailed Description
Tree item for displaying ratio between two counters.
Ratio is counted as counter1:counter2.
Constructor & Destructor Documentation
CStatTreeItemRatio::CStatTreeItemRatio (const wxString & label, const CStatTreeItemCounter * cnt1, const CStatTreeItemCounter * cnt2, uint64_t(*)() totalfunc1 = NULL, uint64_t(*)() totalfunc2 = NULL) [inline]
See also:
CStatTreeItemBase::CStatTreeItemBase
Parameters:
cnt1 First counter to use.
cnt2 Second counter to use.
Member Function Documentation
void CStatTreeItemRatio::AddECValues (CECTag * tag) const [protected, virtual]
Add values to EC tag being generated.
Parameters:
tag The tag to which values should be added.
See also:
CStatTreeItemBase::AddECValues
Reimplemented from CStatTreeItemBase.
References CECTag::AddTag(), and GetString().
wxString CStatTreeItemRatio::GetDisplayString () const [virtual]
See also:
CStatTreeItemBase::GetDisplayString()
Reimplemented from CStatTreeItemBase.
References GetString(), and CStatTreeItemBase::m_label.
The documentation for this class was generated from the following files:
src/StatTree.h
src/StatTree.cpp