aMule: CGenericClientListCtrl Class Reference
CGenericClientListCtrl Class Reference
This class is responsible for representing clients in a generic way.
#include <GenericClientListCtrl.h>
Public Member Functions
CGenericClientListCtrl (const wxString &tablename, wxWindow *parent, wxWindowID winid, const wxPoint &pos, const wxSize &size, long style, const wxValidator &validator, const wxString &name)
virtual ~CGenericClientListCtrl ()
void InitColumnData ()
void AddSource (CKnownFile *owner, const CClientRef &source, SourceItemType type)
void RemoveSource (uint32 source, const CKnownFile *owner)
void ShowSources (const CKnownFileVector &files)
void UpdateItem (uint32 toupdate, SourceItemType type)
void SetShowing (bool status)
bool GetShowing () const
Static Protected Member Functions
static int wxCALLBACK SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData)
Protected Attributes
GenericColumnInfo m_columndata
Private Types
typedef std::multimap< uint32,
ClientCtrlItem_Struct * > ListItems
typedef ListItems::value_type ListItemsPair
typedef std::pair
< ListItems::iterator,
ListItems::iterator > ListIteratorPair
Private Member Functions
virtual CamuleDlg::DialogType GetParentDialog ()=0
void ShowSourcesCount (int diff)
virtual void OnDrawItem (int item, wxDC *dc, const wxRect &rect, const wxRect &rectHL, bool highlighted)
void DrawClientItem (wxDC *dc, int nColumn, const wxRect &rect, ClientCtrlItem_Struct *item, int iTextOffset, int iBitmapOffset, int iBitmapXSize) const
void DrawSourceStatusBar (const CClientRef &source, wxDC *dc, const wxRect &rect, bool bFlat) const
void DrawStatusBar (const CClientRef &client, wxDC *dc, const wxRect &rect1) const
virtual wxString GetTTSText (unsigned) const
virtual void SetShowSources (CKnownFile *, bool) const =0
wxString TranslateCIDToName (GenericColumnEnum cid)
void OnSwapSource (wxCommandEvent &event)
void OnViewFiles (wxCommandEvent &event)
void OnAddFriend (wxCommandEvent &event)
void OnSetFriendslot (wxCommandEvent &event)
void OnSendMessage (wxCommandEvent &event)
void OnViewClientInfo (wxCommandEvent &event)
void OnItemActivated (wxListEvent &event)
void OnMouseRightClick (wxListEvent &event)
void OnMouseMiddleClick (wxListEvent &event)
void OnKeyPressed (wxKeyEvent &event)
void RawAddSource (CKnownFile *owner, CClientRef source, SourceItemType type)
void RawRemoveSource (ListItems::iterator &it)
virtual bool IsShowingDownloadSources () const =0
Static Private Member Functions
static int Compare (const CClientRef &client1, const CClientRef &client2, long lParamColumnSort)
Private Attributes
ListItems m_ListItems
wxMenu * m_menu
wxBrush m_hilightBrush
wxBrush m_hilightUnfocusBrush
int m_clientcount
CKnownFileVector m_knownfiles
bool m_showing
Detailed Description
This class is responsible for representing clients in a generic way.
Constructor & Destructor Documentation
CGenericClientListCtrl::CGenericClientListCtrl (const wxString & tablename, wxWindow * parent, wxWindowID winid, const wxPoint & pos, const wxSize & size, long style, const wxValidator & validator, const wxString & name)
Constructor.
See also:
CMuleListCtrl::CMuleListCtrl for documentation of parameters.
Member Function Documentation
void CGenericClientListCtrl::AddSource (CKnownFile * owner, const CClientRef & source, SourceItemType type)
Adds a source belonging to the specified file.
Parameters:
owner The owner of this specific source-entry, must be a valid pointer.
source The client object to be added, must be a valid pointer.
type If the source is a current source, or a A4AF source.
Please note that the specified client will only be added to the list if it's owner is shown, otherwise the source will simply be ignored. Duplicates wont be added.
References m_knownfiles, m_ListItems, and ShowSourcesCount().
virtual CamuleDlg::DialogType CGenericClientListCtrl::GetParentDialog () [private, pure virtual]
Must be overriden by the derived class and return the dialog where this list is.
See also:
CamuleDlg::DialogType
Implemented in CSharedFilePeersListCtrl, and CSourceListCtrl.
Referenced by OnDrawItem().
virtual wxString CGenericClientListCtrl::GetTTSText (unsigned) const [inline, private, virtual]
See also:
CMuleListCtrl::GetTTSText Just a dummy
Reimplemented from CMuleListCtrl.
void CGenericClientListCtrl::InitColumnData ()
Initializes the control.
We need a 2-stage initialization so the derived class members can be called.
References CMuleListCtrl::InsertColumn(), CMuleListCtrl::LoadSettings(), and TranslateCIDToName().
void CGenericClientListCtrl::RemoveSource (uint32 source, const CKnownFile * owner)
Removes a source from the list.
Parameters:
source ID of the source to be removed.
owner Either a specific file, or NULL to remove the source from all files.
References m_ListItems, and ShowSourcesCount().
void CGenericClientListCtrl::ShowSources (const CKnownFileVector & files)
Shows the clients of specific files.
Parameters:
file A valid, sorted vector of files whose clients will be shown.
WARNING: The received vector *MUST* be odered with std::sort.
References m_knownfiles, m_ListItems, SetShowSources(), ShowSourcesCount(), and CMuleListCtrl::SortList().
Referenced by CSharedFilesWnd::SelectionUpdated().
int CGenericClientListCtrl::SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData) [static, protected]
Wrapper around the user-provided sorter function.
This function ensures that items are sorted in the order specified by clicking on column-headers, and also enforces that different entries are never considered equal. This is required for lists that make use of child-items, since otherwise, parents may not end up properly located in relation to child-items.
Reimplemented from CMuleListCtrl.
References CMuleListCtrl::COLUMN_MASK, and CMuleListCtrl::SORT_DES.
wxString CGenericClientListCtrl::TranslateCIDToName (GenericColumnEnum cid) [private]
Translate the CID to a unique string for saving column sizes.
See also:
CMuleListCtrl::InsertColumn
Referenced by InitColumnData().
void CGenericClientListCtrl::UpdateItem (uint32 toupdate, SourceItemType type)
Updates the state of the specified item, possibly causing a redrawing.
Parameters:
toupdate ID of the client to be updated.
type If the source is a current source, or a A4AF source.
References m_knownfiles, and m_ListItems.
Member Data Documentation
ListItems CGenericClientListCtrl::m_ListItems [private]
This list contains everything shown on the list.
Sources are only to be found on this list if they are being displayed
Referenced by AddSource(), RemoveSource(), ShowSources(), UpdateItem(), and ~CGenericClientListCtrl().
The documentation for this class was generated from the following files:
src/GenericClientListCtrl.h
src/GenericClientListCtrl.cpp