aMule: CStatTreeItemTotalClients Class Reference
CStatTreeItemTotalClients Class Reference
Special item for total client count.
#include <StatTree.h>
Public Member Functions
CStatTreeItemTotalClients (const wxString &label, const CStatTreeItemCounter *known, const CStatTreeItemCounter *unknown)
virtual wxString GetDisplayString () const
Protected Member Functions
virtual void AddECValues (CECTag *tag) const
Protected Attributes
const CStatTreeItemCounter * m_known
const CStatTreeItemCounter * m_unknown
Detailed Description
Special item for total client count.
Constructor & Destructor Documentation
CStatTreeItemTotalClients::CStatTreeItemTotalClients (const wxString & label, const CStatTreeItemCounter * known, const CStatTreeItemCounter * unknown) [inline]
See also:
CStatTreeItemBase::CStatTreeItemBase
Parameters:
known Counter that counts known clients.
unknown Counter that counts unknown clients.
Member Function Documentation
void CStatTreeItemTotalClients::AddECValues (CECTag * tag) const [protected, virtual]
Add values to EC tag being generated.
Parameters:
tag The tag to which values should be added.
See also:
CStatTreeItemBase::AddECValues
Reimplemented from CStatTreeItemBase.
References CECTag::AddTag(), CStatTreeItemCounterTmpl< _Tp >::GetValue(), m_known, and m_unknown.
wxString CStatTreeItemTotalClients::GetDisplayString () const [virtual]
See also:
CStatTreeItemBase::GetDisplayString()
Reimplemented from CStatTreeItemBase.
References CStatTreeItemCounterTmpl< _Tp >::GetValue(), m_known, CStatTreeItemBase::m_label, and m_unknown.
The documentation for this class was generated from the following files:
src/StatTree.h
src/StatTree.cpp