aMule: CSharedFilesWnd Class Reference
CSharedFilesWnd Class Reference
This class represents the window containing the list of shared files.
#include <SharedFilesWnd.h>
Public Member Functions
CSharedFilesWnd (wxWindow *pParent=NULL)
~CSharedFilesWnd ()
void SelectionUpdated ()
void RemoveAllSharedFiles ()
void Prepare ()
Public Attributes
CSharedFilesCtrl * sharedfilesctrl
CSharedFilePeersListCtrl * peerslistctrl
int m_splitter
Private Types
enum EClientShow { ClientShowAll = 0, ClientShowSelected, ClientShowUploading }
Private Member Functions
void OnBtnReloadShared (wxCommandEvent &evt)
void OnItemSelectionChanged (wxListEvent &evt)
void OnToggleClientList (wxCommandEvent &event)
void OnSashPositionChanging (wxSplitterEvent &evt)
void OnSelectClientsMode (wxCommandEvent &evt)
Private Attributes
wxGauge * m_bar_requests
wxGauge * m_bar_accepted
wxGauge * m_bar_transfer
wxRadioBox * m_radioClientMode
bool m_prepared
EClientShow m_clientShow
Static Private Attributes
static const int s_splitterMin = 90
Detailed Description
This class represents the window containing the list of shared files.
Member Function Documentation
void CSharedFilesWnd::Prepare ()
Call this function before displaying the dialog.
This functions does a few tasks to ensure that the dialog is looking the right way.
References m_prepared, m_splitter, OnToggleClientList(), peerslistctrl, and s_splitterMin.
void CSharedFilesWnd::SelectionUpdated ()
This function updates the statistics of the selected items.
Call this function when an item has been selected, or when a selected item changes. It
References CMuleListCtrl::IsSorting(), m_bar_accepted, m_bar_requests, m_bar_transfer, peerslistctrl, sharedfilesctrl, and CGenericClientListCtrl::ShowSources().
Referenced by OnBtnReloadShared(), OnItemSelectionChanged(), OnSelectClientsMode(), and RemoveAllSharedFiles().
The documentation for this class was generated from the following files:
src/SharedFilesWnd.h
src/SharedFilesWnd.cpp