aMule: CUpDownClient Class Reference
CUpDownClient Class Reference
Classes
struct A4AFStamp
This struct is used to keep track of CPartFiles which this source shares.
struct TransferredData
Public Member Functions
CUpDownClient (CClientTCPSocket *sender=0)
CUpDownClient (uint16 in_port, uint32 in_userid, uint32 in_serverup, uint16 in_serverport, CPartFile *in_reqfile, bool ed2kID, bool checkfriend)
void Safe_Delete ()
bool HasBeenDeleted ()
ClientState GetClientState ()
bool Disconnected (const wxString &strReason, bool bFromSocket=false)
bool TryToConnect (bool bIgnoreMaxCon=false)
bool Connect ()
void ConnectionEstablished ()
const wxString & GetUserName () const
void SetIP (uint32 val)
uint32 GetIP () const
bool HasLowID () const
wxString GetFullIP () const
uint32 GetConnectIP () const
uint32 GetUserIDHybrid () const
void SetUserIDHybrid (uint32 val)
uint16_t GetUserPort () const
void SetUserPort (uint16_t port)
uint64 GetTransferredDown () const
uint32 GetServerIP () const
void SetServerIP (uint32 nIP)
uint16 GetServerPort () const
void SetServerPort (uint16 nPort)
const CMD4Hash & GetUserHash () const
void SetUserHash (const CMD4Hash &userhash)
void ValidateHash ()
bool HasValidHash () const
uint32 GetVersion () const
uint8 GetMuleVersion () const
bool ExtProtocolAvailable () const
bool IsEmuleClient () const
bool IsBanned () const
const wxString & GetClientFilename () const
uint16 GetUDPPort () const
void SetUDPPort (uint16 nPort)
uint8 GetUDPVersion () const
uint8 GetExtendedRequestsVersion () const
bool IsFriend () const
bool IsML () const
bool IsHybrid () const
uint32 GetCompatibleClient () const
void ClearDownloadBlockRequests ()
void RequestSharedFileList ()
void ProcessSharedFileList (const byte *pachPacket, uint32 nSize, wxString &pszDirectory)
void SendSharedDirectories ()
void SendSharedFilesOfDirectory (const wxString &strReqDir)
wxString GetUploadFileInfo ()
void SetUserName (const wxString &NewName)
uint8 GetClientSoft () const
void ReGetClientSoft ()
bool ProcessHelloAnswer (const byte *pachPacket, uint32 nSize)
bool ProcessHelloPacket (const byte *pachPacket, uint32 nSize)
void SendHelloAnswer ()
bool SendHelloPacket ()
void SendMuleInfoPacket (bool bAnswer, bool OSInfo=false)
bool ProcessMuleInfoPacket (const byte *pachPacket, uint32 nSize)
void ProcessMuleCommentPacket (const byte *pachPacket, uint32 nSize)
bool Compare (const CUpDownClient *tocomp, bool bIgnoreUserhash=false) const
void SetLastSrcReqTime ()
void SetLastSrcAnswerTime ()
void SetLastAskedForSources ()
uint32 GetLastSrcReqTime () const
uint32 GetLastSrcAnswerTime () const
uint32 GetLastAskedForSources () const
bool GetFriendSlot () const
void SetFriendSlot (bool bNV)
void SetCommentDirty (bool bDirty=true)
uint8 GetSourceExchange1Version () const
bool SupportsSourceExchange2 () const
bool SafeSendPacket (CPacket *packet)
void ProcessRequestPartsPacket (const byte *pachPacket, uint32 nSize, bool largeblocks)
void ProcessRequestPartsPacketv2 (const CMemFile &data)
void SendPublicKeyPacket ()
void SendSignaturePacket ()
void ProcessPublicKeyPacket (const byte *pachPacket, uint32 nSize)
void ProcessSignaturePacket (const byte *pachPacket, uint32 nSize)
uint8 GetSecureIdentState ()
void SendSecIdentStatePacket ()
void ProcessSecIdentStatePacket (const byte *pachPacket, uint32 nSize)
uint8 GetInfoPacketsReceived () const
void InfoPacketsReceived ()
uint8 GetUploadState () const
void SetUploadState (uint8 news)
uint64 GetTransferredUp () const
uint64 GetSessionUp () const
void ResetSessionUp ()
uint32 GetUploadDatarate () const
uint32 GetUpStartTimeDelay () const
uint32 GetWaitStartTime () const
bool IsDownloading () const
uint32 GetScore () const
uint32 CalculateScore ()
void ClearScore ()
uint16 GetUploadQueueWaitingPosition () const
void SetUploadQueueWaitingPosition (uint16 pos)
uint8 GetObfuscationStatus () const
uint16 GetNextRequestedPart () const
void AddReqBlock (Requested_Block_Struct *reqblock)
void CreateNextBlockPackage ()
void SetUpStartTime ()
void SetWaitStartTime ()
void ClearWaitStartTime ()
void SendHashsetPacket (const CMD4Hash &forfileid)
bool SupportMultiPacket () const
bool SupportExtMultiPacket () const
void SetUploadFileID (CKnownFile *newreqfile)
const CKnownFile * GetUploadFile () const
void SendOutOfPartReqsAndAddToWaitingQueue ()
void ProcessExtendedInfo (const CMemFile *data, CKnownFile *tempreqfile)
void ProcessFileInfo (const CMemFile *data, const CPartFile *file)
void ProcessFileStatus (bool bUdpPacket, const CMemFile *data, const CPartFile *file)
const CMD4Hash & GetUploadFileID () const
void SetUploadFileID (const CMD4Hash &new_id)
void ClearUploadFileID ()
uint32 SendBlockData ()
void ClearUploadBlockRequests ()
void SendRankingInfo ()
void SendCommentInfo (CKnownFile *file)
bool IsDifferentPartBlock () const
void UnBan ()
void Ban ()
uint32 GetAskedCount () const
void AddAskedCount ()
void ClearAskedCount ()
void FlushSendBlocks ()
void SetLastUpRequest ()
uint32 GetLastUpRequest () const
size_t GetUpPartCount () const
void SetRequestFile (CPartFile *reqfile)
CPartFile * GetRequestFile () const
uint8 GetDownloadState () const
void SetDownloadState (uint8 byNewState)
uint32 GetLastAskedTime () const
void ResetLastAskedTime ()
bool IsPartAvailable (uint16 iPart) const
bool IsUpPartAvailable (uint16 iPart) const
const BitVector & GetPartStatus () const
const BitVector & GetUpPartStatus () const
float GetKBpsDown () const
float CalculateKBpsDown ()
uint16 GetRemoteQueueRank () const
uint16 GetOldRemoteQueueRank () const
void SetRemoteQueueFull (bool flag)
bool IsRemoteQueueFull () const
void SetRemoteQueueRank (uint16 nr)
bool AskForDownload ()
void SendStartupLoadReq ()
void SendFileRequest ()
void ProcessHashSet (const byte *packet, uint32 size)
bool AddRequestForAnotherFile (CPartFile *file)
bool DeleteFileRequest (CPartFile *file)
void DeleteAllFileRequests ()
void SendBlockRequests ()
void ProcessBlockPacket (const byte *packet, uint32 size, bool packed, bool largeblocks)
uint16 GetAvailablePartCount () const
bool SwapToAnotherFile (bool bIgnoreNoNeeded, bool ignoreSuspensions, bool bRemoveCompletely, CPartFile *toFile=NULL)
void UDPReaskACK (uint16 nNewQR)
void UDPReaskFNF ()
void UDPReaskForDownload ()
bool IsSourceRequestAllowed ()
uint16 GetUpCompleteSourcesCount () const
void SetUpCompleteSourcesCount (uint16 n)
uint8 GetChatState ()
void SetChatState (uint8 nNewS)
EChatCaptchaState GetChatCaptchaState () const
void ProcessCaptchaRequest (CMemFile *data)
void ProcessCaptchaReqRes (uint8 nStatus)
void ProcessChatMessage (wxString message)
uint8 GetMessagesReceived () const
void IncMessagesReceived ()
uint8 GetMessagesSent () const
void IncMessagesSent ()
bool IsSpammer () const
void SetSpammer (bool bVal)
bool IsMessageFiltered (const wxString &message)
const wxString & GetFileComment () const
uint8 GetFileRating () const
const wxString & GetSoftStr () const
const wxString & GetSoftVerStr () const
const wxString GetServerName () const
uint16 GetKadPort () const
void SetKadPort (uint16 nPort)
void SetReqFileAICHHash (CAICHHash *val)
CAICHHash * GetReqFileAICHHash () const
bool IsSupportingAICH () const
void SendAICHRequest (CPartFile *pForFile, uint16 nPart)
bool IsAICHReqPending () const
void ProcessAICHAnswer (const byte *packet, uint32 size)
void ProcessAICHRequest (const byte *packet, uint32 size)
void ProcessAICHFileHash (CMemFile *data, const CPartFile *file)
EUtf8Str GetUnicodeSupport () const
int unzip (Pending_Block_Struct *block, byte *zipped, uint32 lenZipped, byte **unzipped, uint32 *lenUnzipped, int iRecursion=0)
void UpdateDisplayedInfo (bool force=false)
int GetFileListRequested () const
void SetFileListRequested (int iFileListRequested)
void ResetFileStatusInfo ()
bool CheckHandshakeFinished () const
bool GetSentCancelTransfer () const
void SetSentCancelTransfer (bool bVal)
wxString GetClientFullInfo ()
wxString GetClientShortInfo ()
const wxString & GetClientOSInfo () const
void ProcessPublicIPAnswer (const byte *pbyData, uint32 uSize)
void SendPublicIPRequest ()
void SetSocket (CClientTCPSocket *socket)
CClientTCPSocket * GetSocket () const
bool IsConnected () const
bool SendPacket (CPacket *packet, bool delpacket=true, bool controlpacket=true)
float SetDownloadLimit (uint32 reducedownload)
bool SendChatMessage (const wxString &message)
bool HasBlocks () const
ESourceFrom GetSourceFrom () const
void SetSourceFrom (ESourceFrom val)
const byte * GetBuddyID () const
void SetBuddyID (const byte *m_achTempBuddyID)
bool HasValidBuddyID () const
void SetBuddyIP (uint32 val)
uint32 GetBuddyIP () const
void SetBuddyPort (uint16 val)
uint16 GetBuddyPort () const
bool SendBuddyPingPong ()
bool AllowIncomeingBuddyPingPong ()
void SetLastBuddyPingPongTime ()
EKadState GetKadState () const
void SetKadState (EKadState nNewS)
uint8 GetKadVersion ()
void ProcessFirewallCheckUDPRequest (CMemFile *data)
bool SendBuddyPing ()
int GetHashType () const
void CheckForAggressive ()
const wxString & GetClientModString () const
const wxString & GetClientVerString () const
const wxString & GetVersionString () const
void UpdateStats ()
void * GetCreditsHash () const
uint16 GetLastDownloadingPart () const
bool GetOSInfoSupport () const
bool GetVBTTags () const
uint16 GetLastPartAsked () const
void SetLastPartAsked (uint16 nPart)
CFriend * GetFriend () const
void SetFriend (CFriend *newfriend)
bool IsIdentified () const
bool IsBadGuy () const
bool SUIFailed () const
bool SUINeeded () const
bool SUINotSupported () const
uint64 GetDownloadedTotal () const
uint64 GetUploadedTotal () const
double GetScoreRatio () const
uint32 GetCreationTime () const
bool SupportsLargeFiles () const
EIdentState GetCurrentIdentState () const
bool SupportsCryptLayer () const
bool RequestsCryptLayer () const
bool RequiresCryptLayer () const
bool SupportsDirectUDPCallback () const
uint32_t GetDirectCallbackTimeout () const
bool HasObfuscatedConnectionBeenEstablished () const
void SetCryptLayerSupport (bool bVal)
void SetCryptLayerRequest (bool bVal)
void SetCryptLayerRequires (bool bVal)
void SetDirectUDPCallbackSupport (bool bVal)
void SetConnectOptions (uint8_t options, bool encryption=true, bool callback=true)
bool ShouldReceiveCryptUDPPackets () const
bool HasDisabledSharedFiles () const
CUpDownClient (class CEC_UpDownClient_Tag *)
void RequestSharedFileList ()
bool ExtProtocolAvailable () const
uint16 GetAvailablePartCount () const
const wxString & GetClientFilename () const
const wxString & GetClientModString () const
const wxString & GetClientOSInfo () const
uint8 GetClientSoft () const
const wxString & GetClientVerString () const
uint64 GetDownloadedTotal () const
uint8 GetDownloadState () const
CFriend * GetFriend () const
bool GetFriendSlot () const
wxString GetFullIP () const
uint16 GetKadPort () const
float GetKBpsDown () const
uint32 GetIP () const
uint16 GetLastDownloadingPart () const
uint16 GetNextRequestedPart () const
uint8 GetObfuscationStatus () const
uint16 GetOldRemoteQueueRank () const
const BitVector & GetPartStatus () const
uint16 GetRemoteQueueRank () const
CPartFile * GetRequestFile () const
uint32 GetScore () const
double GetScoreRatio () const
uint32 GetServerIP () const
const wxString GetServerName () const
uint16 GetServerPort () const
const wxString & GetSoftStr () const
const wxString & GetSoftVerStr () const
ESourceFrom GetSourceFrom () const
uint64 GetTransferredDown () const
uint64 GetTransferredUp () const
uint32 GetUploadDatarate () const
uint64 GetUploadedTotal () const
const CKnownFile * GetUploadFile () const
uint16 GetUploadQueueWaitingPosition () const
uint8 GetUploadState () const
size_t GetUpPartCount () const
const CMD4Hash & GetUserHash () const
uint32 GetUserIDHybrid () const
const wxString & GetUserName () const
uint16 GetUserPort () const
uint32 GetVersion () const
bool HasDisabledSharedFiles () const
bool HasLowID () const
bool IsBadGuy () const
bool IsFriend () const
bool IsIdentified () const
bool IsRemoteQueueFull () const
bool IsUpPartAvailable (uint16 iPart) const
void RequestSharedFileList () const
void SetFriend (CFriend *newfriend)
void SetFriendSlot (bool bNV)
bool SUIFailed () const
bool SUINeeded () const
bool SUINotSupported () const
bool SwapToAnotherFile (bool bIgnoreNoNeeded, bool ignoreSuspensions, bool bRemoveCompletely, CPartFile *toFile=NULL)
Public Attributes
bool m_bAddNextConnect
Private Types
typedef std::map< CPartFile
*, A4AFStamp > A4AFList
Private Member Functions
~CUpDownClient ()
void Link ()
void Unlink ()
bool IsValidSwapTarget (A4AFList::iterator it, bool ignorenoneeded=false, bool ignoresuspended=false)
void Init ()
bool ProcessHelloTypePacket (const CMemFile &data)
void SendHelloTypePacket (CMemFile *data)
void SendFirewallCheckUDPRequest ()
void ClearHelloProperties ()
void CreateStandardPackets (const unsigned char *data, uint32 togo, Requested_Block_Struct *currentblock)
void CreatePackedPackets (const unsigned char *data, uint32 togo, Requested_Block_Struct *currentblock)
uint32 CalculateScoreInternal ()
~CUpDownClient ()
void Link ()
void Unlink ()
Private Attributes
uint16 m_linked
CClientCredits * credits
CFriend * m_Friend
uint64 m_nTransferredUp
sint64 m_nCurQueueSessionPayloadUp
sint64 m_addedPayloadQueueSession
uint32 m_nUpDatarate
uint32 m_nSumForAvgUpDataRate
std::list< TransferredData > m_AvarageUDR_list
A4AFList m_A4AF_list
CPartFile * m_reqfile
uint32 m_dwUserIP
uint32 m_nConnectIP
uint32 m_dwServerIP
uint32 m_nUserIDHybrid
uint16_t m_nUserPort
int16 m_nServerPort
uint32 m_nClientVersion
uint32 m_cSendblock
uint8 m_byEmuleVersion
uint8 m_byDataCompVer
bool m_bEmuleProtocol
wxString m_Username
uint32 m_FullUserIP
CMD4Hash m_UserHash
bool m_HasValidHash
uint16 m_nUDPPort
uint8 m_byUDPVer
uint8 m_bySourceExchange1Ver
uint8 m_byAcceptCommentVer
uint8 m_byExtendedRequestsVer
uint8 m_clientSoft
uint32 m_dwLastSourceRequest
uint32 m_dwLastSourceAnswer
uint32 m_dwLastAskedForSources
int m_iFileListRequested
bool m_bFriendSlot
bool m_bCommentDirty
bool m_bIsHybrid
bool m_bIsML
bool m_bSupportsPreview
bool m_bUnicodeSupport
uint16 m_nKadPort
bool m_bMultiPacket
ClientState m_clientState
CClientTCPSocket * m_socket
bool m_fNeedOurPublicIP
ESecureIdentState m_SecureIdentState
uint8 m_byInfopacketsReceived
uint32 m_dwLastSignatureIP
uint8 m_bySupportSecIdent
uint32 m_byCompatibleClient
std::list< CPacket * > m_WaitingPackets_list
uint32 m_lastRefreshedDLDisplay
uint8 m_nUploadState
uint32 m_dwUploadTime
uint32 m_cAsked
uint32 m_dwLastUpRequest
uint32 m_nCurSessionUp
uint16 m_nUpPartCount
CMD4Hash m_requpfileid
uint16 m_nUpCompleteSourcesCount
uint32 m_score
uint16 m_waitingPosition
BitVector m_upPartStatus
uint16 m_lastPartAsked
wxString m_strModVersion
std::list
< Requested_Block_Struct * > m_BlockRequests_queue
std::list
< Requested_Block_Struct * > m_DoneBlocks_list
bool m_bRemoteQueueFull
uint8 m_nDownloadState
uint16 m_nPartCount
uint32 m_dwLastAskedTime
wxString m_clientFilename
uint64 m_nTransferredDown
uint16 m_lastDownloadingPart
uint16 m_cShowDR
uint32 m_dwLastBlockReceived
uint16 m_nRemoteQueueRank
uint16 m_nOldRemoteQueueRank
bool m_bCompleteSource
bool m_bReaskPending
bool m_bUDPPending
bool m_bHashsetRequested
std::list< Pending_Block_Struct * > m_PendingBlocks_list
std::list
< Requested_Block_Struct * > m_DownloadBlocks_list
float kBpsDown
uint32 msReceivedPrev
uint32 bytesReceivedCycle
wxString m_strComment
uint8 m_byChatstate
uint8 m_nChatCaptchaState
uint8 m_cCaptchasSent
int8 m_iRating
uint8 m_cMessagesReceived
uint8 m_cMessagesSent
wxString m_strCaptchaChallenge
wxString m_strCaptchaPendingMsg
unsigned int m_fHashsetRequesting: 1
unsigned int m_fNoViewSharedFiles: 1
unsigned int m_fSupportsPreview: 1
unsigned int m_fIsSpammer: 1
unsigned int m_fSentCancelTransfer: 1
unsigned int m_fSharedDirectories: 1
unsigned int m_fSupportsAICH: 3
unsigned int m_fAICHRequested: 1
unsigned int m_fSupportsLargeFiles: 1
unsigned int m_fSentOutOfPartReqs: 1
unsigned int m_fExtMultiPacket: 1
unsigned int m_fRequestsCryptLayer: 1
unsigned int m_fSupportsCryptLayer: 1
unsigned int m_fRequiresCryptLayer: 1
unsigned int m_fSupportsSourceEx2: 1
unsigned int m_fSupportsCaptcha: 1
unsigned int m_fDirectUDPCallback: 1
unsigned int m_fOsInfoSupport: 1
unsigned int m_fValueBasedTypeTags: 1
bool m_bHelloAnswerPending
BitVector m_downPartStatus
CAICHHash * m_pReqFileAICHHash
ESourceFrom m_nSourceFrom
byte m_achBuddyID [16]
bool m_bBuddyIDValid
uint32 m_nBuddyIP
uint16 m_nBuddyPort
EKadState m_nKadState
uint8 m_byKadVersion
uint32 m_dwLastBuddyPingPongTime
uint32_t m_dwDirectCallbackTimeout
uint16 m_Aggressiveness
uint32 m_LastFileRequest
bool m_OSInfo_sent
wxString m_clientSoftString
wxString m_clientVerString
wxString m_clientVersionString
wxString m_fullClientVerString
wxString m_sClientOSInfo
wxString m_pendingMessage
int SecIdentSupRec
CKnownFile * m_uploadingfile
uint8 m_MaxBlockRequests
uint32 m_lastClientSoft
uint32 m_lastClientVersion
wxString m_lastOSInfo
uint32 m_nCreationTime
uint32 m_lastaverage
uint32 m_last_block_start
bool m_hasbeenobfuscatinglately
uint16 m_AvailPartCount
float m_kBpsDown
uint16 m_nextRequestedPart
uint8 m_obfuscationStatus
wxString m_ServerName
uint16 m_nServerPort
uint16 m_nUserPort
bool m_fNoViewSharedFiles
EIdentState m_identState
Friends
class CClientList
class CClientRef
class CUpDownClientListRem
Constructor & Destructor Documentation
CUpDownClient::~CUpDownClient () [private]
Please note that only the ClientList is allowed to delete the clients.
To schedule a client for deletion, call the CClientList::AddToDeleteQueue funtion, which will safely remove dead clients once every second.
Member Function Documentation
void CUpDownClient::CheckForAggressive ()
Checks that a client isn't aggressively re-asking for files.
Call this when a file is requested. If the time since the last request is less than MIN_REQUESTTIME, 3 is added to the m_Aggressiveness variable. If the time since the last request is >= MIN_REQUESTTIME, the variable is decremented by 1. The client is banned if the variable reaches 10 or above.
To check if a client is aggressive use the IsClientAggressive() function.
Currently this function is called when the following packets are received:
OP_STARTUPLOADREQ
OP_REASKFILEPING
References m_Aggressiveness, and m_LastFileRequest.
CClientTCPSocket* CUpDownClient::GetSocket () const [inline]
Function for accessing the socket owned by a client.
Returns:
The pointer (can be NULL) to the socket used by this client.
Please note that the socket object is quite volatile and can be removed from one function call to the next, therefore, you should normally use the safer functions below, which all check if the socket is valid before deferring it.
Referenced by CClientList::AttachToAlreadyKnown().
const CKnownFile* CUpDownClient::GetUploadFile () const [inline]
Gets the file actually on upload.
bool CUpDownClient::HasBeenDeleted () [inline]
Specifies if the client has been queued for deletion.
Returns:
True if Safe_Delete has been called, false otherwise.
bool CUpDownClient::IsConnected () const
Safe function for checking if the socket is connected.
Returns:
True if the socket exists and is connected, false otherwise.
Referenced by CClientList::AttachToAlreadyKnown(), CClientList::Process(), and SendChatMessage().
bool CUpDownClient::IsValidSwapTarget (A4AFList::iterator it, bool ignorenoneeded = false, bool ignoresuspended = false) [private]
Helper function used by SwapToAnotherFile().
Parameters:
it The iterator of the PartFile to be examined.
ignorenoneeded Do not check for the status NoNeededParts when checking the file.
ignoresuspended Do not check the timestamp when checking the file.
Returns:
True if the file is a viable target, false otherwise.
This function is used to perform checks to see if we should consider this file a viable target for A4AF swapping. Unless ignoresuspended is true, it will examine the timestamp of the file and reset it if needed.
References m_A4AF_list.
void CUpDownClient::Safe_Delete ()
This function is to be called when the client object is to be deleted.
It'll close the socket of the client and remove it from various lists that can own it.
The client will really be deleted only after thelast reference to it is unlinked;
References m_linked, and SetSocket().
Referenced by CClientList::AttachToAlreadyKnown(), CDownloadQueue::CheckAndAddSource(), and CClientList::FilterQueues().
bool CUpDownClient::SendChatMessage (const wxString & message)
Sends a message to a client.
Returns:
True if sent, false if connecting
References IsConnected(), SendPacket(), and CFileDataIO::WriteString().
Referenced by CClientList::SendChatMessage().
bool CUpDownClient::SendPacket (CPacket * packet, bool delpacket = true, bool controlpacket = true)
Safe function for sending packets.
Returns:
True if the socket exists and the packet was sent, false otherwise.
References CClientTCPSocket::SendPacket().
Referenced by SendChatMessage().
float CUpDownClient::SetDownloadLimit (uint32 reducedownload)
Safe function for setting the download limit of the socket.
Returns:
Current download speed of the client.
void CUpDownClient::SetSocket (CClientTCPSocket * socket)
Sets the current socket of the client.
Parameters:
socket The pointer to the new socket, can be NULL.
Please note that this function DOES NOT delete the old socket.
Referenced by CClientList::AttachToAlreadyKnown(), and Safe_Delete().
Member Data Documentation
BitVector CUpDownClient::m_downPartStatus [private]
This vector contains the avilability of parts for the file we requested from this user.
When changing it, be sure to call CPartFile::UpdatePartsFrequency so that the files know the actual availability of parts.
uint16 CUpDownClient::m_linked [private]
Reference count which is increased whenever client is linked to a clientref.
Clients are to be stored only by ClientRefs, CUpDownClient * are for temporary use only. Linking is done only by CClientRef which is friend, so methods are private.
Referenced by Safe_Delete().
BitVector CUpDownClient::m_upPartStatus [private]
This vector contains the avilability of parts for the file that the user is requesting.
When changing it, be sure to call CKnownFile::UpdatePartsFrequency so that the files know the actual availability of parts.
The documentation for this class was generated from the following files:
src/updownclient.h
src/UpDownClientEC.h
src/amule-remote-gui.cpp
src/BaseClient.cpp
src/DownloadClient.cpp
src/UploadClient.cpp