aMule: CStatTreeItemAverageSpeed Class Reference
CStatTreeItemAverageSpeed Class Reference
Tree item for average up/down speed.
#include <StatTree.h>
Public Member Functions
CStatTreeItemAverageSpeed (const wxString &label, const CStatTreeItemUlDlCounter *counter, const CStatTreeItemTimer *timer)
virtual wxString GetDisplayString () const
Protected Member Functions
virtual void AddECValues (CECTag *tag) const
Protected Attributes
const CStatTreeItemUlDlCounter * m_counter
const CStatTreeItemTimer * m_timer
Detailed Description
Tree item for average up/down speed.
Constructor & Destructor Documentation
CStatTreeItemAverageSpeed::CStatTreeItemAverageSpeed (const wxString & label, const CStatTreeItemUlDlCounter * counter, const CStatTreeItemTimer * timer) [inline]
See also:
CStatTreeItemBase::CStatTreeItemBase
Parameters:
counter Session up/down counter.
timer Session uptime timer.
Member Function Documentation
void CStatTreeItemAverageSpeed::AddECValues (CECTag * tag) const [protected, virtual]
Add values to EC tag being generated.
Parameters:
tag The tag to which values should be added.
See also:
CStatTreeItemBase::AddECValues
Reimplemented from CStatTreeItemBase.
References CECTag::AddTag(), CStatTreeItemTimer::GetTimerSeconds(), m_counter, and m_timer.
wxString CStatTreeItemAverageSpeed::GetDisplayString () const [virtual]
See also:
CStatTreeItemBase::GetDisplayString()
Reimplemented from CStatTreeItemBase.
References CStatTreeItemTimer::GetTimerSeconds(), m_counter, CStatTreeItemBase::m_label, and m_timer.
The documentation for this class was generated from the following files:
src/StatTree.h
src/StatTree.cpp