aMule: CSharedFilesCtrl Class Reference
CSharedFilesCtrl Class Reference
This class represents the widget used to list shared files.
#include <SharedFilesCtrl.h>
Public Member Functions
CSharedFilesCtrl (wxWindow *parent, int id, const wxPoint &pos, wxSize size, int flags)
~CSharedFilesCtrl ()
void ShowFileList ()
void ShowFile (CKnownFile *file)
void RemoveFile (CKnownFile *toremove)
void UpdateItem (CKnownFile *toupdate)
void ShowFilesCount ()
Protected Member Functions
wxString GetOldColumnOrder () const
Private Member Functions
void DoShowFile (CKnownFile *file, bool batch)
void DrawAvailabilityBar (CKnownFile *file, wxDC *dc, const wxRect &rect) const
virtual void OnDrawItem (int item, wxDC *dc, const wxRect &rect, const wxRect &rectHL, bool highlighted)
virtual wxString GetTTSText (unsigned item) const
virtual bool AltSortAllowed (unsigned column) const
void OnRightClick (wxListEvent &event)
void OnGetFeedback (wxCommandEvent &event)
void OnSetPriority (wxCommandEvent &event)
void OnSetPriorityAuto (wxCommandEvent &event)
void OnCreateURI (wxCommandEvent &event)
void OnEditComment (wxCommandEvent &event)
void OnRename (wxCommandEvent &event)
void OnKeyPressed (wxKeyEvent &event)
void OnAddCollection (wxCommandEvent &evt)
Static Private Member Functions
static int wxCALLBACK SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData)
Private Attributes
wxMenu * m_menu
Detailed Description
This class represents the widget used to list shared files.
Constructor & Destructor Documentation
CSharedFilesCtrl::CSharedFilesCtrl (wxWindow * parent, int id, const wxPoint & pos, wxSize size, int flags)
Constructor.
See also:
CMuleListCtrl::CMuleListCtrl
References CMuleListCtrl::InsertColumn(), CMuleListCtrl::LoadSettings(), m_menu, CMuleListCtrl::SetSortFunc(), CMuleListCtrl::SetTableName(), and SortProc().
Member Function Documentation
bool CSharedFilesCtrl::AltSortAllowed (unsigned column) const [private, virtual]
Function that specifies which columns have alternate sorting.
See also:
CMuleListCtrl::AltSortAllowed
Reimplemented from CMuleListCtrl.
void CSharedFilesCtrl::DoShowFile (CKnownFile * file, bool batch) [private]
Adds the specified file to the list.
If 'batch' is true, the item will be inserted last, and the files-count will not be updated, nor is the list checked for dupes.
References CMuleListCtrl::GetInsertPos(), and ShowFilesCount().
Referenced by ShowFile(), and ShowFileList().
void CSharedFilesCtrl::DrawAvailabilityBar (CKnownFile * file, wxDC * dc, const wxRect & rect) const [private]
Draws the graph of file-part availability.
Parameters:
file The file to make a graph over.
dc The wcDC to draw on.
rect The drawing area.
This function draws a barspan showing the availability of the parts of a file, for both Part-files and Known-files. Availability for Part-files is determined using the currently known sources, while availability for Known-files is determined using the sources requesting that file.
References CBarShader::Draw(), CBarShader::FillRange(), CBarShader::Set3dDepth(), CBarShader::SetFileSize(), CBarShader::SetHeight(), and CBarShader::SetWidth().
Referenced by OnDrawItem().
wxString CSharedFilesCtrl::GetTTSText (unsigned item) const [private, virtual]
See also:
CMuleListCtrl::GetTTSText
Reimplemented from CMuleListCtrl.
void CSharedFilesCtrl::RemoveFile (CKnownFile * toremove)
Removes a file from the list.
Parameters:
toremove The file to be removed.
References ShowFilesCount().
void CSharedFilesCtrl::ShowFile (CKnownFile * file)
Adds the specified file to the list, updating filecount and more.
Parameters:
file The new file to be shown.
Note that the item is inserted in sorted order.
References DoShowFile().
void CSharedFilesCtrl::ShowFileList ()
Reloads the list of shared files.
References DoShowFile(), ShowFilesCount(), and CMuleListCtrl::SortList().
int CSharedFilesCtrl::SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData) [static, private]
Sorter-function.
See also:
wxListCtrl::SortItems
Reimplemented from CMuleListCtrl.
References CMuleListCtrl::COLUMN_MASK, CMuleListCtrl::SORT_ALT, and CMuleListCtrl::SORT_DES.
Referenced by CSharedFilesCtrl().
void CSharedFilesCtrl::UpdateItem (CKnownFile * toupdate)
Updates a file on the list.
Parameters:
toupdate The file to be updated.
The documentation for this class was generated from the following files:
src/SharedFilesCtrl.h
src/SharedFilesCtrl.cpp