aMule: CSearchFile Class Reference
CSearchFile Class Reference
Represents a search-result returned from a server or client.
#include <SearchFile.h>
Classes
struct ClientStruct
Public Types
enum DownloadStatus {
NEW, DOWNLOADED, QUEUED, CANCELED,
QUEUEDCANCELED
}
Public Member Functions
CSearchFile (class CEC_SearchFile_Tag *tag)
CSearchFile (const CSearchFile &other)
CSearchFile (const CMemFile &data, bool optUTF8, wxUIntPtr searchID, uint32_t serverIP=0, uint16_t serverPort=0, const wxString &directory=wxEmptyString, bool kademlia=false)
virtual ~CSearchFile ()
void MergeResults (const CSearchFile &other)
uint32 GetSourceCount () const
uint32 GetCompleteSourceCount () const
wxUIntPtr GetSearchID () const
bool IsKademlia () const
enum DownloadStatus GetDownloadStatus () const
void SetDownloadStatus ()
void SetDownloadStatus (enum DownloadStatus s)
CSearchFile * GetParent () const
const CSearchResultList & GetChildren () const
bool HasChildren () const
bool ShowChildren () const
void SetShowChildren (bool show)
void AddChild (CSearchFile *file)
void AddClient (const ClientStruct &client)
const std::list< ClientStruct > & GetClients () const
uint32_t GetClientID () const throw ()
void SetClientID (uint32_t clientID) throw ()
uint16_t GetClientPort () const throw ()
void SetClientPort (uint16_t port) throw ()
uint32_t GetClientServerIP () const throw ()
void SetClientServerIP (uint32_t serverIP) throw ()
uint16_t GetClientServerPort () const throw ()
void SetClientServerPort (uint16_t port) throw ()
int GetClientsCount () const
void SetKadPublishInfo (uint32_t val) throw ()
uint32_t GetKadPublishInfo () const throw ()
const wxString & GetDirectory () const throw ()
Private Member Functions
CSearchFile & operator= (const CSearchFile &other)
void UpdateParent ()
Private Attributes
CSearchFile * m_parent
CSearchResultList m_children
bool m_showChildren
wxUIntPtr m_searchID
uint32 m_sourceCount
uint32 m_completeSourceCount
bool m_kademlia
enum DownloadStatus m_downloadStatus
wxString m_directory
std::list< ClientStruct > m_clients
uint32_t m_clientID
uint16_t m_clientPort
uint32_t m_clientServerIP
uint16_t m_clientServerPort
uint32_t m_kadPublishInfo
Friends
class CPartFile
class CSearchListRem
Detailed Description
Represents a search-result returned from a server or client.
A file may have either a parent or any number of children. When a child is added to a result, the parent becomes a generic representation of all its children, which will include a copy of the original result. The parent object will contain the sum of sources (total/complete) and will have the most common filename. Children are owned by their parents, and can be displayed on CSearchListCtrl.
Basic file parameters (hash, name, size, rating) can be read via the CAbstractFile functions. Tags pertaining to meta-data are stored in the taglist inherited from CAbstractFile.
TODO: Server IP/Port are currently not used. TODO: Client ID/Port are currently not used.
Constructor & Destructor Documentation
CSearchFile::CSearchFile (class CEC_SearchFile_Tag * tag)
Constructor used to create results on the remote GUI.
References AddChild(), and m_searchID.
Referenced by CSearchFile().
CSearchFile::CSearchFile (const CSearchFile & other)
Copy constructor, also copies children.
References CSearchFile(), and m_children.
CSearchFile::CSearchFile (const CMemFile & data, bool optUTF8, wxUIntPtr searchID, uint32_t serverIP = 0, uint16_t serverPort = 0, const wxString & directory = wxEmptyString, bool kademlia = false)
Normal constructor, reads a result from a packet.
Parameters:
data Source of results-packet.
optUTF8 Specifies if text-strings are to be read as UTF8.
searchID searchID The
serverIP The IP of the server that sent this result.
serverPort The port of the server that sent this result.
directory If from a clients shared files, the directory this file is in.
kademlia Specifies if this was from a kad-search.
References m_completeSourceCount, m_sourceCount, and SetDownloadStatus().
CSearchFile::~CSearchFile () [virtual]
Frees all children owned by this file.
Member Function Documentation
void CSearchFile::AddChild (CSearchFile * file)
Adds the given file as a child of this file.
Note that a file can either be a parent _or_ a child, but not both. Also note that it is only legal to add children whose filesize and filehash matches the parent's. AddChild takes ownership of the file.
References m_children, and m_parent.
Referenced by CSearchList::AddToList(), and CSearchFile().
const CSearchResultList& CSearchFile::GetChildren () const [inline]
Returns the list of children belonging to this file.
References m_children.
Referenced by CSearchListCtrl::AddResult(), and CSearchListCtrl::ShowChildren().
uint32 CSearchFile::GetCompleteSourceCount () const [inline]
Returns the number of sources that have the entire file.
References m_completeSourceCount.
Referenced by CSearchListCtrl::AddResult(), CSearchListCtrl::SortProc(), and CSearchListCtrl::UpdateResult().
enum DownloadStatus CSearchFile::GetDownloadStatus () const [inline]
Returns the download status.
References m_downloadStatus.
Referenced by CSearchListCtrl::IsFiltered(), and CSearchListCtrl::UpdateItemColor().
CSearchFile* CSearchFile::GetParent () const [inline]
Returns the parent of this file.
References m_parent.
Referenced by CSearchListCtrl::AddResult(), CSearchListCtrl::OnDrawItem(), and CSearchListCtrl::SortProc().
wxUIntPtr CSearchFile::GetSearchID () const [inline]
Returns the ID of the search, used to select the right list when displaying.
References m_searchID.
Referenced by CSearchListCtrl::AddResult(), CSearchDlg::AddResult(), CSearchList::AddToList(), and CSearchDlg::UpdateResult().
uint32 CSearchFile::GetSourceCount () const [inline]
Returns the total number of sources.
References m_sourceCount.
Referenced by CSearchListCtrl::AddResult(), CSearchListCtrl::SortProc(), CSearchListCtrl::UpdateItemColor(), UpdateParent(), and CSearchListCtrl::UpdateResult().
bool CSearchFile::HasChildren () const [inline]
Returns true if this item has children.
References m_children.
Referenced by CSearchListCtrl::AddResult(), CSearchListCtrl::OnDrawItem(), and CSearchListCtrl::OnItemActivated().
bool CSearchFile::IsKademlia () const [inline]
Returns true if the result is from a Kademlia search.
References m_kademlia.
void CSearchFile::MergeResults (const CSearchFile & other)
Merges the two results into one.
Merges the other result into this one, updating various informations.
Parameters:
other The file to be merged into this.
References m_completeSourceCount, m_kademlia, m_kadPublishInfo, and m_sourceCount.
void CSearchFile::SetDownloadStatus (enum DownloadStatus s) [inline]
Set download status directly.
References m_downloadStatus.
void CSearchFile::SetDownloadStatus ()
Set download status according to the global lists of knownfile, partfiles, canceledfiles.
References m_children, and m_downloadStatus.
Referenced by CSearchFile().
void CSearchFile::SetShowChildren (bool show) [inline]
Enable/Disable displaying of children (set in CSearchListCtrl).
References m_showChildren.
Referenced by CSearchListCtrl::ShowChildren().
bool CSearchFile::ShowChildren () const [inline]
Returns true if children should be displayed.
References m_showChildren.
Referenced by CSearchListCtrl::AddResult(), CSearchListCtrl::OnDrawItem(), CSearchListCtrl::OnItemActivated(), and CSearchListCtrl::SetSorting().
void CSearchFile::UpdateParent () [private]
Updates a parent file so that it shows various common traits.
Currently, the most common filename is selected, and an average of fileratings is set, based on files that have a rating only.
References GetSourceCount(), m_children, m_completeSourceCount, m_kademlia, m_kadPublishInfo, m_parent, and m_sourceCount.
The documentation for this class was generated from the following files:
src/SearchFile.h
src/amule-remote-gui.cpp
src/SearchFile.cpp