aMule: CFileLock Class Reference
CFileLock Class Reference
This class provides an easy way to lock non-critical files used by multiple applications.
#include <FileLock.h>
Public Member Functions
CFileLock (const std::string &file)
~CFileLock ()
Private Member Functions
CFileLock (const CFileLock &)
CFileLock & operator= (const CFileLock &)
bool SetLock (bool doLock)
Private Attributes
int m_fd
bool m_ok
Detailed Description
This class provides an easy way to lock non-critical files used by multiple applications.
However, since the implementation relies on fcntl, it may not work on all filesystems (NFS) and thus locking is not certain.
Currently, this lock holds an exclusive lock on the file in question. It is assumed that the file will be read/written by all users.
Constructor & Destructor Documentation
CFileLock::CFileLock (const std::string & file) [inline]
Locks the lock-file for the specified file.
The lock-file is a file named file + "_lock", and will be created if it does not already exist. This file is not removed afterwards.
References m_ok, and SetLock().
CFileLock::~CFileLock () [inline]
Releases the lock, if any is held.
References m_fd, m_ok, and SetLock().
Member Function Documentation
bool CFileLock::SetLock (bool doLock) [inline, private]
Locks or unlocks the lock-file, returning true on success.
References m_fd.
Referenced by CFileLock(), and ~CFileLock().
The documentation for this class was generated from the following file:
src/FileLock.h