aMule: CMuleNotebook Class Reference
CMuleNotebook Class Reference
This is an NoteBook control which adds additional features above what is provided by the wxNoteBook widget.
#include <MuleNotebook.h>
Public Member Functions
CMuleNotebook (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxString &name=wxT("notebook"))
virtual ~CMuleNotebook ()
virtual bool DeletePage (int nPage)
virtual bool DeleteAllPages ()
void EnablePopup (bool enable)
void SetPopupHandler (wxWindow *widget)
Protected Member Functions
void OnMouseLeftRelease (wxMouseEvent &event)
void OnMouseMotion (wxMouseEvent &event)
void OnRMButton (wxMouseEvent &event)
void OnPopupClose (wxCommandEvent &evt)
void OnPopupCloseAll (wxCommandEvent &evt)
void OnPopupCloseOthers (wxCommandEvent &evt)
Protected Attributes
bool m_popup_enable
wxWindow * m_popup_widget
Detailed Description
This is an NoteBook control which adds additional features above what is provided by the wxNoteBook widget.
Currently it includes:
Use of images on the tabs for closing the pages.
A popup-menu for closing one or more pages.
Events triggered when pages are closed.
Constructor & Destructor Documentation
CMuleNotebook::CMuleNotebook (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0, const wxString & name = wxT("notebook"))
Constructor.
See also:
wxNotebook::wxNotebook
Member Function Documentation
bool CMuleNotebook::DeletePage (int nPage) [virtual]
Deletes the page and triggers an event.
Parameters:
nPage The page to be removed.
Referenced by DeleteAllPages(), OnMouseLeftRelease(), OnPopupClose(), CChatWnd::OnPopupClose(), OnPopupCloseOthers(), and CChatWnd::OnPopupCloseOthers().
void CMuleNotebook::EnablePopup (bool enable)
Enables or disables the displaying of a popup-menu.
Parameters:
enabled The new setting.
References m_popup_enable.
void CMuleNotebook::SetPopupHandler (wxWindow * widget)
Sets an external widget to handle the popup-event.
Parameters:
widget The widget which would recieve the event or NULL to disable.
Setting the handler to a non-NULL pointer means that upon right-clicks, a right click event will be sent to that widget, so that it can create a popup-menu. The coordinates will be fixed to fit onto the specified widget, so no mapping is needed.
References m_popup_widget.
The documentation for this class was generated from the following files:
src/MuleNotebook.h
src/MuleNotebook.cpp