aMule: CECTag Class Reference
CECTag Class Reference
High level EC packet TAGs handler class.
#include <ECTag.h>
Public Types
typedef TagList::const_iterator const_iterator
Public Member Functions
CECTag (ec_tagname_t name, unsigned int length, const void *data)
CECTag (ec_tagname_t name, unsigned int length, void **dataptr)
CECTag (ec_tagname_t name, bool data)
CECTag (ec_tagname_t name, uint8_t data)
CECTag (ec_tagname_t name, uint16_t data)
CECTag (ec_tagname_t name, uint32_t data)
CECTag (ec_tagname_t name, uint64_t data)
CECTag (ec_tagname_t name, double data)
CECTag (ec_tagname_t name, const std::string &data)
CECTag (ec_tagname_t name, const EC_IPv4_t &data)
CECTag (ec_tagname_t name, const CMD4Hash &data)
CECTag (ec_tagname_t name, const char *data)
CECTag ()
CECTag (const CECTag &tag)
~CECTag (void)
CECTag & operator= (const CECTag &rhs)
bool operator== (const CECTag &tag) const
bool operator!= (const CECTag &tag) const
bool AddTag (const CECTag &tag, CValueMap *valuemap=NULL)
void AddTag (ec_tagname_t name, uint64_t data, CValueMap *valuemap=NULL)
void AddTag (ec_tagname_t name, const CMD4Hash &data, CValueMap *valuemap)
const CECTag * GetFirstTagSafe () const
const CECTag * GetTagByName (ec_tagname_t name) const
CECTag * GetTagByName (ec_tagname_t name)
const CECTag * GetTagByNameSafe (ec_tagname_t name) const
size_t GetTagCount () const
bool HasChildTags () const
const void * GetTagData () const
uint16_t GetTagDataLen () const
uint32_t GetTagLen () const
ec_tagname_t GetTagName () const
uint64_t GetInt () const
bool IsInt () const
double GetDoubleData () const
std::string GetStringDataSTL () const
bool IsString () const
EC_IPv4_t GetIPv4Data () const
CMD4Hash GetMD4Data () const
void DebugPrint (int level, bool print_empty) const
void swap (CECTag &t)
bool AssignIfExist (ec_tagname_t tagname, bool *target) const
uint8_t AssignIfExist (ec_tagname_t tagname, uint8_t *target) const
uint16_t AssignIfExist (ec_tagname_t tagname, uint16_t *target) const
uint32_t AssignIfExist (ec_tagname_t tagname, uint32_t *target) const
uint64_t AssignIfExist (ec_tagname_t tagname, uint64_t *target) const
time_t AssignIfExist (ec_tagname_t tagname, time_t *target) const
double AssignIfExist (ec_tagname_t tagname, double *target) const
float AssignIfExist (ec_tagname_t tagname, float *target) const
CMD4Hash AssignIfExist (ec_tagname_t tagname, CMD4Hash *target) const
std::string AssignIfExist (ec_tagname_t tagname, std::string *target) const
bool AssignIfExist (ec_tagname_t tagname, bool &target) const
bool AssignIfExist (ec_tagname_t tagname, uint8_t &target) const
bool AssignIfExist (ec_tagname_t tagname, uint16_t &target) const
bool AssignIfExist (ec_tagname_t tagname, uint32_t &target) const
bool AssignIfExist (ec_tagname_t tagname, uint64_t &target) const
bool AssignIfExist (ec_tagname_t tagname, time_t &target) const
bool AssignIfExist (ec_tagname_t tagname, double &target) const
bool AssignIfExist (ec_tagname_t tagname, float &target) const
bool AssignIfExist (ec_tagname_t tagname, CMD4Hash &target) const
bool AssignIfExist (ec_tagname_t tagname, std::string &target) const
const_iterator begin () const
const_iterator end () const
Protected Member Functions
uint8_t GetType () const
bool ReadFromSocket (CECSocket &socket)
bool WriteTag (CECSocket &socket) const
bool ReadChildren (CECSocket &socket)
bool WriteChildren (CECSocket &socket) const
Private Types
typedef std::list< CECTag > TagList
Private Member Functions
void InitInt (uint64_t data)
void NewData ()
void ConstructStringTag (ec_tagname_t name, const std::string &data)
Private Attributes
ec_tagname_t m_tagName
ec_tagtype_t m_dataType
ec_taglen_t m_dataLen
char * m_tagData
TagList m_tagList
Static Private Attributes
static const CECTag s_theNullTag
Detailed Description
High level EC packet TAGs handler class.
Constructor & Destructor Documentation
CECTag::CECTag (ec_tagname_t name, unsigned int length, const void * data)
Creates a new CECTag instance from the given data.
Parameters:
name TAG name
length length of data buffer
data TAG data
CECTag::CECTag (ec_tagname_t name, unsigned int length, void ** dataptr)
Creates a new CECTag instance for custom data.
Parameters:
name TAG name
length length of data buffer that will be alloc'ed
dataptr pointer to a void pointer which will be assigned the internal TAG data buffer
Note:
TAG data buffer has to be filled with valid data after the ctor
CECTag::CECTag (ec_tagname_t name, bool data)
Creates a new CECTag instance, which contains an int value.
This takes care of endianness problems with numbers.
Parameters:
name TAG name.
data number.
See also:
GetInt()
CECTag::CECTag (ec_tagname_t name, double data)
Creates a new CECTag instance, which contains a double precision floating point number.
Parameters:
name TAG name
data double number
Note:
The actual data is converted to string representation, because we have not found yet an effective and safe way to transmit floating point numbers.
See also:
GetDoubleData()
CECTag::CECTag (ec_tagname_t name, const std::string & data)
Creates a new CECTag instance, which contains a string.
Parameters:
name TAG name
data wxString object, it's contents are converted to UTF-8.
See also:
GetStringDataSTL()
CECTag::CECTag (ec_tagname_t name, const EC_IPv4_t & data)
Creates a new CECTag instance, which contains an IPv4 address.
This function takes care of the endianness of the port number.
Parameters:
name TAG name
data The EC_IPv4_t class containing the IPv4 address.
See also:
GetIPv4Data()
CECTag::CECTag (ec_tagname_t name, const CMD4Hash & data)
Creates a new CECTag instance, which contains a MD4 hash.
This function takes care to store hash in network byte order.
Parameters:
name TAG name
data The CMD4Hash class containing the MD4 hash.
See also:
GetMD4Data()
References CMD4Hash::GetHash().
CECTag::CECTag ()
Creates a new null-valued CECTag instance.
See also:
s_theNullTag
GetTagByNameSafe
Referenced by CECPacket::CECPacket().
Member Function Documentation
bool CECTag::AddTag (const CECTag & tag, CValueMap * valuemap = NULL)
Add a child tag to this one.
The tag argument is reset to an empty tag.
Be very careful that this method swallows the content of tag, leaving tag empty. Thus, the following code won't work as expected:
 {
    CECPacket *p = new CECPacket(whatever);
    CECTag *t1 = new CECTag(whatever);
    CECTag *t2 = new CECTag(whatever);
    p->AddTag(*t1);
    t1->AddTag(*t2);    // t2 won't be part of p !!!
 }
To get the desired results, the above should be replaced with something like:
 {
    CECPacket *p = new CECPacket(whatever);
    CECTag *t1 = new CECTag(whatever);
    CECTag *t2 = new CECTag(whatever);
    t1->AddTag(*t2);
    delete t2;  // we can safely delete the now empty t2 here, because t1 holds its content
    p->AddTag(*t1);
    delete t1;  // now p holds the content of both t1 and t2
 }
Then why copying? The answer is to enable simplifying the code like this:
 {
    CECPacket *p = new CECPacket(whatever);
    CECTag t1(whatever);
    t1.AddTag(CECTag(whatever));    // t2 is now created on-the-fly
    p->AddTag(t1);  // now p holds a copy of both t1 and t2
 }
Parameters:
tag a CECTag class instance to add.
Returns:
true if tag was really added, false when it was omitted through valuemap.
Referenced by CStatTreeItemTotalClients::AddECValues(), CStatTreeItemMaxConnLimitReached::AddECValues(), CStatTreeItemReconnects::AddECValues(), CStatTreeItemRatio::AddECValues(), CStatTreeItemAverageSpeed::AddECValues(), CStatTreeItemAverage::AddECValues(), CStatTreeItemTimer::AddECValues(), CStatTreeItemPacketTotals::AddECValues(), CStatTreeItemPackets::AddECValues(), CStatTreeItemCounterMax::AddECValues(), CStatTreeItemUlDlCounter::AddECValues(), CStatTreeItemCounterTmpl< _Tp >::AddECValues(), CStatTreeItemSimple::AddECValues(), CStatTreeItemPeakConnections::AddECValues(), CStatTreeItemRateCounter::AddECValues(), CamuleRemoteGuiApp::BootstrapKad(), CECPacket::CECPacket(), CStatTreeItemBase::CreateECTag(), UpdatableItemsContainer< SearchFile, CEC_SearchFile_Tag, uint32 >::ProcessUpdate(), and CamuleRemoteGuiApp::UpdateNotesDat().
double CECTag::GetDoubleData (void) const
Returns a double value.
Note:
The returned value is what we get by converting the string form of the number to a double.
Returns:
The double value of the tag.
See also:
CECTag(ec_tagname_t, double)
uint64 CECTag::GetInt (void) const
Returns the uint8 data of the tag.
Returns the uint64 data of the tag.
Returns the uint32 data of the tag.
Returns the uint16 data of the tag.
This function takes care of the endianness problems with numbers.
Returns:
The uint8 data of the tag.
See also:
CECTag(ec_tagname_t, uint8)
This function takes care of the endianness problems with numbers.
Returns:
The uint16 data of the tag.
See also:
CECTag(ec_tagname_t, uint16)
This function takes care of the endianness problems with numbers.
Returns:
The uint32 data of the tag.
See also:
CECTag(ec_tagname_t, uint32)
This function takes care of the endianness problems with numbers.
Returns:
The uint64 data of the tag.
See also:
CECTag(ec_tagname_t, uint64)
Referenced by ServersInfo::ReQuery().
EC_IPv4_t CECTag::GetIPv4Data () const
Returns an EC_IPv4_t class.
This function takes care of the endianness of the port number.
Returns:
EC_IPv4_t class.
See also:
CECTag(ec_tagname_t, const EC_IPv4_t&)
Referenced by ServersInfo::ReQuery().
CMD4Hash CECTag::GetMD4Data (void) const
Returns a CMD4Hash class.
This function takes care of converting from MSB to LSB as necessary.
Returns:
CMD4Hash class.
See also:
CECTag(ec_tagname_t, const CMD4Hash&)
Reimplemented in CEC_SharedFile_Tag, CEC_UpDownClient_Tag, and CEC_SearchFile_Tag.
CECTag * CECTag::GetTagByName (ec_tagname_t name)
Finds the (first) child tag with given name.
Parameters:
name TAG name to look for.
Returns:
the tag found, or NULL.
const CECTag * CECTag::GetTagByName (ec_tagname_t name) const
Finds the (first) child tag with given name.
Parameters:
name TAG name to look for.
Returns:
the tag found, or NULL.
Referenced by GetTagByNameSafe().
const CECTag * CECTag::GetTagByNameSafe (ec_tagname_t name) const
Finds the (first) child tag with given name.
Parameters:
name TAG name to look for.
Returns:
the tag found, or a special null-valued tag otherwise.
See also:
s_theNullTag
References GetTagByName(), and s_theNullTag.
Referenced by ServersInfo::ReQuery().
size_t CECTag::GetTagCount (void) const [inline]
Returns the number of child tags.
Returns:
The number of child tags.
const void * CECTag::GetTagData (void) const [inline]
Returns a pointer to the TAG DATA.
Returns:
A pointer to the TAG DATA. (As specified with the data field of the constructor.)
uint16 CECTag::GetTagDataLen (void) const [inline]
Returns the length of the data buffer.
Returns:
The length of the data buffer.
uint32 CECTag::GetTagLen (void) const
Query TAG length that is suitable for the TAGLEN field (i.e. without it's own header size).
Returns:
Tag length, containing its childs' length.
Referenced by CECPacket::GetPacketLength().
ec_tagname_t CECTag::GetTagName (void) const [inline]
Returns TAGNAME.
Returns:
The name of the tag.
CECTag & CECTag::operator= (const CECTag & tag)
Copy assignment operator.
std::vector uses this, but the compiler-supplied version wouldn't properly handle m_dynamic and m_tagData. This wouldn't be necessary if m_tagData was a smart pointer (Hi, Kry!).
The documentation for this class was generated from the following files:
src/libs/ec/cpp/ECTag.h
src/libs/ec/cpp/ECTag.cpp