aMule: CBarShader Class Reference
CBarShader Class Reference
The barshader class is responsible for drawing the chunk-based progress bars used in aMule.
#include <BarShader.h>
Public Member Functions
CBarShader (unsigned height=1, unsigned width=1)
~CBarShader ()
void SetWidth (int width)
void SetHeight (unsigned height)
void Set3dDepth (unsigned depth)
void SetFileSize (uint64 fileSize)
void FillRange (uint64 start, uint64 end, const CMuleColour &colour)
void Fill (const CMuleColour &colour)
void Draw (wxDC *dc, int iLeft, int iTop, bool bFlat)
Private Member Functions
void BuildModifiers ()
Private Attributes
unsigned m_Width
unsigned m_Height
uint64 m_FileSize
double * m_Modifiers
uint16 m_used3dlevel
std::vector< CMuleColour > m_Content
Detailed Description
The barshader class is responsible for drawing the chunk-based progress bars used in aMule.
CBarShader represents the chunks of a file through the use of spans, which cover a range in the file with a certain color. New spans can be added on the fly and old spans are automatically removed, resized or merged when necessary.
CBarShader will try to minimize the number of spans when possible.
Constructor & Destructor Documentation
CBarShader::CBarShader (unsigned height = 1, unsigned width = 1)
Constructor.
Parameters:
height The height of the area upon which the span is drawn.
width The width of the area upon which the span is drawn.
Member Function Documentation
void CBarShader::Draw (wxDC * dc, int iLeft, int iTop, bool bFlat)
Draws the bar on the specifed wxDC.
Parameters:
dc The wxDC upon which the bar should be drawn.
iLeft The left position from where to start drawing.
iTop The top position from where to start drawing.
bFlat 3D effect is not applied if this is true.
This functions draws the bar with the height and width specified through either the contructor or with SetWidth() and SetHeight().
References BuildModifiers(), m_Height, m_Modifiers, and m_Width.
Referenced by CSharedFilesCtrl::DrawAvailabilityBar(), CDownloadListCtrl::DrawFileStatusBar(), CGenericClientListCtrl::DrawSourceStatusBar(), and CGenericClientListCtrl::DrawStatusBar().
void CBarShader::Fill (const CMuleColour & colour) [inline]
Fill the entire bar with a span of the specified color.
Parameters:
colour The colour of the new span.
References m_Width.
Referenced by CDownloadListCtrl::DrawFileStatusBar(), and SetWidth().
void CBarShader::FillRange (uint64 start, uint64 end, const CMuleColour & colour)
Fills in a range with a certain color.
Parameters:
start The starting position of the new span.
end The ending position of the new span. Must be larger than start.
colour The colour of the new span.
Calling this function fill the specified range with the specified color. Any spans completly or partially covered by the new span are either removed or resized. If the value of end is larger than the current filesize, the filesize is increased to the value of end.
References m_FileSize, and m_Width.
Referenced by CSharedFilesCtrl::DrawAvailabilityBar(), CDownloadListCtrl::DrawFileStatusBar(), CGenericClientListCtrl::DrawSourceStatusBar(), and CGenericClientListCtrl::DrawStatusBar().
void CBarShader::Set3dDepth (unsigned depth)
Sets the 3D-depth of the bar.
Parameters:
depth A value in the range from 1 to 5.
References m_Modifiers, and m_used3dlevel.
Referenced by CSharedFilesCtrl::DrawAvailabilityBar(), CDownloadListCtrl::DrawFileStatusBar(), CGenericClientListCtrl::DrawSourceStatusBar(), and CGenericClientListCtrl::DrawStatusBar().
void CBarShader::SetFileSize (uint64 fileSize) [inline]
Sets a new filesize.
Parameters:
fileSize The new filesize.
Calling this function sets a new filesize, which is the virtual length of the bar. This function must be called before any filling.
References m_FileSize.
Referenced by CSharedFilesCtrl::DrawAvailabilityBar(), CDownloadListCtrl::DrawFileStatusBar(), CGenericClientListCtrl::DrawSourceStatusBar(), and CGenericClientListCtrl::DrawStatusBar().
void CBarShader::SetHeight (unsigned height)
Sets the height of the drawn bar.
Parameters:
height The new height.
Changes the height of the bar, used when it is drawn.
References m_Height, and m_Modifiers.
Referenced by CSharedFilesCtrl::DrawAvailabilityBar(), CDownloadListCtrl::DrawFileStatusBar(), CGenericClientListCtrl::DrawSourceStatusBar(), and CGenericClientListCtrl::DrawStatusBar().
void CBarShader::SetWidth (int width)
Sets the width of the drawn bar.
Parameters:
width The new width.
Setting this sets the width the bar which is used when it is drawn and resets the pixel buffer to the fill color.
References Fill(), and m_Width.
Referenced by CSharedFilesCtrl::DrawAvailabilityBar(), CDownloadListCtrl::DrawFileStatusBar(), CGenericClientListCtrl::DrawSourceStatusBar(), and CGenericClientListCtrl::DrawStatusBar().
The documentation for this class was generated from the following files:
src/BarShader.h
src/BarShader.cpp