aMule: CFormat Class Reference
CFormat Class Reference
This class offers a typesafe alternative to wxString::Format.
#include <Format.h>
Classes
struct FormatSpecifier
Structure to hold a format specifier.
Public Member Functions
CFormat (const wxChar *str)
CFormat (const wxString &str)
template<typename _Tp >
CFormat & operator% (_Tp value)
template<typename _Tp >
CFormat & operator% (_Tp *value)
CFormat & operator% (const wxString &value)
CFormat & operator% (const CFormat &value)
wxString GetString () const
operator wxString () const
template<>
void ProcessArgument (FormatList::iterator, const wxString &)
template<>
void ProcessArgument (FormatList::iterator, unsigned long long)
template<>
void ProcessArgument (FormatList::iterator it, double value)
template<>
void ProcessArgument (FormatList::iterator it, wxChar value)
template<>
void ProcessArgument (FormatList::iterator it, signed long long value)
template<>
void ProcessArgument (FormatList::iterator it, void *value)
template<>
CFormat & operator% (char value)
template<>
CFormat & operator% (signed char value)
template<>
CFormat & operator% (unsigned char value)
template<>
CFormat & operator% (bool value)
template<>
CFormat & operator% (signed short value)
template<>
CFormat & operator% (unsigned short value)
template<>
CFormat & operator% (signed int value)
template<>
CFormat & operator% (unsigned int value)
template<>
CFormat & operator% (signed long value)
template<>
CFormat & operator% (unsigned long value)
template<>
CFormat & operator% (float value)
template<>
CFormat & operator% (const wxChar *value)
template<>
CFormat & operator% (CPath value)
Private Types
typedef std::list
< FormatSpecifier > FormatList
Private Member Functions
void Init (const wxString &str)
wxString GetModifiers (FormatList::const_iterator it) const
template<typename _Tp >
void ProcessArgument (FormatList::iterator it, _Tp value)
Private Attributes
FormatList m_formats
unsigned m_argIndex
wxString m_formatString
Detailed Description
This class offers a typesafe alternative to wxString::Format.
CFormat has been implemented against the description of printf found in the "man 3 printf" manual page.
CFormat lacks the following capabilities:
The "*" width-modifier, because only one argument is fed at a time.
The "n" type, just unsafe and won't be implemented.
The "C" and "S" types, which are considered obsolete.
The Long Double type, which is extremly slow and shouldn't be used.
Support for the C99 a, A conversions and the non-standard ', I flags depend on the underlying C library. Do not use them.
Supports the glibc-specific m conversion on all platforms, where there's a way to get the error description. If the underlying C library has a thread-safe way to get the error description, then this conversion is thread-safe, too.
Deviations from printf(3):
CFormat tries hard to format the passed POD-type according to the conversion type. Basic type conversions may take place to accomplish this goal. This results in formats accepting a variety of types, namely:
c, i, d, u, o, x, X accept wxChar and all integer types,
a, A, e, E, f, F, g, G accept wxChar, integer and floating-point types,
p accepts only pointers,
s accepts all the above mentioned types in addition to wxString and wxChar* types.
The only exception from this rule is integer (d, i, u) conversion. It will always use the correct conversion (i or u) depending on the signedness of the passed argument.
's' conversions are inspired by the "we're converting to string, anyway" mood. Thus they use a 'default' conversion for each accepted type: 'c' for wxChar, 'i' and 'u' for signed and unsigned integers, respectively, 'g' for floating-point numbers and 'p' for pointers.
Other relaxations / differences from printf(3):
Length modifiers are read and validated, but always ignored.
As a consequence, invalid combinations of length modifiers and conversion types are silently ignored (i.e. for example the invalid '%qs' format-specifier is silently treated as '%s').
'p' conversion ignores all modifiers except the argument index reference.
You can mix positional and indexed argument references. (You actually can't, because msgfmt will treat this as an error.)
With indexed argument references we allow to leave gaps in the indices.
Constructor & Destructor Documentation
CFormat::CFormat (const wxChar * str) [inline]
Constructor.
Parameters:
str The format-string to be used.
References Init().
CFormat::CFormat (const wxString & str) [inline]
Constructor.
This form is required to construct from a plain char * with wx 2.9
Parameters:
str The format-string to be used.
References Init().
Member Function Documentation
void CFormat::Init (const wxString & str) [private]
Initialize internal structures.
Initializes member variables and parses the given format string.
References CFormat::FormatSpecifier::endPos, m_argIndex, m_formats, m_formatString, CFormat::FormatSpecifier::result, and CFormat::FormatSpecifier::startPos.
Referenced by CFormat().
template<typename _Tp > CFormat & CFormat::operator% (_Tp value) [inline]
Feeds a value into the format-string.
Passing a type that isn't compatible with the current format field results in the field being skipped, and an exception raised.
Passing any type to a CFormat with no free fields results in the argument being ignored.
Specialize this member template to teach CFormat how to handle other types.
References m_argIndex, and m_formats.
The documentation for this class was generated from the following files:
src/libs/common/Format.h
src/libs/common/Format.cpp
src/libs/common/Path.h