aMule: CThreadScheduler Class Reference
CThreadScheduler Class Reference
This class mananges scheduling of background tasks.
#include <ThreadScheduler.h>
Static Public Member Functions
static void Start ()
static void Terminate ()
static bool AddTask (CThreadTask *task, bool overwrite=false)
Private Types
typedef std::pair< CThreadTask
*, uint32 > CEntryPair
typedef std::map< wxString,
CThreadTask * > CDescMap
typedef std::map< wxString,
CDescMap > CTypeMap
Private Member Functions
size_t GetTaskCount () const
bool DoAddTask (CThreadTask *task, bool overwrite)
void CreateSchedulerThread ()
void * Entry ()
Private Attributes
std::deque< CEntryPair > m_tasks
bool m_tasksDirty
CTypeMap m_taskDescs
CMuleThread * m_thread
CThreadTask * m_currentTask
Friends
class CTaskThread
struct CTaskSorter
Detailed Description
This class mananges scheduling of background tasks.
Currently it is assumed that all tasks are IO intensive, so that only a single task is allowed to proceed at any one time. All threads are run in lowest priority mode.
Tasks are sorted by priority (see ETaskPriority) and age.
Note that the scheduler starts in suspended mode, in which tasks are queued but not executed. Call Start() to begin execution of the tasks.
Member Function Documentation
bool CThreadScheduler::AddTask (CThreadTask * task, bool overwrite = false) [static]
Adds a new task to the queue, returning true if the task was queued.
Before the task is queued, it is checked against the existing tasks based on type and description. If an matching task already exists, this task-object is discarded. The task is also discarded if the scheduler has been terminated. If 'overwrite' is true, any existing duplicate task is dropped, and if already running, terminated.
Note: This function takes ownership of the task.
See also:
Start
Terminate
References DoAddTask(), and CThreadTask::GetDesc().
Referenced by CSharedFileList::CheckAICHHashes(), CHashingTask::OnLastTask(), and CIPFilter::Reload().
void CThreadScheduler::CreateSchedulerThread () [private]
Creates the actual scheduler thread if none exist.
References m_tasks, m_thread, and CMuleThread::Stop().
Referenced by DoAddTask(), and Start().
bool CThreadScheduler::DoAddTask (CThreadTask * task, bool overwrite) [private]
Tries to add the given task to the queue, returning true on success.
References CreateSchedulerThread(), CThreadTask::GetDesc(), CThreadTask::GetType(), CThreadTask::m_abort, m_currentTask, m_taskDescs, m_tasks, and m_tasksDirty.
Referenced by AddTask().
void * CThreadScheduler::Entry () [private]
Entry function called via internal thread-object.
References CScopedPtr< TYPE >::get(), m_currentTask, m_taskDescs, m_tasks, m_tasksDirty, m_thread, CScopedPtr< TYPE >::reset(), and CMuleThread::TestDestroy().
Referenced by CTaskThread::Entry().
size_t CThreadScheduler::GetTaskCount () const [private]
Returns the number of tasks on the queue.
References m_tasks.
void CThreadScheduler::Start () [static]
Starts execution of queued tasks.
References CreateSchedulerThread().
void CThreadScheduler::Terminate () [static]
Terminates task execution and frees the scheduler object.
Tasks added after this are discarded.
The documentation for this class was generated from the following files:
src/ThreadScheduler.h
src/ThreadScheduler.cpp