aMule: CPath Class Reference
CPath Class Reference
This class wraps a path/filename, serving a purpose much like wxFileName.
#include <Path.h>
Public Types
enum EAccess { exists, readable, writable, readwritable = readable | writable }
Public Member Functions
CPath ()
CPath (const wxString &path)
CPath (const CPath &other)
CPath & operator= (const CPath &other)
bool operator< (const CPath &other) const
bool operator== (const CPath &other) const
bool operator!= (const CPath &other) const
bool IsOk () const
bool FileExists () const
bool DirExists () const
bool IsDir (EAccess mode) const
bool IsFile (EAccess mode) const
wxString GetRaw () const
wxString GetPrintable () const
wxString GetExt () const
CPath GetPath () const
CPath GetFullName () const
sint64 GetFileSize () const
bool IsSameDir (const CPath &other) const
CPath JoinPaths (const CPath &other) const
CPath Cleanup (bool keepSpaces=true, bool isFAT32=false) const
CPath AddPostfix (const wxString &postfix) const
CPath AppendExt (const wxString &ext) const
CPath RemoveExt () const
CPath RemoveAllExt () const
bool StartsWith (const CPath &other) const
wxString TruncatePath (size_t length, bool isFilePath=false) const
Static Public Member Functions
static CPath FromUniv (const wxString &path)
static wxString ToUniv (const CPath &path)
static bool RenameFile (const CPath &src, const CPath &dst, bool overwrite=false)
static bool CloneFile (const CPath &src, const CPath &dst, bool overwrite=false)
static bool BackupFile (const CPath &src, const wxString &appendix)
static bool RemoveFile (const CPath &file)
static bool RemoveDir (const CPath &file)
static bool MakeDir (const CPath &file)
static bool FileExists (const wxString &file)
static bool DirExists (const wxString &path)
static sint64 GetFileSize (const wxString &file)
static time_t GetModificationTime (const CPath &file)
static sint64 GetFreeSpaceAt (const CPath &path)
Private Attributes
wxString m_printable
wxString m_filesystem
Friends
int CmpAny (const CPath &ArgA, const CPath &ArgB)
Detailed Description
This class wraps a path/filename, serving a purpose much like wxFileName.
But in addition CPath serves to enable the handling of "broken" filenames, allowing these to be printed in a meaningful manner, while still allowing access to the actual files in the filesystem.
This class is thread-safe, in that the class is read-only, and any function that returns wxStrings or CPath objects, ensure that an entirely new wxString object is created to circumvent the thread-unsafe reference counting of that class.
This class, and its static functions should be used in preference of wxFileName, for the above reason, and so that cross-platform issues can be worked around in a single place.
Member Enumeration Documentation
enum CPath::EAccess
Enumerator:
exists
Only check of the file or dir exists.
readable
If set, checks if a file is readable, or if a dir can be accessed.
writable
If set, checks if a file or directory can be written to,.
readwritable
Combination of the two checks above.
Constructor & Destructor Documentation
CPath::CPath ()
Default constructor.
Referenced by BackupFile(), DirExists(), FileExists(), FromUniv(), GetFileSize(), and JoinPaths().
CPath::CPath (const wxString & path) [explicit]
Constuctor.
References m_filesystem, and m_printable.
CPath::CPath (const CPath & other)
Copy constructor.
Creates a deep-copy of the passed object.
Member Function Documentation
CPath CPath::AddPostfix (const wxString & postfix) const
Returns a CPath with a postfix before the file-extension.
Must be ASCII.
References m_filesystem, and m_printable.
Referenced by CCompletionTask::Entry().
CPath CPath::AppendExt (const wxString & ext) const
Returns a CPath object with the extension appended.
Empty strings are ignored.
References m_filesystem, and m_printable.
Referenced by CCompletionTask::Entry(), and CFile::Open().
CPath CPath::Cleanup (bool keepSpaces = true, bool isFAT32 = false) const
Returns a CPath with invalid chars removed, and spaces escaped if specified.
References m_filesystem, and m_printable.
Referenced by CCompletionTask::Entry().
bool CPath::CloneFile (const CPath & src, const CPath & dst, bool overwrite = false) [static]
Copies the file 'src' to the file 'dst', overwriting if specified.
The silly name is used to avoid conflicts with the define CopyFile, which is set on MSW.
References m_filesystem.
Referenced by BackupFile(), and CCompletionTask::Entry().
bool CPath::DirExists (const wxString & path) [static]
Returns true if the path exists, and is a directory.
References CPath().
bool CPath::DirExists () const
Returns true if the path exists and is a directory, false otherwise.
References m_filesystem.
Referenced by CCompletionTask::Entry(), and CCatDialog::OnBnClickedOk().
bool CPath::FileExists (const wxString & file) [static]
Returns true if the path exists, and is a file.
References CPath().
bool CPath::FileExists () const
Returns true if the path exists and is a file, false otherwise.
References m_filesystem.
Referenced by CAICHSyncTask::ConvertToKnown2ToKnown264(), CFile::Create(), CCompletionTask::Entry(), CAICHSyncTask::Entry(), GetFileSize(), CDownloadQueue::IsFileExisting(), CIPFilterTask::LoadFromFile(), and CFile::Open().
CPath CPath::FromUniv (const wxString & path) [static]
Creates a path from one saved in the 'universal' format.
These are to be used when the filenames/paths are saved to the local machine, and ensure that locale-changes does not affect our ability to find previously known files. This should not be used when sending filenames to other clients or (currently) the core/gui.
References CPath().
Referenced by Cfg_Path::LoadFromFile().
wxString CPath::GetExt () const
Returns the (raw) last extension, empty if none is found.
References m_filesystem.
Referenced by CSharedFilesCtrl::OnRightClick(), and CSearchListCtrl::SortProc().
sint64 CPath::GetFileSize (const wxString & file) [static]
Returns the size of the specified file, or wxInvalidOffset on failure.
References CPath().
sint64 CPath::GetFileSize () const
Returns the size of the specified file, or wxInvalidSize on failure.
References FileExists(), and m_filesystem.
sint64 CPath::GetFreeSpaceAt (const CPath & path) [static]
Returns the free diskspace at the specified path, or wxInvalidOffset on failure.
References m_filesystem.
Referenced by CDownloadQueue::CheckDiskspace(), and CAllocateFileTask::Entry().
CPath CPath::GetFullName () const
Returns the full filename, excluding the path.
References m_filesystem, and m_printable.
Referenced by CCompletionTask::Entry(), and CDownloadQueue::LoadMetFiles().
time_t CPath::GetModificationTime (const CPath & file) [static]
Returns the modification time the specified file, or (time_t)-1 on failure.
References m_filesystem.
Referenced by CHashingTask::Entry().
CPath CPath::GetPath () const
Returns the full path, exluding the filename.
References m_filesystem, and m_printable.
wxString CPath::GetPrintable () const
Returns the contents of the object in a form suitable for use in the UI.
References m_printable.
Referenced by CSearchListCtrl::AddResult(), CGenericClientListCtrl::DrawClientItem(), CSharedFileList::GetPublicSharedDirName(), CSearchListCtrl::IsFiltered(), CDownloadQueue::LoadMetFiles(), CSharedFilesCtrl::OnDrawItem(), CSharedFilesCtrl::OnRename(), TruncatePath(), and CSearchListCtrl::UpdateResult().
wxString CPath::GetRaw () const
Returns the contents of the object in a form suitable for use with wx system-calls.
References m_filesystem.
Referenced by CSharedFileList::GetPublicSharedDirName(), CIPFilterTask::LoadFromFile(), CFile::Open(), and Cfg_Path::TransferToWindow().
bool CPath::IsDir (EAccess mode) const
Returns if if the path is a dir, and the checks were positive.
References m_filesystem, readable, and writable.
Referenced by CSharedFileList::IsShared().
bool CPath::IsFile (EAccess mode) const
Returns if if the path is a dir, and the checks were positive.
References m_filesystem, readable, and writable.
bool CPath::IsOk () const
Returns true if the filename is valid, false otherwise.
References m_filesystem, and m_printable.
Referenced by CCompletionTask::CCompletionTask(), CGenericClientListCtrl::DrawClientItem(), CCompletionTask::Entry(), JoinPaths(), CDownloadQueue::LoadMetFiles(), CCatDialog::OnBnClickedOk(), CFile::Open(), and StartsWith().
bool CPath::IsSameDir (const CPath & other) const
Compares under the assumption that both objects are dirs, even if one or the other lacks a terminal directory-seperator.
However, an empty CPath object will not be considered equal to a path to the root.
References m_filesystem.
Referenced by CSharedFileList::IsShared().
CPath CPath::JoinPaths (const CPath & other) const
Returns a CPath created from joining the two objects.
References CPath(), IsOk(), m_filesystem, and m_printable.
Referenced by CCompletionTask::Entry(), CHashingTask::Entry(), CDownloadQueue::LoadMetFiles(), CSharedFilesCtrl::OnAddCollection(), and TruncatePath().
bool CPath::MakeDir (const CPath & file) [static]
Creates the specified directory, returning true on success.
References m_filesystem.
Referenced by CCatDialog::OnBnClickedOk().
bool CPath::operator!= (const CPath & other) const
Note that only exact matches are considered equal, see IsSameDir.
bool CPath::operator< (const CPath & other) const
Less-than operator.
References m_filesystem.
CPath & CPath::operator= (const CPath & other)
Assignment operator.
References m_filesystem, and m_printable.
bool CPath::operator== (const CPath & other) const
Note that only exact matches are considered equal, see IsSameDir.
References m_filesystem.
CPath CPath::RemoveAllExt () const
Returns a CPath object with all extensions removed.
References RemoveExt().
bool CPath::RemoveDir (const CPath & file) [static]
Deletes the specified directory, returning true on success.
References m_filesystem.
CPath CPath::RemoveExt () const
Returns a CPath with the (last, if multiple) extension removed.
References m_filesystem, and m_printable.
Referenced by CFile::Close(), CAllocateFileTask::Entry(), CCompletionTask::Entry(), and RemoveAllExt().
bool CPath::RemoveFile (const CPath & file) [static]
Deletes the specified file, returning true on success.
References m_filesystem.
Referenced by CCompletionTask::Entry().
bool CPath::RenameFile (const CPath & src, const CPath & dst, bool overwrite = false) [static]
Renames the file 'src' to the file 'dst', overwriting if specified.
Note that renaming cannot be done across volumes. For that CopyFile is required.
References m_filesystem.
Referenced by CFile::Close(), and CCompletionTask::Entry().
bool CPath::StartsWith (const CPath & other) const
Returns true if the the passed path makes up an prefix of this object.
References IsOk(), and m_filesystem.
wxString CPath::ToUniv (const CPath & path) [static]
Creates an 'universal' path from the specified CPath.
References m_filesystem.
Referenced by Cfg_Path::SaveToFile().
wxString CPath::TruncatePath (size_t length, bool isFilePath = false) const
Get truncated path.
Note:
This function truncates the name of the file, not the file itself.
Parameters:
length The truncated path should not exceed this length.
isFilePath Indicates whether the last part of the path (the file name) should be kept or not, if possible.
Returns:
The truncated path, at most length long.
References GetPrintable(), and JoinPaths().
Referenced by CClientDetailDialog::OnInitDialog().
Member Data Documentation
wxString CPath::m_filesystem [private]
Contains the "raw" filename, for use in system-calls, as well as in wxWidgets file functions.
Referenced by AddPostfix(), AppendExt(), BackupFile(), Cleanup(), CloneFile(), CPath(), DirExists(), FileExists(), GetExt(), GetFileSize(), GetFreeSpaceAt(), GetFullName(), GetModificationTime(), GetPath(), GetRaw(), IsDir(), IsFile(), IsOk(), IsSameDir(), JoinPaths(), MakeDir(), operator<(), operator=(), operator==(), RemoveDir(), RemoveExt(), RemoveFile(), RenameFile(), StartsWith(), and ToUniv().
The documentation for this class was generated from the following files:
src/libs/common/Path.h
src/libs/common/Path.cpp