aMule: CMuleListCtrl Class Reference
CMuleListCtrl Class Reference
Enhanced wxListCtrl provided custom-drawing among other things.
#include <MuleListCtrl.h>
Classes
class ColNameEntry
This class contains a column index, its default width and its name.
class MuleSortData
Public Types
enum MLOrder { SORT_DES = 0x1000, SORT_ALT = 0x2000 }
typedef std::vector< wxUIntPtr > ItemDataList
Public Member Functions
CMuleListCtrl (wxWindow *parent, wxWindowID winid=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxLC_ICON, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxT("mulelistctrl"))
virtual ~CMuleListCtrl ()
virtual void SaveSettings ()
virtual void LoadSettings ()
long GetInsertPos (wxUIntPtr data)
virtual void SortList ()
ItemDataList GetSelectedItems () const
void SetSortFunc (MuleListCtrlCompare func)
void ClearSelection ()
long InsertColumn (long col, const wxString &heading, int format=wxLIST_FORMAT_LEFT, int width=-1, const wxString &name=wxEmptyString)
void ClearAll ()
bool DeleteColumn (int col)
bool IsSorting () const
Static Public Attributes
static const unsigned COLUMN_MASK = 0xfff
static const unsigned SORTING_MASK = 0x3000
Protected Member Functions
virtual bool AltSortAllowed (unsigned column) const
virtual wxString GetTTSText (unsigned item) const
void SetTableName (const wxString &name)
virtual wxString GetOldColumnOrder () const
unsigned GetSortColumn () const
unsigned GetSortOrder () const
virtual void SetSorting (unsigned column, unsigned order)
bool IsItemSorted (long item)
void OnColumnRClick (wxListEvent &evt)
void OnColumnLClick (wxListEvent &evt)
void OnMenuSelected (wxCommandEvent &evt)
void OnMouseWheel (wxMouseEvent &event)
void OnChar (wxKeyEvent &evt)
void OnItemSelected (wxListEvent &evt)
void OnItemDeleted (wxListEvent &evt)
void OnAllItemsDeleted (wxListEvent &evt)
long CheckSelection (wxListEvent &event)
long CheckSelection (wxMouseEvent &event)
Private Types
typedef std::pair< unsigned,
unsigned > CColPair
typedef std::list< CColPair > CSortingList
typedef std::list< ColNameEntry > ColNameList
typedef std::vector< int > ColSizeVector
Private Member Functions
void ResetTTS ()
void SetColumnImage (unsigned col, int image)
int CompareItems (wxUIntPtr item1, wxUIntPtr item2)
const wxString & GetColumnName (int column) const
int GetColumnDefaultWidth (int column) const
int GetColumnIndex (const wxString &name) const
int GetNewColumnIndex (int oldindex) const
void ParseOldConfigEntries (const wxString &sortOrders, const wxString &columnWidths)
Static Private Member Functions
static int wxCALLBACK SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData)
Private Attributes
wxString m_name
MuleListCtrlCompare m_sort_func
wxString m_tts_text
unsigned m_tts_time
int m_tts_item
CSortingList m_sort_orders
ColNameList m_column_names
ColSizeVector m_column_sizes
bool m_isSorting
Detailed Description
Enhanced wxListCtrl provided custom-drawing among other things.
This class provides these features which the original wxListCtrl lacks:
Automatic sort arrows upon clicks on the column headers
Custom drawing of items.
Hiding of columns through auto-generated popup-menu.
Helper function for inserting items pre-sorted.
Loading and saving of column properties.
Selection of items by typing an initial part of the text (TTS).
Member Enumeration Documentation
enum CMuleListCtrl::MLOrder
The various ways in which a column can be sorted.
If SORT_DES is not set, sorting is taken to be ascending. If SORT_ALT is not set, sorting is taken to be normal.
Enumerator:
SORT_DES
If set, sorting is to be in descending order.
SORT_ALT
If sorting should use alternate method.
Is specified in with or without DEC.
Constructor & Destructor Documentation
CMuleListCtrl::CMuleListCtrl (wxWindow * parent, wxWindowID winid = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxLC_ICON, const wxValidator & validator = wxDefaultValidator, const wxString & name = wxT("mulelistctrl"))
Constructor.
See also:
wxGenericListCtrl::wxGenericListCtrl for documentation of parameters.
CMuleListCtrl::~CMuleListCtrl () [virtual]
Destructor.
If a name for the table has been specified with SetTableName, then column settings will be saved automatically.
References m_name, and SaveSettings().
Member Function Documentation
bool CMuleListCtrl::AltSortAllowed (unsigned column) const [protected, virtual]
Must be overwritten to enable alternate sorting.
Parameters:
The column being sorted.
Subclasses of CMuleListCtrl can allow alternative sorting of columns. This is done by overriding this function and returning true for the columns where alternative sorting is desired.
Reimplemented in CSearchListCtrl, and CSharedFilesCtrl.
Referenced by OnColumnLClick().
long CMuleListCtrl::CheckSelection (wxListEvent & event) [protected]
Check and fix selection state.
Parameters:
event The event which triggered the selection.
Returns:
The index of the item selected or -1 if none.
This function checks if the clicked item is selected. If not, then the item is selected and all other items are deselected.
References ClearSelection().
Referenced by CServerListCtrl::OnItemRightClicked(), CSharedFilesCtrl::OnRightClick(), and CSearchListCtrl::OnRightClick().
void CMuleListCtrl::ClearAll () [inline]
Clears all items and all columns.
Intercepted to clear column name list.
For more information see the wxWidgets documentation of wxListCtrl::ClearAll()
Reimplemented from MuleExtern::wxGenericListCtrl.
References m_column_names.
int CMuleListCtrl::CompareItems (wxUIntPtr item1, wxUIntPtr item2) [private]
Compares two items in the list, using the current sort sequence.
References m_sort_func, and m_sort_orders.
Referenced by GetInsertPos(), and IsItemSorted().
bool CMuleListCtrl::DeleteColumn (int col) [inline]
Delete one column from the list.
Not implemented yet, intercepted here just as a sanity check.
Reimplemented from MuleExtern::wxGenericListCtrl.
int CMuleListCtrl::GetColumnDefaultWidth (int column) const [private]
Get the column default width by index.
Parameters:
[in] column Index of the column whose name we're looking for.
Returns:
The column default width or wx default width if index is invalid (out of range), or the column name hasn't been set.
References m_column_names.
Referenced by OnMenuSelected().
int CMuleListCtrl::GetColumnIndex (const wxString & name) const [private]
Get column index by name.
Parameters:
[in] name Internal name of the colunm whose index is needed.
Returns:
The column index, or -1 in case the name was invalid.
References m_column_names.
Referenced by GetNewColumnIndex(), and LoadSettings().
const wxString & CMuleListCtrl::GetColumnName (int column) const [private]
Get the column name by index.
Parameters:
[in] column Index of the column whose name we're looking for.
Returns:
The column name or an empty string if index is invalid (out of range), or the column name hasn't been set.
References m_column_names.
Referenced by SaveSettings().
long CMuleListCtrl::GetInsertPos (wxUIntPtr data)
This function tries to locate the best place to insert an item.
Parameters:
The userdata of the new item.
This function does a binary type search to locate the best place to insert the new item with the specified userdata. It then returns the item after this position. To do this, the sorter-function must be set through the SetSortFunc function, otherwise it will just return the position after the last item.
References CompareItems(), and m_sort_func.
Referenced by CSearchListCtrl::AddResult(), CSharedFilesCtrl::DoShowFile(), and CServerListCtrl::RefreshServer().
int CMuleListCtrl::GetNewColumnIndex (int oldindex) const [private]
Find out the new index of the column by the old index.
Parameters:
[in] oldindex Old column index which we want to turn into a new index.
Returns:
The new index of the column, or -1 if an error occured.
References GetColumnIndex(), and GetOldColumnOrder().
Referenced by ParseOldConfigEntries().
wxString CMuleListCtrl::GetOldColumnOrder () const [protected, virtual]
Return old column order.
Returns:
The pre-2.2.2 column order.
This function should be overridden in descendant classes to return a comma-separated list of the old column order, when column data was saved/loaded by index. The default implementation returns an empty string, meaning that old settings (if any) should be discarded.
Note:
When you add or remove columns from the list control, DO NOT change this list. This list may only be updated if you changed a column name that is already in this list, to reflect the name change. List order also must be preserved.
Reimplemented in CDownloadListCtrl, CSearchListCtrl, CServerListCtrl, and CSharedFilesCtrl.
Referenced by GetNewColumnIndex().
CMuleListCtrl::ItemDataList CMuleListCtrl::GetSelectedItems () const
Returns a list the user-data of all selected items.
Returns:
A list of data associated with the selected items.
This function will return the user-data for each selected item in a vector, which can then be manipulated with regards to changes made in the current order of the listctrl items.
Referenced by CServerListCtrl::OnPriorityChange(), CServerListCtrl::OnStaticChange(), and SortList().
wxString CMuleListCtrl::GetTTSText (unsigned item) const [protected, virtual]
Returns the string used when selecting rows via Type-To-Select.
Parameters:
item The index of the item being examined.
By default, this function simply returns the text in the first column for the given item. However, when owner-drawing is enabled, this function _must_ be overriden.
Reimplemented in CDownloadListCtrl, CGenericClientListCtrl, CSearchListCtrl, and CSharedFilesCtrl.
Referenced by OnChar().
long CMuleListCtrl::InsertColumn (long col, const wxString & heading, int format = wxLIST_FORMAT_LEFT, int width = -1, const wxString & name = wxEmptyString)
Insert a new column.
Parameters:
[in] col Column will be inserted at this position.
[in] heading Heading text for the column.
[in] format Format (alignment) of the column.
[in] width The column width.
[in] name Internal name of the column.
We override this method to allow a name to be specified for each column. The name is used for saving/loading column settings independently of their index. It is necessary to set a unique name for each column, to let column settings be saved/loaded. If you don't set a name for a column, settings for that column won't be saved.
Requirements about column names:
they must not contain the ':' (colon) and ',' (comma) characters,
they should be at least one character long.
Note:
Changing the internal name of one column results in width of that column being reset to default, and if sorting was done by that column, sorting being forgotten. If you change the name of a column, don't forget to update the list GetOldColumnOrder() returns, if necessary.
For more information refer to the wxWidgets documentation of wxListCtrl::InsertColumn()
References m_column_names.
Referenced by CSearchListCtrl::CSearchListCtrl(), CServerListCtrl::CServerListCtrl(), CSharedFilesCtrl::CSharedFilesCtrl(), and CGenericClientListCtrl::InitColumnData().
void CMuleListCtrl::LoadSettings () [virtual]
Loads column settings.
Currently loads the width of all columns, hidden columns, the column to sort by and in which direction to sort. This function also ensures that the items are sorted after the settings have been read.
References GetColumnIndex(), m_column_sizes, m_name, m_sort_func, m_sort_orders, ParseOldConfigEntries(), SetSorting(), SORT_ALT, SORT_DES, and SortList().
Referenced by CSearchListCtrl::CSearchListCtrl(), CServerListCtrl::CServerListCtrl(), CSharedFilesCtrl::CSharedFilesCtrl(), and CGenericClientListCtrl::InitColumnData().
void CMuleListCtrl::ParseOldConfigEntries (const wxString & sortOrders, const wxString & columnWidths) [private]
Parses old config entries.
Parameters:
[in] sortOrders Old sort orders line.
[in] columnWidths Old column widths line.
References GetNewColumnIndex(), SetSorting(), and SORTING_MASK.
Referenced by LoadSettings().
void CMuleListCtrl::SaveSettings () [virtual]
Saves column settings.
Currently saves the width of all columns, hidden columns, the column to sort by and in which direction to sort.
References GetColumnName(), m_column_sizes, m_name, m_sort_orders, SORT_ALT, and SORT_DES.
Referenced by ~CMuleListCtrl().
void CMuleListCtrl::SetColumnImage (unsigned col, int image) [private]
Sets the image of a specific column.
Parameters:
col The column to change.
order The sorting order to represent. Zero unsets the image.
Referenced by SetSorting().
void CMuleListCtrl::SetSortFunc (MuleListCtrlCompare func) [inline]
Sets the sorter function.
Parameters:
func See the documentation on wxListCtrl::SortItems for more information about the expected function type.
References m_sort_func.
Referenced by CSearchListCtrl::CSearchListCtrl(), CServerListCtrl::CServerListCtrl(), and CSharedFilesCtrl::CSharedFilesCtrl().
void CMuleListCtrl::SetSorting (unsigned column, unsigned order) [protected, virtual]
Set the sort column.
Parameters:
column The column with which the list should be sorted.
order The order in which to sort the column.
Note that attempting to sort a column in an unsupported order is an illegal operation.
Reimplemented in CSearchListCtrl.
References m_sort_orders, SetColumnImage(), SORT_ALT, SORT_DES, SORTING_MASK, and SortList().
Referenced by LoadSettings(), OnColumnLClick(), and ParseOldConfigEntries().
void CMuleListCtrl::SetTableName (const wxString & name) [inline, protected]
Sets the internally used table-name.
Parameters:
name The new name or an empty string to disable.
You need to call this function with a unique name before you can make use of the LoadSettings/SaveSettings functions. CMuleListCtrl uses the name specified in this command to create unique keynames.
References m_name.
Referenced by CSearchListCtrl::CSearchListCtrl(), CServerListCtrl::CServerListCtrl(), CSharedFilesCtrl::CSharedFilesCtrl(), and CSearchListCtrl::~CSearchListCtrl().
void CMuleListCtrl::SortList () [virtual]
Sorts the list.
Before you can use this function, you will need to specify a sorter function using SetSortFunc. wxListCtrl needs such a function to perform the sort.
References GetSelectedItems(), IsSorting(), m_sort_func, m_sort_orders, ResetTTS(), and SortProc().
Referenced by CDownloadListCtrl::AddFile(), LoadSettings(), CTransferWnd::OnSetDefaultCat(), CServerListCtrl::RefreshServer(), SetSorting(), CSharedFilesCtrl::ShowFileList(), CGenericClientListCtrl::ShowSources(), and CSearchListCtrl::UpdateResult().
int CMuleListCtrl::SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData) [static, private]
Wrapper around the user-provided sorter function.
This function ensures that items are sorted in the order specified by clicking on column-headers, and also enforces that different entries are never considered equal. This is required for lists that make use of child-items, since otherwise, parents may not end up properly located in relation to child-items.
Reimplemented in CDownloadListCtrl, CFileDetailListCtrl, CGenericClientListCtrl, CSearchListCtrl, CServerListCtrl, and CSharedFilesCtrl.
Referenced by SortList().
The documentation for this class was generated from the following files:
src/MuleListCtrl.h
src/MuleListCtrl.cpp