aMule: CThreadTask Class Reference
CThreadTask Class Reference
Base-class of all threaded tasks.
#include <ThreadScheduler.h>
Public Member Functions
CThreadTask (const wxString &type, const wxString &desc, ETaskPriority priority=ETP_Normal)
virtual ~CThreadTask ()
const wxString & GetType () const
const wxString & GetDesc () const
ETaskPriority GetPriority () const
Protected Member Functions
virtual void Entry ()=0
virtual void OnLastTask ()
virtual void OnExit ()
bool TestDestroy () const
Private Attributes
wxString m_type
wxString m_desc
ETaskPriority m_priority
CMuleThread * m_owner
bool m_abort
Friends
class CThreadScheduler
Detailed Description
Base-class of all threaded tasks.
This class acts as a pseudo-thread, and is transparently executed on a worker thread by the CThreadScheduler class.
Note that the task type should be an unique description of the task type, as it is used to detect completion of all tasks of a given type and in duplicate detection with the description. The description should be unique for the given task, such that duplicates can be discovered.
Constructor & Destructor Documentation
CThreadTask::CThreadTask (const wxString & type, const wxString & desc, ETaskPriority priority = ETP_Normal)
Parameters:
type Should be a name constant among tasks of the type (hashing, completion, etc).
desc Should be an unique description for this task, for detecting duplicates.
priority Decides how soon the task will be carried out.
CThreadTask::~CThreadTask () [virtual]
Needed since CThreadScheduler only works with CThreadTask pointers.
Member Function Documentation
virtual void CThreadTask::Entry () [protected, pure virtual]
See also:
wxThread::Entry
Implemented in CIPFilterTask, CHashingTask, CAICHSyncTask, CCompletionTask, and CAllocateFileTask.
const wxString & CThreadTask::GetDesc () const
Returns the task description, used for debugging and duplicate detection.
Referenced by CThreadScheduler::AddTask(), and CThreadScheduler::DoAddTask().
ETaskPriority CThreadTask::GetPriority () const
Returns the priority of the task.
Used when selecting the next task.
const wxString & CThreadTask::GetType () const
Returns the task type, used for debugging and duplicate detection.
Referenced by CThreadScheduler::DoAddTask(), and CHashingTask::OnLastTask().
void CThreadTask::OnExit () [protected, virtual]
See also:
wxThread::OnExit
Reimplemented in CCompletionTask, and CAllocateFileTask.
void CThreadTask::OnLastTask () [protected, virtual]
Called when the last task of a specific type has been completed.
Reimplemented in CHashingTask.
bool CThreadTask::TestDestroy () const [protected]
See also:
wxThread::TestDestroy
References m_abort, m_owner, and CMuleThread::TestDestroy().
Referenced by CHashingTask::Entry(), and CIPFilterTask::LoadFromFile().
The documentation for this class was generated from the following files:
src/ThreadScheduler.h
src/ThreadScheduler.cpp