aMule: CServerListCtrl Class Reference
CServerListCtrl Class Reference
The CServerListCtrl is used to display the list of servers which the user can connect to and which we request sources from.
#include <ServerListCtrl.h>
Public Member Functions
CServerListCtrl (wxWindow *parent, wxWindowID winid=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxLC_ICON, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxT("mulelistctrl"))
virtual ~CServerListCtrl ()
void AddServer (CServer *toadd)
void RemoveServer (CServer *server)
void RemoveAllServers (int state=wxLIST_STATE_DONTCARE)
void RefreshServer (CServer *server)
void HighlightServer (const CServer *server, bool highlight)
void ShowServerCount ()
Protected Member Functions
wxString GetOldColumnOrder () const
Private Member Functions
void OnItemActivated (wxListEvent &event)
void OnItemRightClicked (wxListEvent &event)
void OnPriorityChange (wxCommandEvent &event)
void OnStaticChange (wxCommandEvent &event)
void OnConnectToServer (wxCommandEvent &event)
void OnGetED2kURL (wxCommandEvent &event)
void OnRemoveServers (wxCommandEvent &event)
void OnKeyPressed (wxKeyEvent &event)
Static Private Member Functions
static int wxCALLBACK SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData)
Private Attributes
const CServer * m_connected
Detailed Description
The CServerListCtrl is used to display the list of servers which the user can connect to and which we request sources from.
It is a permanently sorted list in that it always ensure that the items are sorted in the correct order.
Constructor & Destructor Documentation
CServerListCtrl::CServerListCtrl (wxWindow * parent, wxWindowID winid = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxLC_ICON, const wxValidator & validator = wxDefaultValidator, const wxString & name = wxT("mulelistctrl"))
Constructor.
See also:
CMuleListCtrl::CMuleListCtrl
References CMuleListCtrl::InsertColumn(), CMuleListCtrl::LoadSettings(), m_connected, CMuleListCtrl::SetSortFunc(), CMuleListCtrl::SetTableName(), and SortProc().
Member Function Documentation
void CServerListCtrl::AddServer (CServer * toadd)
Adds a server to the list.
Parameters:
A pointer to the new server.
Internally this function calls RefreshServer and ShowServerCount, with the result that it is legal to add servers already in the list, though not recommended.
References RefreshServer(), and ShowServerCount().
void CServerListCtrl::HighlightServer (const CServer * server, bool highlight)
Sets the highlighting of the specified server.
Parameters:
server The server to have its highlighting set.
highlight The new highlighting state.
Please note that only _one_ item is allowed to be highlighted at any one time, so calling this function while another item is already highlighted will result in the old item not being highlighted any more.
References m_connected.
void CServerListCtrl::RefreshServer (CServer * server)
Updates the displayed information on a server.
Parameters:
server The server to be updated.
This function will not only update the displayed information, it will also reposition the item should it be nescecarry to enforce the current sorting. Also note that this function does not require that the server actually is on the list already, since AddServer makes use of it, but this should generally be avoided, since it will result in the server-count getting skewed until the next AddServer call.
References CMuleListCtrl::GetInsertPos(), CMuleListCtrl::IsItemSorted(), and CMuleListCtrl::SortList().
Referenced by AddServer().
void CServerListCtrl::RemoveAllServers (int state = wxLIST_STATE_DONTCARE)
Removes all servers with the specified state.
Parameters:
state All items with this state will be removed, default being all.
References m_connected, and ShowServerCount().
Referenced by OnRemoveServers().
int CServerListCtrl::SortProc (wxUIntPtr item1, wxUIntPtr item2, long sortData) [static, private]
Sorter function.
See also:
wxListCtrl::SortItems
Reimplemented from CMuleListCtrl.
References CMuleListCtrl::COLUMN_MASK, and CMuleListCtrl::SORT_DES.
Referenced by CServerListCtrl().
The documentation for this class was generated from the following files:
src/ServerListCtrl.h
src/ServerListCtrl.cpp