aMule: CECFileConfig Class Reference
CECFileConfig Class Reference
Extension to wxFileConfig for reading/writing CMD4Hash values.
#include <ECFileConfig.h>
Public Member Functions
CECFileConfig (const wxString &localFilename=wxEmptyString)
bool ReadHash (const wxString &key, CMD4Hash *hash)
bool WriteHash (const wxString &key, const CMD4Hash &hash)
Detailed Description
Extension to wxFileConfig for reading/writing CMD4Hash values.
This class converts between the text and binary representation of an MD4 hash, and also maps empty strings to the empty hash and vica versa.
Member Function Documentation
bool CECFileConfig::ReadHash (const wxString & key, CMD4Hash * hash) [inline]
Reads a hash from the config file.
Parameters:
key the key to be read
hash the CMD4Hash object to write the hash to
Returns:
true on success, false otherwise.
References CMD4Hash::Clear(), and CMD4Hash::Decode().
bool CECFileConfig::WriteHash (const wxString & key, const CMD4Hash & hash) [inline]
Writes a CMD4Hash object to the config file.
Parameters:
key the key to write to
hash the hash to be written
Returns:
true on success, false otherwise.
References CMD4Hash::IsEmpty().
The documentation for this class was generated from the following file:
src/libs/ec/cpp/ECFileConfig.h