aMule: CStatTreeItemBase Class Reference
CStatTreeItemBase Class Reference
Base tree item class.
#include <StatTree.h>
Public Member Functions
CStatTreeItemBase (const wxString &label, unsigned flags=stNone)
VIRTUAL ~CStatTreeItemBase ()
CStatTreeItemBase * AddChild (CStatTreeItemBase *child, uint32_t id=0, bool skipOneLevel=false)
bool HasChildren ()
bool HasVisibleChildren ()
bool HasChildWithId (uint32_t id)
CStatTreeItemBase * GetChildById (uint32_t id)
StatTreeItemIterator GetFirstVisibleChild (uint32_t max_children)
void GetNextVisibleChild (StatTreeItemIterator &it)
bool IsAtEndOfList (StatTreeItemIterator &it)
void ReSortChildren ()
virtual wxString GetDisplayString () const
wxMutex & GetLock ()
uint32_t GetUniqueId () const
VIRTUAL bool IsVisible () const
virtual CECTag * CreateECTag (uint32_t max_children)
Protected Member Functions
virtual void AddECValues (CECTag *) const
Protected Attributes
const wxString m_label
CStatTreeItemBase * m_parent
unsigned m_flags
Static Private Member Functions
static bool ValueSort (const CStatTreeItemBase *a, const CStatTreeItemBase *b)
Private Attributes
uint32_t m_id
uint32_t m_visible_counter
uint32_t m_uniqueid
std::list< CStatTreeItemBase * > m_children
wxMutex m_lock
Detailed Description
Base tree item class.
Constructor & Destructor Documentation
CStatTreeItemBase::CStatTreeItemBase (const wxString & label, unsigned flags = stNone) [inline]
Creates an item with a constant label.
Parameters:
label Visible text for the item.
flags Flags to use.
Member Function Documentation
CStatTreeItemBase * CStatTreeItemBase::AddChild (CStatTreeItemBase * child, uint32_t id = 0, bool skipOneLevel = false)
Adds a new child node.
Parameters:
child child to add.
id an optional ID for the new item.
skipOneLevel activates a trick to let the code work for aMule OSInfo and Version trees.
Returns:
the newly added item.
References m_children, m_flags, m_id, m_lock, m_parent, and stSortChildren.
virtual void CStatTreeItemBase::AddECValues (CECTag *) const [inline, protected, virtual]
Add values to the EC tag being generated.
Should have a real implementation in children which have some value. The given parameter is the tag to which values should be added.
Reimplemented in CStatTreeItemRateCounter, CStatTreeItemPeakConnections, CStatTreeItemSimple, CStatTreeItemCounterTmpl< _Tp >, CStatTreeItemHiddenCounter, CStatTreeItemUlDlCounter, CStatTreeItemCounterMax, CStatTreeItemPackets, CStatTreeItemPacketTotals, CStatTreeItemTimer, CStatTreeItemAverage, CStatTreeItemAverageSpeed, CStatTreeItemRatio, CStatTreeItemReconnects, CStatTreeItemMaxConnLimitReached, CStatTreeItemTotalClients, CStatTreeItemCounterTmpl< uint32_t >, and CStatTreeItemCounterTmpl< uint64_t >.
Referenced by CreateECTag().
CECTag * CStatTreeItemBase::CreateECTag (uint32_t max_children) [virtual]
Create an EC tag from this node (and children).
Parameters:
max_children The maximum number of children to show, when the stCapChildren flag is set. Otherwise it has no effect. (0 = unlimited)
Returns:
A EC tag containing this node and all its children.
References AddECValues(), CECTag::AddTag(), IsVisible(), m_children, m_flags, m_label, m_lock, m_uniqueid, m_visible_counter, and stCapChildren.
CStatTreeItemBase * CStatTreeItemBase::GetChildById (uint32_t id)
Access a specific child.
Returns:
the child with the given ID, or NULL if not found.
References m_children, and m_lock.
StatTreeItemIterator CStatTreeItemBase::GetFirstVisibleChild (uint32_t max_children)
Get the first visible child.
Parameters:
max_children The maximum number of children to show, when the stCapChildren flag is set. Otherwise it has no effect. (0 = unlimited)
Returns:
An iterator, that should be passed to GetNextVisibleChild() and IsAtEndOfList().
References m_children, and m_visible_counter.
wxMutex& CStatTreeItemBase::GetLock () [inline]
Returns the mutex used to lock the child list of this node.
This function is used by CStatisticsDlg to be able to lock the core tree while updating the GUI tree.
References m_lock.
bool CStatTreeItemBase::HasChildren () [inline]
Check for children.
Returns:
true if this node has children, false otherwise.
References m_children, and m_lock.
bool CStatTreeItemBase::HasChildWithId (uint32_t id)
Check for a given child.
Returns:
true if this node has a child with the given ID.
References m_children, and m_lock.
bool CStatTreeItemBase::HasVisibleChildren ()
Check for visible children.
Returns:
true if this node has children and at least one of them is visible.
References m_children, and m_lock.
The documentation for this class was generated from the following files:
src/StatTree.h
src/StatTree.cpp