aMule: CPartFile Class Reference
CPartFile Class Reference
Public Types
typedef std::list
< Requested_Block_Struct * > CReqBlockPtrList
Public Member Functions
virtual void SetFileName (const CPath &filename)
CPartFile (CSearchFile *searchresult)
CPartFile (const CED2KFileLink *fileLink)
virtual bool LoadFromFile (const CFileDataIO *file)
bool WriteToFile (CFileDataIO *file)
bool IsPartFile () const
bool IsCompleted () const
bool IsCPartFile () const
uint32 Process (uint32 reducedownload, uint8 m_icounter)
uint8 LoadPartFile (const CPath &in_directory, const CPath &filename, bool from_backup=false, bool getsizeonly=false)
bool SavePartFile (bool Initial=false)
void PartFileHashFinished (CKnownFile *result)
bool HashSinglePart (uint16 partnumber)
bool CheckShowItemInGivenCat (int inCategory)
bool IsComplete (uint64 start, uint64 end)
bool IsComplete (uint16 part)
void UpdateCompletedInfos ()
bool GetNextRequestedBlock (CUpDownClient *sender, std::vector< Requested_Block_Struct * > &toadd, uint16 &count)
void WritePartStatus (CMemFile *file)
void WriteCompleteSourcesCount (CMemFile *file)
void AddSources (CMemFile &sources, uint32 serverip, uint16 serverport, unsigned origin, bool bWithObfuscationAndHash)
uint8 GetStatus (bool ignorepause=false) const
virtual void UpdatePartsInfo ()
const CPath & GetPartMetFileName () const
uint16 GetPartMetNumber () const
uint64 GetTransferred () const
const CPath & GetFullName () const
float GetKBpsDown () const
double GetPercentCompleted () const
uint16 GetSourceCount () const
uint16 GetSrcA4AFCount () const
uint16 GetTransferingSrcCount () const
uint16 GetNotCurrentSourcesCount () const
uint16 GetValidSourcesCount () const
uint64 GetNeededSpace ()
virtual wxString GetFeedback () const
wxString getPartfileStatus () const
sint32 getTimeRemaining () const
int getPartfileStatusRang () const
uint32 WriteToBuffer (uint32 transize, byte *data, uint64 start, uint64 end, Requested_Block_Struct *block, const CUpDownClient *client)
void FlushBuffer (bool fromAICHRecoveryDataAvailable=false)
void RemoveAllRequestedBlocks (void)
void RemoveBlockFromList (uint64 start, uint64 end)
void RemoveAllSources (bool bTryToSwap)
void Delete ()
void StopFile (bool bCancel=false)
void PauseFile (bool bInsufficient=false)
void ResumeFile ()
virtual CPacket * CreateSrcInfoPacket (const CUpDownClient *forClient, uint8 byRequestedVersion, uint16 nRequestedOptions)
void AddClientSources (CMemFile *sources, unsigned nSourceFrom, uint8 uClientSXVersion, bool bSourceExchange2, const CUpDownClient *pClient=NULL)
bool PreviewAvailable ()
uint16 GetAvailablePartCount () const
uint32 GetLastAnsweredTime () const
void SetLastAnsweredTime ()
void SetLastAnsweredTimeTimeout ()
uint64 GetLostDueToCorruption () const
uint64 GetGainDueToCompression () const
uint32 TotalPacketsSavedDueToICH () const
bool IsStopped () const
bool IsPaused () const
void UpdateFileRatingCommentAvail ()
int GetCommonFilePenalty ()
void UpdateDisplayedInfo (bool force=false)
uint8 GetCategory () const
void SetCategory (uint8 cat)
void RemoveCategory (uint8 cat)
void SetDownPriority (uint8 newDownPriority, bool bSave=true, bool bRefresh=true)
bool IsAutoDownPriority () const
void SetAutoDownPriority (bool flag)
void UpdateAutoDownPriority ()
uint8 GetDownPriority () const
void SetActive (bool bActive)
uint32 GetDlActiveTime () const
bool GetInsufficient () const
void CompleteFileEnded (bool errorOccured, const CPath &newname)
bool RemoveSource (CUpDownClient *toremove, bool updatewindow=true, bool bDoStatsUpdate=true)
void RequestAICHRecovery (uint16 nPart)
void AICHRecoveryDataAvailable (uint16 nPart)
void ClientStateChanged (int oldState, int newState)
bool AddSource (CUpDownClient *client)
bool DelSource (CUpDownClient *client)
void UpdatePartsFrequency (CUpDownClient *client, bool increment)
const SourceSet & GetSourceList () const
const SourceSet & GetA4AFList () const
void ClearA4AFList ()
const CReqBlockPtrList GetRequestedBlockList () const
const CGapList & GetGapList () const
void AddDeadSource (const CUpDownClient *client)
bool IsDeadSource (const CUpDownClient *client)
uint16 GetMaxSources () const
uint16 GetMaxSourcePerFileSoft () const
uint16 GetMaxSourcePerFileUDP () const
void GetRatingAndComments (FileRatingList &list) const
void AllocationFinished ()
bool IsHashSetNeeded () const
void SetHashSetNeeded (bool value)
uint64 GetCompletedSize () const
void SetCompletedSize (uint64 size)
bool IsLocalSrcRequestQueued () const
void SetLocalSrcRequestQueued (bool value)
void AddA4AFSource (CUpDownClient *src)
bool RemoveA4AFSource (CUpDownClient *src)
uint32 GetLastSearchTime () const
void SetLastSearchTime (uint32 time)
void AddDownloadingSource (CUpDownClient *client)
void RemoveDownloadingSource (CUpDownClient *client)
void SetStatus (uint8 in)
void StopPausedFile ()
void SetA4AFAuto (bool in)
bool IsA4AFAuto () const
void SaveSourceSeeds ()
void LoadSourceSeeds ()
CUpDownClient * GetSlowerDownloadingClient (uint32 speed, CUpDownClient *caller)
bool ReadData (class CFileArea &area, uint64 offset, uint32 toread)
Static Public Member Functions
static bool CanAddSource (uint32 userid, uint16 port, uint32 serverip, uint16 serverport, uint8 *pdebug_lowiddropped=NULL, bool ed2kID=true)
Public Attributes
time_t lastseencomplete
ArrayOfUInts16 m_SrcpartFrequency
Private Member Functions
void AddGap (uint64 start, uint64 end)
void AddGap (uint16 part)
void FillGap (uint64 start, uint64 end)
void FillGap (uint16 part)
bool GetNextEmptyBlockInPart (uint16 partnumber, Requested_Block_Struct *result)
bool IsAlreadyRequested (uint64 start, uint64 end)
void CompleteFile (bool hashingdone)
void CreatePartFile ()
void Init ()
bool CheckFreeDiskSpace (uint64 neededSpace=0)
bool IsCorruptedPart (uint16 partnumber)
void PerformFileComplete ()
Private Attributes
CFileAutoClose m_hpartfile
CDeadSourceList m_deadSources
class CCorruptionBlackBox * m_CorruptionBlackBox
uint16 m_notCurrentSources
uint32 m_validSources
uint32 m_iLastPausePurge
uint16 m_count
uint16 transferingsrc
uint64 completedsize
uint64 transferred
uint64 m_iLostDueToCorruption
uint64 m_iGainDueToCompression
uint32 m_iTotalPacketsSavedDueToICH
float kBpsDown
CPath m_fullname
CPath m_partmetfilename
CPath m_PartPath
bool m_paused
bool m_stopped
bool m_insufficient
uint8 m_iDownPriority
bool m_bAutoDownPriority
uint8 status
uint32 lastpurgetime
uint32 m_LastNoNeededCheck
CGapList m_gaplist
CReqBlockPtrList m_requestedblocks_list
double percentcompleted
std::list< uint16 > m_corrupted_list
uint16 m_availablePartsCount
uint32 m_ClientSrcAnswered
bool m_bPercentUpdated
uint32 m_lastRefreshedDLDisplay
std::list< class
PartFileBufferedData * > m_BufferedData_list
uint32 m_nTotalBufferData
uint32 m_nLastBufferFlushTime
uint8 m_category
uint32 m_nDlActiveTime
time_t m_tActivated
bool m_is_A4AF_auto
SourceSet m_SrcList
SourceSet m_A4AFsrclist
bool m_hashsetneeded
uint32 m_lastsearchtime
bool m_localSrcReqQueued
CClientRefList m_downloadingSourcesList
uint32 m_LastSearchTimeKad
uint8 m_TotalSearchesKad
Friends
class CKnownFilesRem
class CPartFileConvert
Member Function Documentation
void CPartFile::AddDeadSource (const CUpDownClient * client)
Adds a source to the list of dead sources.
Parameters:
client The source to be recorded as dead for this file.
References CDeadSourceList::AddDeadSource(), and m_deadSources.
void CPartFile::ClientStateChanged (int oldState, int newState)
This function is used to update source-counts.
Parameters:
oldState The old state of the client, or -1 to ignore.
newState The new state of the client, or -1 to ignore.
Call this function for a client belonging to this file, which has changed its state. The value -1 can be used to make the function ignore one of the two states.
AddSource and DelSource takes care of calling this function when a source is removed, so there's no need to call this function when calling either of those.
void CPartFile::Init () [private]
Common initializations for constructors.
Reimplemented from CKnownFile.
bool CPartFile::IsDeadSource (const CUpDownClient * client)
Checks if a source is recorded as being dead for this file.
Parameters:
client The client to evaluate.
Returns:
True if dead, false otherwise.
Sources that are dead are not to be considered valid sources and should not be added to the partfile.
References CDeadSourceList::IsDeadSource(), and m_deadSources.
Referenced by CDownloadQueue::CheckAndAddKnownSource(), and CDownloadQueue::CheckAndAddSource().
void CPartFile::UpdatePartsFrequency (CUpDownClient * client, bool increment)
Updates the requency of avilable parts from with the data the client provides.
Parameters:
client The clients whoose available parts should be considered.
increment If true, the counts are incremented, otherwise they are decremented.
This functions updates the frequency list of file-parts, using the clients parts-status. This function should be called by clients every time they update their parts-status, or when they are added or removed from the file.
The documentation for this class was generated from the following files:
src/PartFile.h
src/amule-remote-gui.cpp
src/PartFile.cpp