aMule: CRangeMap< VALUE, KEYTYPE > Class Template Reference
CRangeMap< VALUE, KEYTYPE > Class Template Reference
This class represents a map of non-overlapping ranges.
#include <RangeMap.h>
Classes
class iterator_base
This class provides a wrapper around the raw iterators used by CRangeMap.
Public Types
typedef iterator_base
< RangeIterator, ValueRef,
ValuePtr > iterator
typedef iterator_base
< ConstRangeIterator,
ConstValueRef, ConstValuePtr > const_iterator
typedef RangeMap::size_type size_type
typedef VALUE value_type
Public Member Functions
CRangeMap ()
CRangeMap (const CRangeMap< VALUE, KEYTYPE > &other)
CRangeMap & operator= (const CRangeMap< VALUE, KEYTYPE > &other)
void swap (CRangeMap< VALUE, KEYTYPE > &other)
bool operator== (const CRangeMap< VALUE, KEYTYPE > &other) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator erase (iterator pos)
size_type size () const
bool empty () const
void clear ()
iterator find_range (KEYTYPE key)
void erase_range (KEYTYPE startPos, KEYTYPE endPos)
iterator insert (KEYTYPE startPos, KEYTYPE endPos)
template<typename TYPE >
iterator insert (KEYTYPE startPos, KEYTYPE endPos, const TYPE &value)
Protected Member Functions
iterator do_insert (KEYTYPE start, HELPER entry, bool merge=true)
RangeIterator get_insert_it (KEYTYPE start)
RangeIterator resize (KEYTYPE startPos, KEYTYPE endPos, RangeIterator it)
Private Types
typedef CRangeMapHelper< VALUE,
KEYTYPE > HELPER
typedef std::map< KEYTYPE, HELPER > RangeMap
typedef std::pair< KEYTYPE,
HELPER > RangePair
typedef RangeMap::iterator RangeIterator
typedef RangeMap::const_iterator ConstRangeIterator
typedef HELPER::ValueRef ValueRef
typedef HELPER::ValuePtr ValuePtr
typedef HELPER::ConstValueRef ConstValueRef
typedef HELPER::ConstValuePtr ConstValuePtr
Private Attributes
RangeMap m_ranges
Detailed Description
template<typename VALUE, typename KEYTYPE = uint64>
class CRangeMap< VALUE, KEYTYPE >
This class represents a map of non-overlapping ranges.
Each range has a user-specified value associated. The map supports quick lookup of which range covers a particular key-value, and will merge or split existing ranges when new ranges are added.
The decision on whenever to split/resize a range or to merge the two ranges involved is based on equality of the user-specified value, using the equality operator. Thus if two ranges with the same user-value are placed adjacent to each other or partially overlapping each other, then they will be merged into a single range. If the user-values of the two ranges are different, then the old range will be either resized or split, based on the position of the new range.
In cases where ranges are split into two parts, copies will be made of the user-specified value, such that each new part contains the same user-value.
It is currently not possible to manipulate existing ranges by hand, other than by erasing and then re-inserting them.
A specialization of this class exists (typedef'd as CRangeSet), which does not assosiate a value with each range.
NOTE: KEYTYPE is assumed to be an unsigned integer type!
Member Function Documentation
template<typename VALUE, typename KEYTYPE = uint64> iterator CRangeMap< VALUE, KEYTYPE >::do_insert (KEYTYPE start, HELPER entry, bool merge = true) [inline, protected]
Inserts the specified range.
Parameters:
start The starting position of the range.
entry A helper-struct, containing the end position and possibly user-data.
merge Specifies if ranges should be merged when possible.
Returns:
An iterator pointing to the range covering at least the specified range.
Referenced by CRangeMap< rangeObject, uint32 >::insert().
template<typename VALUE, typename KEYTYPE = uint64> iterator CRangeMap< VALUE, KEYTYPE >::erase (iterator pos) [inline]
Erases the specified range and returns the range next to it.
Parameters:
pos The iterator of the range to be erased.
Returns:
The iterator of the range after the erased range.
Attempting to erase the end() iterator is an invalid operation.
template<typename VALUE, typename KEYTYPE = uint64> iterator CRangeMap< VALUE, KEYTYPE >::find_range (KEYTYPE key) [inline]
Returns the range covering the specified key-value.
Parameters:
key A value that may or may not be covered by a range.
Returns:
end() or the iterator of the range covering key.
A range is considered to cover a value if the value is greather than or equal to the start-key and less than or equal to the end-key.
template<typename VALUE, typename KEYTYPE = uint64> RangeIterator CRangeMap< VALUE, KEYTYPE >::get_insert_it (KEYTYPE start) [inline, protected]
Finds the optimal location to start looking for insertion points.
This is the first range whose start comes after the new start. We check the last element first, since sequential insertions are commen.
Referenced by CRangeMap< rangeObject, uint32 >::do_insert().
template<typename VALUE, typename KEYTYPE = uint64> iterator CRangeMap< VALUE, KEYTYPE >::insert (KEYTYPE startPos, KEYTYPE endPos) [inline]
Inserts a new range into the map, potentially erasing/changing old ranges.
Parameters:
startPos The start position of the range, also considered part of the range.
endPos The end position of the range, also considered part of the range.
object The user-data to be assosiated with the range.
Returns:
An iterator pointing to the resulting range, covering at least the specified range.
This function inserts the specified range into the map, while overwriting or resizing existing ranges if there is any conflict. Ranges might also be merged, if the object of each evaluates to being equal, in which case the old range will be removed and the new extended to include the old range. This also includes ranges placed directly after or in front of each other, which will also be merged if their type is the same.
This has the result that the iterator returned can point to a range quite different from what was originally specified. If this is not desired, then the VALUE type should simply be made to return false on all equality tests. Otherwise, the only promise that is made is that the resulting range has the same user-data (based on the equality operator) as the what was specified.
Note that the start position must be smaller than or equal to the end-position.
Referenced by CIPFilterTask::AddIPRange().
template<typename VALUE, typename KEYTYPE = uint64> bool CRangeMap< VALUE, KEYTYPE >::operator== (const CRangeMap< VALUE, KEYTYPE > & other) const [inline]
Equality operator for two ranges.
Returns:
True if both ranges contain the same ranges and values.
The documentation for this class was generated from the following file:
src/RangeMap.h