aMule: CFileAutoClose Class Reference
CFileAutoClose Class Reference
This class encapsulates the CFile class.
#include <FileAutoClose.h>
Public Member Functions
CFileAutoClose ()
CFileAutoClose (const CPath &path, CFile::OpenMode mode=CFile::read)
bool Release (bool now=false)
bool Open (const CPath &path, CFile::OpenMode mode=CFile::read)
bool Create (const CPath &path, bool overwrite=false)
bool Close ()
uint64 GetLength () const
bool SetLength (uint64 newLength)
const CPath & GetFilePath () const
bool IsOpened () const
void ReadAt (void *buffer, uint64 offset, size_t count)
void WriteAt (const void *buffer, uint64 offset, size_t count)
bool Eof ()
int fd ()
void Unlock ()
Private Member Functions
void Reopen ()
CFileAutoClose (const CFileAutoClose &)
CFileAutoClose & operator= (const CFileAutoClose &)
Private Attributes
CFile m_file
CFile::OpenMode m_mode
bool m_autoClosed
uint16 m_locked
uint64 m_size
uint32 m_lastAccess
Detailed Description
This class encapsulates the CFile class.
It allows to close the used file handle and reopen it on usage to minimize the number of used file handles.
Constructor & Destructor Documentation
CFileAutoClose::CFileAutoClose (const CPath & path, CFile::OpenMode mode = CFile::read)
Constructor, calls Open on the specified file.
To check if the file was successfully opened, a call to IsOpened() is required.
References Open().
Member Function Documentation
bool CFileAutoClose::Close ()
Closes the file.
Note that calling Close on an closed file is an illegal operation.
References CFile::Close(), m_autoClosed, and m_file.
bool CFileAutoClose::Create (const CPath & path, bool overwrite = false)
Calling Create is equivilant of calling open with OpenMode 'write'.
Parameters:
overwrite Specifies if the target file should be overwritten, in case that it already exists.
See also:
CFile::Open
References CFile::Create(), m_autoClosed, m_file, m_lastAccess, and m_mode.
int CFileAutoClose::fd ()
Returns the file descriptior assosiated with the file.
This breaks the purpose of this class of course. Therefore the AutoClose mechanism is disabled when fd() is called. It's required for FileArea's mmap stuff. Currently FileArea objects are shortlived enough for this not being a problem anyway, but that might change in the future.
References CFile::fd(), m_file, m_locked, and Reopen().
Referenced by CFileArea::ReadAt().
uint64 CFileAutoClose::GetLength () const
See also:
CSafeFileIO::GetLength
Note that calling GetLength on a closed file is an illegal operation.
References CFile::GetLength(), m_autoClosed, m_file, and m_size.
Referenced by CHashingTask::Entry().
bool CFileAutoClose::Open (const CPath & path, CFile::OpenMode mode = CFile::read)
Opens a file.
Parameters:
path The full or relative path to the file.
mode The opening mode (see CFile).
Returns:
True if the file was opened, false otherwise.
References m_autoClosed, m_file, m_lastAccess, m_locked, m_mode, m_size, and CFile::Open().
Referenced by CFileAutoClose(), and CHashingTask::Entry().
void CFileAutoClose::ReadAt (void * buffer, uint64 offset, size_t count)
Reads 'count' bytes into 'buffer'.
Parameters:
buffer The target buffer.
offset The seek address in the file.
count The number of bytes to read.
See CFileDataIO::Read
References m_file, CFileDataIO::Read(), Reopen(), and CFileDataIO::Seek().
Referenced by CFileArea::ReadAt().
bool CFileAutoClose::Release (bool now = false)
Request auto closing of the file handle.
Parameters:
now true: close immediately false: close when timeout has expired
Returns:
True if the file has been (or has already been) autoclosed.
References CFile::Close(), GetFilePath(), CFile::GetLength(), CFile::IsOpened(), m_autoClosed, m_file, m_lastAccess, m_locked, and m_size.
void CFileAutoClose::WriteAt (const void * buffer, uint64 offset, size_t count)
Write 'count' bytes from 'buffer' into the file.
Parameters:
buffer The source-data buffer.
offset The seek address in the file.
count The number of bytes to write.
See CFileDataIO::Write
References m_file, Reopen(), CFileDataIO::Seek(), and CFileDataIO::Write().
Referenced by CFileArea::FlushAt().
The documentation for this class was generated from the following files:
src/FileAutoClose.h
src/FileAutoClose.cpp