aMule: CStatTreeItemTimer Class Reference
CStatTreeItemTimer Class Reference
Tree item for timer type nodes.
#include <StatTree.h>
Public Member Functions
CStatTreeItemTimer (const wxString &label, unsigned flags=stNone)
void SetStartTime (uint64_t value)
void StartTimer ()
void StopTimer ()
bool IsRunning () const
void ResetTimer ()
uint64_t GetTimerValue () const
operator uint64_t () const
uint64_t GetTimerSeconds () const
uint64_t GetTimerStart () const
virtual wxString GetDisplayString () const
virtual bool IsVisible () const
Protected Member Functions
virtual void AddECValues (CECTag *tag) const
Protected Attributes
uint64_t m_value
Detailed Description
Tree item for timer type nodes.
Constructor & Destructor Documentation
CStatTreeItemTimer::CStatTreeItemTimer (const wxString & label, unsigned flags = stNone) [inline]
See also:
CStatTreeItemBase::CStatTreeItemBase
Member Function Documentation
void CStatTreeItemTimer::AddECValues (CECTag * tag) const [protected, virtual]
Add values to EC tag being generated.
Parameters:
tag The tag to which values should be added.
See also:
CStatTreeItemBase::AddECValues
Reimplemented from CStatTreeItemBase.
References CECTag::AddTag(), GetTimerSeconds(), and m_value.
wxString CStatTreeItemTimer::GetDisplayString () const [virtual]
See also:
CStatTreeItemBase::GetDisplayString()
Reimplemented from CStatTreeItemBase.
References GetTimerSeconds(), CStatTreeItemBase::m_label, and m_value.
virtual bool CStatTreeItemTimer::IsVisible () const [inline, virtual]
See also:
CStatTreeItemBase::IsVisible()
Reimplemented from CStatTreeItemBase.
References CStatTreeItemBase::m_flags, m_value, and stHideIfZero.
The documentation for this class was generated from the following files:
src/StatTree.h
src/StatTree.cpp