aMule: CFileArea Class Reference
CFileArea Class Reference
This class is used to optimize file read/write using mapped memory if supported.
#include <FileArea.h>
Public Member Functions
CFileArea ()
virtual ~CFileArea ()
bool Close ()
void ReadAt (CFileAutoClose &file, uint64 offset, size_t count)
void StartWriteAt (CFileAutoClose &file, uint64 offset, size_t count)
bool FlushAt (CFileAutoClose &file, uint64 offset, size_t count)
byte * GetBuffer () const
void CheckError ()
Private Member Functions
CFileArea (const CFileArea &)
CFileArea & operator= (const CFileArea &)
Private Attributes
byte * m_buffer
byte * m_mmap_buffer
size_t m_length
CFileArea * m_next
CFileAutoClose * m_file
bool m_error
Friends
class CFileAreaSigHandler
Detailed Description
This class is used to optimize file read/write using mapped memory if supported.
Member Function Documentation
byte* CFileArea::GetBuffer () const [inline]
Get buffer that contains data readed or to write.
Returns:
allocated buffer or NULL if not initialized
References m_buffer.
void CFileArea::ReadAt (CFileAutoClose & file, uint64 offset, size_t count)
Init area with a given piece of file.
Parameters:
file file to read.
offset seek address in file.
count bytes to read.
Initialize buffer. Buffer will contain data from current file position for count length. Buffer will be a memory mapped area or a allocated buffer depending on systems.
References Close(), CFileAutoClose::fd(), m_buffer, m_file, m_length, m_mmap_buffer, CFileAutoClose::ReadAt(), and CFileAutoClose::Unlock().
Member Data Documentation
byte* CFileArea::m_buffer [private]
Pointer to buffer used for read/write operations.
If mapped points inside m_mmap_buffer area otherwise point to an allocated buffer to be freed.
Referenced by Close(), FlushAt(), GetBuffer(), ReadAt(), and StartWriteAt().
The documentation for this class was generated from the following files:
src/FileArea.h
src/FileArea.cpp