aMule: CObservable< EventType > Class Template Reference
CObservable< EventType > Class Template Reference
This class implements the Observable part of the Observer/Observable pattern.
#include <Observable.h>
Public Types
typedef CObserver< EventType > ObserverType
Public Member Functions
virtual ~CObservable ()
bool AddObserver (ObserverType *o)
bool RemoveObserver (ObserverType *o)
Protected Member Functions
void NotifyObservers (const EventType &e, ObserverType *o=NULL)
void RemoveAllObservers ()
virtual void ObserverAdded (ObserverType *)
virtual void ObserverRemoved (ObserverType *)
Private Types
typedef std::set< ObserverType * > ObserverSetType
typedef ObserverSetType::iterator myIteratorType
Private Attributes
wxMutex m_mutex
ObserverSetType m_list
Friends
class CObserver< EventType >
Detailed Description
template<typename EventType>
class CObservable< EventType >
This class implements the Observable part of the Observer/Observable pattern.
Member Function Documentation
template<typename EventType> bool CObservable< EventType >::AddObserver (ObserverType * o)
This function subscribes an observer to events from this observable.
Parameters:
o The observer that wishes to observe this object.
Returns:
True if it succesfully subscribed, false otherwise.
If the subscription was succesful, ObserverAdded() will be called on "o", allowing the subclass to initialize the the observer's state.
Referenced by CQueueObserver< ValueType >::Reset().
template<typename EventType> void CObservable< EventType >::NotifyObservers (const EventType & e, ObserverType * o = NULL) [inline, protected]
This function notifies all or an specific observer of an event.
Parameters:
e The event to be published.
o A specific subscribing observer or NULL for all subscribers.
The purpose of the second parameter is to allow notifications of specific observers when the ObserverAdded() or ObserverRemoved() functions are called and it should not be used outside of these functions.
References CObservable< EventType >::m_list, CObservable< EventType >::m_mutex, and CObserver< EventType >::ReceiveNotification().
template<typename EventType> virtual void CObservable< EventType >::ObserverRemoved (ObserverType *) [inline, protected, virtual]
This function is called when observers are removed from the observable.
Exceptions to this are:
When the Observable is being destroyed.
When the Observer is being destroyed.
Reimplemented in CObservableQueue< CServer * >, and CObservableQueue< CPartFile * >.
Referenced by CObservable< EventType >::RemoveAllObservers().
template<typename EventType > void CObservable< EventType >::RemoveAllObservers () [inline, protected]
This function removes all observers from this object.
ObserverRemoved is called on each observer.
References CObserver< EventType >::m_list, CObservable< EventType >::m_list, CObserver< EventType >::m_mutex, CObservable< EventType >::m_mutex, and CObservable< EventType >::ObserverRemoved().
template<typename EventType> bool CObservable< EventType >::RemoveObserver (ObserverType * o)
This function removes an observer from the list of subscribers.
Parameters:
o The observer to unsubscribe from this observable.
Returns:
True if the observer was removed, false otherwise.
ObserverRemoved() will be called for the observer "o", allowing the subclass to take steps to avoid outdated data being kept.
Referenced by CQueueObserver< ValueType >::Reset().
The documentation for this class was generated from the following file:
src/Observable.h