aMule: CSearchDlg Class Reference
CSearchDlg Class Reference
This class represents the Search Dialog, which takes care of enabling the user to search and to display results in a readable manner.
#include <SearchDlg.h>
Public Member Functions
CSearchDlg (wxWindow *pParent)
~CSearchDlg ()
void AddResult (CSearchFile *toadd)
void UpdateResult (CSearchFile *toupdate)
bool CheckTabNameExists (const wxString &searchString)
void CreateNewTab (const wxString &searchString, wxUIntPtr nSearchID)
void LocalSearchEnd ()
void KadSearchEnd (uint32 id)
void UpdateCatChoice ()
void UpdateHitCount (CSearchListCtrl *page)
void ResetControls ()
void OnBnClickedDownload (wxCommandEvent &ev)
CSearchListCtrl * GetSearchList (wxUIntPtr id)
void UpdateProgress (uint32 new_value)
void StartNewSearch ()
void FixSearchTypes ()
Private Member Functions
void OnFieldChanged (wxEvent &evt)
void OnListItemSelected (wxListEvent &ev)
void OnBnClickedReset (wxCommandEvent &ev)
void OnBnClickedClear (wxCommandEvent &ev)
void OnExtendedSearchChange (wxCommandEvent &ev)
void OnFilterCheckChange (wxCommandEvent &ev)
void OnFilteringChange (wxCommandEvent &ev)
void OnSearchClosing (wxBookCtrlEvent &evt)
void OnBnClickedStart (wxCommandEvent &evt)
void OnBnClickedStop (wxCommandEvent &evt)
void OnSearchPageChanged (wxBookCtrlEvent &evt)
Private Attributes
uint32 m_last_search_time
wxGauge * m_progressbar
CMuleNotebook * m_notebook
wxArrayString m_searchchoices
Detailed Description
This class represents the Search Dialog, which takes care of enabling the user to search and to display results in a readable manner.
Constructor & Destructor Documentation
CSearchDlg::CSearchDlg (wxWindow * pParent)
Constructor.
Parameters:
pParent The parent widget passed to the wxPanel constructor.
Member Function Documentation
void CSearchDlg::AddResult (CSearchFile * toadd)
Adds the provided result to the right result-list.
Please note that there is no duplicates checking, so the files should indeed be a new result.
References CSearchListCtrl::AddResult(), CSearchFile::GetSearchID(), and UpdateHitCount().
bool CSearchDlg::CheckTabNameExists (const wxString & searchString)
Checks if a result-page with the specified heading exists.
Parameters:
searchString The heading to look for.
void CSearchDlg::CreateNewTab (const wxString & searchString, wxUIntPtr nSearchID)
Creates a new tab and displays the specified results.
Parameters:
searchString This will be the heading of the new page.
nSearchID The results with this searchId will be displayed.
References CSearchListCtrl::EnableFiltering(), CSearchListCtrl::SetFilter(), and CSearchListCtrl::ShowResults().
void CSearchDlg::UpdateHitCount (CSearchListCtrl * page)
This function displays the the hit-count in the heading for the specified page.
Parameters:
page The page to have its heading updated.
References CSearchListCtrl::GetHiddenItemCount().
Referenced by AddResult(), and UpdateResult().
void CSearchDlg::UpdateResult (CSearchFile * toupdate)
Updates a changed result.
Parameters:
A pointer to the updated CSearchFile.
This function will update the source-count and color of the result, and if needed, it will also move the result so that the current sorting is maintained.
References CSearchFile::GetSearchID(), UpdateHitCount(), and CSearchListCtrl::UpdateResult().
The documentation for this class was generated from the following files:
src/SearchDlg.h
src/SearchDlg.cpp