aMule: CTimer Class Reference
CTimer Class Reference
Replacement for wxTimer as it doesn't work on non-X builds.
#include <Timer.h>
Public Member Functions
CTimer (wxEvtHandler *owner, int timerid=-1)
bool Start (int millisecs, bool oneShot=false)
bool IsRunning () const
void Stop ()
Private Attributes
CTimerThread * m_thread
wxEvtHandler * m_owner
int m_id
Detailed Description
Replacement for wxTimer as it doesn't work on non-X builds.
Member Function Documentation
bool CTimer::Start (int millisecs, bool oneShot = false)
Starts the timer.
Parameters:
millisecs The frequency of events.
oneShot Specifies if only one event should be produced.
References CMuleThread::Stop(), and Stop().
Referenced by CSearchList::LocalSearchEnd().
void CTimer::Stop ()
Stops the timer.
Note that this does not delete the actual thread immediatly, but no new events will be queued after calling this function.
References CMuleThread::Stop().
Referenced by Start(), and CSearchList::StopSearch().
The documentation for this class was generated from the following files:
src/Timer.h
src/Timer.cpp