aMule: MuleNotify Namespace Reference
MuleNotify Namespace Reference
This namespaces contains a number of functions and classes related to defered function calls, allowing a notification call to be delayed till it can be initiated from the main thread.
Classes
class CMuleNotiferBase
The base class of the functions.
class CMuleNotifier0
Notification functor for functions taking no arguments.
class CMuleNotifier1
Notification functor for functions taking 1 arguments.
class CMuleNotifier2
Notification functor for functions taking 2 arguments.
class CMuleNotifier3
Notification functor for functions taking 3 arguments.
class CMuleGUIEvent
This event is sent when a worker-thread makes use of a notify-macro.
Functions
void HandleNotification (const CMuleNotiferBase &ntf)
void HandleNotificationAlways (const CMuleNotiferBase &ntf)
void Search_Add_Download (CSearchFile *file, uint8 category)
void ShowUserCount (wxString NOT_ON_DAEMON(str))
void Search_Update_Progress (uint32 NOT_ON_DAEMON(val))
void DownloadCtrlUpdateItem (const void *item)
void DownloadCtrlDoItemSelectionChanged ()
void NodesURLChanged (wxString NOT_ON_DAEMON(url))
void ServersURLChanged (wxString NOT_ON_DAEMON(url))
void ShowGUI ()
void SourceCtrlUpdateSource (uint32 NOT_ON_DAEMON(source), SourceItemType NOT_ON_DAEMON(type))
void SourceCtrlAddSource (CPartFile *NOT_ON_DAEMON(owner), CClientRef NOT_ON_DAEMON(source), SourceItemType NOT_ON_DAEMON(type))
void SourceCtrlRemoveSource (uint32 NOT_ON_DAEMON(source), const CPartFile *NOT_ON_DAEMON(owner))
void SharedCtrlAddClient (CKnownFile *NOT_ON_DAEMON(owner), CClientRef NOT_ON_DAEMON(source), SourceItemType NOT_ON_DAEMON(type))
void SharedCtrlRefreshClient (uint32 NOT_ON_DAEMON(client), SourceItemType NOT_ON_DAEMON(type))
void SharedCtrlRemoveClient (uint32 NOT_ON_DAEMON(source), const CKnownFile *NOT_ON_DAEMON(owner))
void ServerRefresh (CServer *NOT_ON_DAEMON(server))
void ChatUpdateFriend (CFriend *NOT_ON_DAEMON(toupdate))
void ChatRemoveFriend (CFriend *toremove)
void SharedFilesShowFile (CKnownFile *NOT_ON_DAEMON(file))
void SharedFilesRemoveFile (CKnownFile *NOT_ON_DAEMON(file))
void SharedFilesRemoveAllFiles ()
void SharedFilesShowFileList ()
void SharedFilesUpdateItem (CKnownFile *NOT_ON_DAEMON(file))
void DownloadCtrlAddFile (CPartFile *file)
void DownloadCtrlRemoveFile (CPartFile *file)
void DownloadCtrlSort ()
void ServerAdd (CServer *NOT_ON_DAEMON(server))
void ServerRemove (CServer *NOT_ON_DAEMON(server))
void ServerRemoveDead ()
void ServerRemoveAll ()
void ServerHighlight (CServer *NOT_ON_DAEMON(server), bool NOT_ON_DAEMON(highlight))
void ServerFreeze ()
void ServerThaw ()
void ServerUpdateED2KInfo ()
void ServerUpdateKadKInfo ()
void SearchCancel ()
void SearchLocalEnd ()
void KadSearchEnd (uint32 NOT_ON_DAEMON(id))
void Search_Update_Sources (CSearchFile *result)
void Search_Add_Result (CSearchFile *NOT_ON_DAEMON(result))
void ChatConnResult (bool NOT_ON_DAEMON(success), uint64 NOT_ON_DAEMON(id), wxString NOT_ON_DAEMON(message))
void ChatProcessMsg (uint64 NOT_ON_DAEMON(sender), wxString NOT_ON_DAEMON(message))
void ChatSendCaptcha (wxString NOT_ON_DAEMON(captcha), uint64 NOT_ON_DAEMON(to_id))
void ShowConnState (long NOT_ON_DAEMON(forceUpdate))
void ShowUpdateCatTabTitles ()
void CategoryAdded ()
void CategoryUpdate (uint32 NOT_ON_DAEMON(cat))
void CategoryDelete (uint32 cat)
void PartFile_Swap_A4AF (CPartFile *file)
void PartFile_Swap_A4AF_Auto (CPartFile *file)
void PartFile_Swap_A4AF_Others (CPartFile *file)
void PartFile_Pause (CPartFile *file)
void PartFile_Resume (CPartFile *file)
void PartFile_Stop (CPartFile *file)
void PartFile_PrioAuto (CPartFile *file, bool val)
void PartFile_PrioSet (CPartFile *file, uint8 newDownPriority, bool bSave)
void PartFile_Delete (CPartFile *file)
void PartFile_SetCat (CPartFile *file, uint32 val)
void KnownFile_Up_Prio_Set (CKnownFile *file, uint8 val)
void KnownFile_Up_Prio_Auto (CKnownFile *file)
void KnownFile_Comment_Set (CKnownFile *file, wxString comment, int8 rating)
void Download_Set_Cat_Prio (uint8 cat, uint8 newprio)
void Download_Set_Cat_Status (uint8 cat, int newstatus)
void Upload_Resort_Queue ()
void IPFilter_Reload ()
void IPFilter_Update (wxString url)
void Client_Delete (CClientRef client)
void ConvertUpdateProgress (float percent, wxString text, wxString header)
void ConvertUpdateJobInfo (ConvertInfo info)
void ConvertRemoveJobInfo (unsigned id)
void ConvertClearInfos ()
void ConvertRemoveJob (unsigned id)
void ConvertRetryJob (unsigned id)
void ConvertReaddAllJobs ()
template<class ValueType >
ValueType DeepCopy (const ValueType &value)
wxString DeepCopy (const wxString &value)
void SharedFilesShowFile (CKnownFile *file)
void SharedFilesRemoveFile (CKnownFile *file)
void SharedFilesUpdateItem (CKnownFile *file)
void SourceCtrlUpdateSource (uint32 source, SourceItemType type)
void SourceCtrlAddSource (CPartFile *owner, CClientRef source, SourceItemType type)
void SourceCtrlRemoveSource (uint32 source, const CPartFile *owner)
void DownloadCtrlHideSource (CPartFile *file)
void SharedCtrlAddClient (CKnownFile *owner, CClientRef client, SourceItemType type)
void SharedCtrlRefreshClient (uint32 client, SourceItemType type)
void SharedCtrlRemoveClient (uint32 client, const CKnownFile *owner)
void ServerAdd (CServer *server)
void ServerRemove (CServer *server)
void ServerHighlight (CServer *server, bool highlight)
void ServerRefresh (CServer *server)
void KadSearchEnd (uint32 id)
void Search_Add_Result (CSearchFile *result)
void ChatUpdateFriend (CFriend *Friend)
void ChatConnResult (bool success, uint64 id, wxString message)
void ChatProcessMsg (uint64 sender, wxString message)
void ChatSendCaptcha (wxString captcha, uint64 to_id)
void ShowConnState (long state)
void ShowUserCount (wxString str)
void CategoryUpdate (uint32 cat)
void NodesURLChanged (wxString url)
void ServersURLChanged (wxString url)
void Search_Update_Progress (uint32 value)
void DoNotifyAlways (void(*func)())
template<typename A1A , typename A1B >
void DoNotifyAlways (void(*func)(A1A), A1B arg1)
template<typename A1A , typename A1B , typename A2A , typename A2B >
void DoNotifyAlways (void(*func)(A1A, A2A), A1B arg1, A2B arg2)
template<typename A1A , typename A1B , typename A2A , typename A2B , typename A3A , typename A3B >
void DoNotifyAlways (void(*func)(A1A, A2A, A3A), A1B arg1, A2B arg2, A3B arg3)
void DoNotify (void(*func)())
template<typename A1A , typename A1B >
void DoNotify (void(*func)(A1A), A1B arg1)
template<typename A1A , typename A1B , typename A2A , typename A2B >
void DoNotify (void(*func)(A1A, A2A), A1B arg1, A2B arg2)
template<typename A1A , typename A1B , typename A2A , typename A2B , typename A3A , typename A3B >
void DoNotify (void(*func)(A1A, A2A, A3A), A1B arg1, A2B arg2, A3B arg3)
Detailed Description
This namespaces contains a number of functions and classes related to defered function calls, allowing a notification call to be delayed till it can be initiated from the main thread.
Function Documentation
wxString MuleNotify::DeepCopy (const wxString & value) [inline]
Special DeepCopy for wxString, which uses reference counting.
References DeepCopy().
template<class ValueType > ValueType MuleNotify::DeepCopy (const ValueType & value) [inline]
Creates a deep copy of the object passed.
Note that this function should be overwritten as needed. See the wxString version below.
References DeepCopy().
Referenced by MuleNotify::CMuleNotifier1< ARG >::CMuleNotifier1(), MuleNotify::CMuleNotifier2< ARG_1, ARG_2 >::CMuleNotifier2(), MuleNotify::CMuleNotifier3< ARG_1, ARG_2, ARG_3 >::CMuleNotifier3(), and DeepCopy().
void MuleNotify::DoNotify (void(*)() func) [inline]
These functions take a function pointer and a set of arguments, matching those of the function-pointer.
A functor is created from these and either executed immediatly, or sent as an event in the case of non-main threads calling the functions.
Note that the return-value of the function must be void.
IMPORTANT: Note that the functions passed to DoNotify must not take arguments via references, since this causes the functors to store references to the arguments, rather than a copy and thus ends up with dangling references.
References DoNotify(), and HandleNotification().
Referenced by DoNotify().
void MuleNotify::HandleNotification (const CMuleNotiferBase & ntf)
This function will execute or queue a given notification functor.
If the caller is the main thread, the functor is executed immediatly, thus acting like a regular function call. OTOH, if the caller is a worker thread, the functor is cloned and sent via an event to wxTheApp.
Referenced by DoNotify().